<a href="https://colab.research.google.com/github/jinhoo007/vireo-support-sla-assessment/blob/main/Copy_of_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Cell 1: Install dependencies

!pip -q install pandas numpy matplotlib openpyxl python-dateutil

print("Required packages installed.")

✅ Required packages installed.

In [ ]:
# Cell 2: Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from google.colab import files

import warnings
warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

print(" Libraries imported successfully.")

✅ Libraries imported successfully.

In [ ]:
from google.colab import files

print("Upload tickets.csv")
files.upload()

Upload tickets.csv

Saving tickets.csv to tickets (3).csv

{'tickets (3).csv': b'ticket_id,created_at,first_response_at,resolved_at,status,channel,customer_id,order_id,product_sku,category,priority,assigned_team,agent_id,transfers,csat_score,refund_amount_inr,refund_reason_code,replacement_issued,customer_message,agent_notes,source_system\r\nTK-240001,2025-01-01 06:12,2025-01-01 06:20,2025-01-02 06:33,resolved,voice,C102873,,VA-EB-AIR,Billing & Payments,High,Billing,A3033,0,3,764,RETURN-QC-OK,N,[IVR transcript] you picked up the item 4 days ago and my money hasn\'t come back. please help,re: refund pending | chk reverse pickup qc status -> refunded rs 764,legacy_fd\r\nTK-240002,2025-01-01 09:01,2025-01-01 09:34,2025-01-01 09:45,resolved,social,C103321,,VA-HP-ST3,Other,Normal,Chat Frontline,A3015,0,0,,,N,"product: my strata 3 headphones\norder: vr895940\npurchased: 29/12\nissue: promo code shosw invalid\ntried: tried in caps\nexpected: resolution",Reported: promo code invalid. Checked coupon validity. Partial refund of discount amount issued. -YA,legacy_fd\r\nTK-240004,2025-01-02 00:41,2025-01-02 03:41,2025-01-04 03:59,resolved,email,C100687,VR895382,VA-EB-PL1,Delivery & Shipping,Normal,Logistics,A3028,0,4,,,N,"hi there,\norder vr895382 (my pulse). i haven\'t received my order.\ncan someone fix this?",Cust contacted re order not delivered. Confiirmed address with cx. Re-shipped fom warehouse.,legacy_fd\r\nTK-240006,2025-01-02 02:21,2025-01-02 03:38,2025-01-12 04:37,resolved,social,C104148,,VA-EB-PL1,Audio Quality,Normal,Chat Frontline,A3044,1,3,,,N,"honestly regretting this purchase. bought the pulse buds around 20/12 from vireo.in. crackling sound in the left side. i already tried different apps. i want a replacement or refund, nothing else.","1. Audio distortion\n2. Asked for a recording\n3. xfer to Escalations & Warranty\n4. adv EQ reset, resolved -KM",legacy_fd\r\nTK-240007,2025-01-02 04:05,2025-01-02 04:38,2025-01-02 05:09,resolved,social,C103733,VR883581,VA-EB-PL1,Billing & Payments,Normal,Billing,A3035,0,0,,,N,"paid via UPI, amount deducted, no order confirmation. how do i get this fixed?",cx: amount deducted without order | asked for utr -> order manually created,legacy_fd\r\nTK-240008,2025-01-02 08:06,2025-01-02 08:16,2025-01-02 08:25,resolved,voice,C102416,VR906611,VA-EB-AIR,Other,Normal,Voice Frontline,A3024,0,4,1529,CANCEL,N,"[IVR transcript] ordered the wrong colour, don\'t ship it.  vr906611",re: order cancellation | cancelled before dispatch -> full refund processed (1529),legacy_fd\r\nTK-240009,2025-01-02 10:01,2025-01-02 11:42,2025-01-02 11:56,resolved,email,C108046,VR895857,VA-EB-AIR,Delivery & Shipping,High,Logistics,A3029,0,0,,,N,"hello ji\ntracking has said out for delivery for a week now\nplease help karo\nthe airlite buds\npls reply",cx reported order not delivered. confirmed address with cx. re-shipped from warehouse.,legacy_fd\r\nTK-240010,2025-01-02 11:24,2025-01-02 11:28,2025-01-03 18:32,closed,chat,C107375,VR889597,VA-HP-ST3,Warranty & Repair,Normal,Escalations & Warranty,A3042,0,3,,,N,"hello\nwhat is the status of my warranty claim","cx updated, eta shared. issue: rma status query. followed up with service centre.",legacy_fd\r\nTK-240011,2025-01-02 12:45,2025-01-02 13:24,2025-01-02 13:45,resolved,social,C107672,VR886071,VA-EB-AIR,Charging & Battery,Normal,Chat Frontline,A3006,1,0,,,N,veyr poor quality. this is regarding airlite. battery draining even when not in use. i already fully charged and discharged twice. fix this or i am posting on twitter.,re: poor battery backup | chk fw 3.7.1 -> esc to warranty,legacy_fd\r\nTK-240012,2025-01-02 14:15,2025-01-02 14:29,2025-01-02 14:51,resolved,voice,C101036,VR899288,VA-HP-ST3,Connectivity,Normal,Voice Frontline,A3023,0,0,,,N,"[IVR transcript] pairing is not working, please help","Cx says pairing failure. Walked through forget + re-pair. Advised FW update via app, resolved. Cx satisfied on chat. -RK",legacy_fd\r\nTK-240014,2025-01-03 01:52,2025-01-03 02:42,2025-01-03 03:10,resolved,email,C102999,VR885186,VA-SP-ORB,Delivery & Shipping,Normal,Logistics,A3028,0,3,,,N,"to the vireo customer care team,\n\ni am writing with reference to my order of my orbit (vr885186) placed on 24-12-2024. order not delivered, tracking not updating. i have checked the tracking page daily. i request you to provide a resolution within 3 working days.\n\nregards,\ndiya menon","Courier confirmed delivery for 08 Jan, cx informed. Issue: delivery delayed. Checked AWB w/ courier.",legacy_fd\r\nTK-240015,2025-01-03 03:26,2025-01-03 03:35,2025-01-06 04:02,resolved,chat,C107056,,VA-HP-ST3,Returns & Refunds,Low,Returns Desk,A3037,0,0,6649,RETURN-QC-OK,N,"sir ji\nstill waiting for my refund\nkal se\nmy strata 3 headphones",Refund confirmed credited. Issue: refund not credited. Checked reverse pickup QC status. (SOP 2.7),legacy_fd\r\nTK-240016,2025-01-03 03:38,2025-01-03 03:57,2025-01-03 04:25,resolved,voice,C103315,,VA-AC-CH65,Other,Normal,Voice Frontline,A3024,0,,1499,DUP-PAYMENT,N,[IVR transcript] helo teh page failed after i paid and now nothing shows in my account pls reply,cx: failed order after payment | asked for utr -> order manually created,helpdesk\r\nTK-240016,2025-01-03 03:38,2025-01-03 03:57,2025-01-03 04:25,resolved,voice,C103315,,VA-AC-CH65,Other,Normal,Voice Frontline,A3024,0,0,1499,DUP-PAYMENT,N,[IVR transcript] helo teh page failed after i paid and now nothing shows in my account pls reply,cx: failed order after payment | asked for utr -> order manually created,legacy_fd\r\nTK-240017,2025-01-03 06:04,2025-01-03 06:12,,open,chat,C107245,,VA-EB-AIR,Warranty & Repair,High,Escalations & Warranty,A3043,0,0,,,N,lfet sie not charging in the case. please resolve asap,Customer states left bud not charging. Asked cx to clean charging pins. Replacement raised for full set.,legacy_fd\r\nTK-240018,2025-01-03 16:03,2025-01-03 16:10,2025-01-08 16:33,resolved,chat,C108722,VR901709,VA-SW-FIT,Delivery & Shipping,Normal,Logistics,A3029,0,,320,LOST-TRANSIT,N,"Hi, I bought Nexa Fit on December 24. The courier marked it delivered but nobody in my house got anything. I checked the tracking page daily. Please call me on my registered number.",contact re shipment not received. checked awb with courier. full refund processed (320).,helpdesk\r\nTK-240018,2025-01-03 16:03,2025-01-03 16:10,2025-01-08 16:33,resolved,chat,C108722,VR901709,VA-SW-FIT,Delivery & Shipping,Normal,Logistics,A3029,0,0,320,LOST-TRANSIT,N,"Hi, I bought Nexa Fit on December 24. The courier marked it delivered but nobody in my house got anything. I checked the tracking page daily. Please call me on my registered number.",contact re shipment not received. checked awb with courier. full refund processed (320).,legacy_fd\r\nTK-240019,2025-01-03 16:41,2025-01-03 19:22,2025-01-03 19:48,resolved,email,C102148,VR897377,VA-SW-FIT,App & Firmware,Normal,Email Frontline,A3002,0,0,,,N,"dear sir/madam,\n\ni am writing w/ reference to my order of my nexa fit band (vr897377) placed on 24 nov. app crashes when i open device settings. i have reinstalled the app. i request u to look into this matter at the earliest.\n\nregards,\njaspreet agarwal",cx ok,legacy_fd\r\nTK-240020,2025-01-03 16:56,2025-01-03 17:00,2025-01-04 21:19,closed,chat,C105318,,VA-EB-AIR,Warranty & Repair,Normal,Escalations & Warranty,A3039,0,2,,,N,"dear sir/madam, i bought airlite earbuds on 28/11. no update on my repair. please advise.","1. rma status query\n2. checked rma status\n3. repair completed, shipped back",legacy_fd\r\nTK-240021,2025-01-03 18:22,2025-01-03 21:50,2025-01-03 22:13,resolved,email,C105316,VR893932,VA-SW-NX1,Other,Normal,Email Frontline,A3002,0,,,,N,"Hi,\nOrdered my Nexa 2 weeks ago. Cannot login to my account.\nKindly look into it.\nThanks in advance Om",number updated,helpdesk\r\nTK-240021,2025-01-03 18:22,2025-01-03 21:50,2025-01-03 22:13,resolved,email,C105316,VR893932,VA-SW-NX1,Other,Normal,Email Frontline,A3002,0,0,,,N,"Hi,\nOrdered my Nexa 2 weeks ago. Cannot login to my account.\nKindly look into it.\nThanks in advance Om",number updated,legacy_fd\r\nTK-240022,2025-01-03 18:34,2025-01-03 18:47,2025-01-05 19:02,resolved,chat,C109335,,VA-AC-CBL,Returns & Refunds,Normal,Returns Desk,A3037,0,0,,,N,Bought the cable around 08/12 from vireo.in. Packed the box a week ago and it\'s still here. I rescheduled pickup twice. Nothing changed. I want a replacement. Awaiting response Aishwarya,Refund processed without pickup as goodwill. Issue: pickup not done. Checked piickup AWB.,legacy_fd\r\nTK-240023,2025-01-04 00:05,2025-01-04 01:56,2025-01-04 02:35,resolved,email,C103682,VR888691,VA-NB-ARC,Billing & Payments,High,Billing,A3033,0,0,1299,DUP-PAYMENT,N,"product: the neckband\norder: vr888691\npurchased: 29/12\nissue: payment was deducted but no order was created\ntried: checked bank statement\nexpected: refund",amount deducted without order | conf w/ payment gateway -> refunded rs 1299 [closed],legacy_fd\r\nTK-240025,2025-01-04 02:39,2025-01-04 02:41,2025-01-04 03:13,resolved,chat,C103854,,VA-SW-FIT,Connectivity,Normal,Chat Frontline,A3010,0,,,,Y,I have been a loyal customer and this is how you treat me. Bought Nexa Fit around 03-11-2024 from Flipkart. not pairing with my phone. I already tried on another phone. Fix this or I am posting on twitter.,"Cx says pairing failure. Walked through forget + re-pair. rplc approved, reverse pickup arranged. Cx informed.",helpdesk\r\nTK-240025,2025-01-04 02:39,2025-01-04 02:41,2025-01-04 03:13,resolved,chat,C103854,,VA-SW-FIT,Connectivity,Normal,Chat Frontline,A3010,0,0,,,Y,I have been a loyal customer and this is how you treat me. Bought Nexa Fit around 03-11-2024 from Flipkart. not pairing with my phone. I already tried on another phone. Fix this or I am posting on twitter.,"Cx says pairing failure. Walked through forget + re-pair. rplc approved, reverse pickup arranged. Cx informed.",legacy_fd\r\nTK-240026,2025-01-04 06:52,2025-01-04 09:16,2025-01-04 10:01,resolved,email,C106096,,VA-EB-AIR,Charging & Battery,Low,Email Frontline,A3022,1,0,,,N,"hello\nthe left one is dead every morning even though it was in the case all night",cx ok ~Steven,legacy_fd\r\nTK-240027,2025-01-04 13:35,2025-01-04 13:44,2025-01-04 14:04,resolved,chat,C105155,VR908953,VA-EB-AIR,Other,Normal,Chat Frontline,A3006,0,4,1709,GW-OTHER,N,"i have been a loyal customer and this is how you treat me. bought airlite around november 08 from vireo.in. battery drains very fast, barely lastts 2 hours. i already turned off always-on display. refund. now.","1. Rapid battery drain\n2. chk FW 2.5.7\n3. Advised settings change, cx satisfied",legacy_fd\r\nTK-240028,2025-01-04 22:41,2025-01-04 22:46,2025-01-05 23:14,resolved,chat,C100892,,VA-AC-CBL,Delivery & Shipping,Normal,Logistics,A3031,0,2,,,N,package not delivered even after 7 days. waiting for ur reply,"1. order not delivered\n2. conf address w/ cx\n3. rto conf, reshipped //OM",legacy_fd\r\nTK-240029,2025-01-05 09:23,2025-01-05 09:29,,open,chat,C105103,VR895558,VA-EB-PL1,Account & Login,Normal,Chat Frontline,A3004,0,0,,,N,"Hi team, This is regarding Pulse earbuds. Locked out of my own account since 3 weeks back. I tried on another browser. Nothing changed. Not acceptable at this price. Please help","customer states unable to log in. checked otp logs. number updated, rslvd. follow-up not required.",legacy_fd\r\nTK-240030,2025-01-05 10:26,2025-01-05 12:01,2025-01-08 12:25,resolved,social,C107043,VR897386,VA-HP-ST3,Delivery & Shipping,Normal,Logistics,A3027,1,,,,N,box was crushed and the my Strata 3 headphones is cracked - VR897386 - please advise,"unit rcvd damaged | photos rcvd, damage confirmed -> reverse pkp arranged (SOP 4.2)",helpdesk\r\nTK-240030,2025-01-05 10:26,2025-01-05 12:01,2025-01-08 12:25,resolved,social,C107043,VR897386,VA-HP-ST3,Delivery & Shipping,Normal,Logistics,A3027,1,0,,,N,box was crushed and the my Strata 3 headphones is cracked - VR897386 - please advise,"unit rcvd damaged | photos rcvd, damage confirmed -> reverse pkp arranged (SOP 4.2)",legacy_fd\r\nTK-240031,2025-01-05 11:07,2025-01-05 11:24,2025-01-08 11:49,resolved,voice,C105529,VR908688,VA-EB-PL1,Delivery & Shipping,High,Logistics,A3017,1,2,,,Y,received damaged product,"contact re unit rcvd damaged. photos rcvd, damage conf. xfer to email frontline. replacement raised, rma shared w/ cx. follow-up not required. ~Shreya",legacy_fd\r\nTK-240032,2025-01-05 11:39,2025-01-05 11:50,2025-01-05 12:01,resolved,voice,C106526,VR908984,VA-AC-CBL,Other,Low,Voice Frontline,A3023,0,,399,CANCEL,N,"Dear team, I bought braided cable on 23/12.  Change of mind, please stop the shipment. I tried cancel button, greyed out. Nothing changed. Very poor quality. Waiting for your reply. Thanks in advance, Rohit",Refund of Rs 399 initiated to source. Issue: cancellation request. chk shipment status. -RK,helpdesk\r\nTK-240032,2025-01-05 11:39,2025-01-05 11:50,2025-01-05 12:01,resolved,voice,C106526,VR908984,VA-AC-CBL,Other,Low,Voice Frontline,A3023,0,0,399,CANCEL,N,"Dear team, I bought braided cable on 23/12.  Change of mind, please stop the shipment. I tried cancel button, greyed out. Nothing changed. Very poor quality. Waiting for your reply. Thanks in advance, Rohit",Refund of Rs 399 initiated to source. Issue: cancellation request. chk shipment status. -RK,legacy_fd\r\nTK-240033,2025-01-05 15:28,2025-01-05 15:33,2025-01-05 15:52,resolved,chat,C102467,,VA-HP-ST3,Billing & Payments,High,Billing,A3034,0,0,700,PRICE-ADJ,N,I bought my Strata 3 headphones on 05 Jan. Discount was not applied at checkout. I tried in caps. Please call me on my registered number. Thanks Isha George,Partial refund of discount amount issued. Issue: promo code invalid. Cecked coupon validity. [closed],legacy_fd\r\nTK-240035,2025-01-05 17:00,2025-01-05 17:05,2025-01-05 17:14,resolved,chat,C104108,,VA-EB-PL1,Billing & Payments,Low,Billing,A3032,0,0,,,N,"Dear Sir/Madam,\n\nI am writing with reference to my order of Pulse earbuds placed on 31 Dec. Need the bill with my firm\'s GSTIN on it. I have checked orders page. I requset you to provide a resolution within 3 working days.\n\nRegards,\nKrishna Tiwari",invoice not downloading | updated gstin on ord -> invoice emailed,legacy_fd\r\nTK-240036,2025-01-05 17:17,2025-01-05 17:21,2025-01-05 17:43,resolved,chat,C104049,VR904854,VA-SW-FIT,Account & Login,Low,Chat Frontline,A3016,0,0,,,N,"hey\nthe login code never arrives, tried 6 times\nmy nexa fit band vr904854\nkindly do the needful","cx: login issue | chk otp logs -> otp resent, cx logged in",legacy_fd\r\nTK-240037,2025-01-06 02:52,2025-01-06 03:06,2025-01-22 04:49,resolved,voice,C105939,,VA-EB-PL1,Audio Quality,Low,Voice Frontline,A3044,1,2,,,Y,This is regarding the Pulse buds. Crackling sound in the right side. How do I get this fixed? Awaiting response Tanvi,"issue: crackling/distortion | checked with different source -> replacement approved, reverse pickup arranged | xfer escalations & warranty",legacy_fd\r\nTK-240038,2025-01-06 06:39,2025-01-06 08:00,2025-01-06 08:11,closed,voice,C106071,,VA-EB-AIR,Delivery & Shipping,Normal,Logistics,A3021,1,3,,,N,"hii\norder not delivered, tracking not updating\nthe airlite buds\n??","1. Order not delivered\n2. Raised ticket with courier partner\n3. Transferred to Email Frontline\n4. Refund initiated as lost in transit",legacy_fd\r\nTK-240039,2025-01-06 06:59,2025-01-06 07:09,2025-01-06 07:23,resolved,chat,C104365,VR882203,VA-EB-PL1,Other,Normal,Chat Frontline,A3005,0,4,2499,DOA-REPL,N,"works for music but useless for meetings, vr882203, kindly look into it","low mic pickup | checked mic permissions on phone -> rfnd approved, rs 2499, 5-7 working days (sop 2.7) //SAM",helpdesk\r\nTK-240039,2025-01-06 06:59,2025-01-06 07:09,2025-01-06 07:23,resolved,chat,C104365,VR882203,VA-EB-PL1,Other,Normal,Chat Frontline,A3005,0,4,2499,DOA-REPL,N,"works for music but useless for meetings, vr882203, kindly look into it","low mic pickup | checked mic permissions on phone -> rfnd approved, rs 2499, 5-7 working days (sop 2.7) //SAM",legacy_fd\r\nTK-240041,2025-01-06 09:58,2025-01-06 10:03,2025-01-06 10:31,closed,chat,C100178,,VA-NB-ARC,Audio Quality,Normal,Chat Frontline,A3012,0,,,,Y,"hii\ndistorted audio at high volume\nthe neckband\n??",Cust contacted re static noise in audio. Checked with different source. Replacement unit dispatched. Case closed with cx consent.,helpdesk\r\nTK-240041,2025-01-06 09:58,2025-01-06 10:03,2025-01-06 10:31,closed,chat,C100178,,VA-NB-ARC,Audio Quality,Normal,Chat Frontline,A3012,0,0,,,Y,"hii\ndistorted audio at high volume\nthe neckband\n??",Cust contacted re static noise in audio. Checked with different source. Replacement unit dispatched. Case closed with cx consent.,legacy_fd\r\nTK-240042,2025-01-06 13:25,2025-01-06 18:19,2025-01-06 18:35,closed,email,C105127,VR909891,VA-SP-ORB,Delivery & Shipping,Normal,Logistics,A3031,0,0,,,N,"Dear Sir/Madam,\n\nI am writing with reference to my order of Orbit speaker placed on 27/12. Paid on 27/12, still waiting for something to show up. I have checked with neighbours. I request you to kindly arrange a replacement.\n\nYours faithfully,\nVivaan Reddy","1. shipment not received\n2. raised ticket w/ courier partner\n3. refund initiated as lost in transit",legacy_fd\r\nTK-240043,2025-01-06 13:34,2025-01-06 13:40,2025-01-11 13:59,resolved,chat,C103002,VR901732,VA-HP-ST2,Delivery & Shipping,Normal,Logistics,A3027,0,2,,,N,"I am losing patience. Bought my Strata 2 headphones aruond 25-12-2024 from Amazon. order not delivered, tracking not updating. I already called teh courier. I want a replacement or refund, nothing else","cx: shipment not received | raised ticket with crr partner -> rto confirmed, reshipped",legacy_fd\r\nTK-240044,2025-01-06 18:41,2025-01-06 20:57,2025-01-06 21:07,resolved,email,C104063,VR909523,VA-SW-FIT,Other,Low,Email Frontline,A3002,0,,,,N,"Hey,\nI bought Nexa Fit on 27 Dec. I moved houses yesterday and the order is going to the old flat.\nI tried editing in app.\nPlease advise.\nRegards,",closed,helpdesk\r\nTK-240044,2025-01-06 18:41,2025-01-06 20:57,2025-01-06 21:07,resolved,email,C104063,VR909523,VA-SW-FIT,Other,Low,Email Frontline,A3002,0,0,,,N,"Hey,\nI bought Nexa Fit on 27 Dec. I moved houses yesterday and the order is going to the old flat.\nI tried editing in app.\nPlease advise.\nRegards,",closed,legacy_fd\r\nTK-240045,2025-01-07 03:44,2025-01-07 03:49,2025-01-07 04:00,resolved,chat,C101165,VR894903,VA-AC-CBL,Account & Login,Normal,Chat Frontline,A3005,0,,,,N,"sir ji\nthe login code never arrives, tried 6 times\n10 days ago se\nurgent","issue: otp not received | checked otp logs -> number updated, resolved //SAM",helpdesk\r\nTK-240045,2025-01-07 03:44,2025-01-07 03:49,2025-01-07 04:00,resolved,chat,C101165,VR894903,VA-AC-CBL,Account & Login,Normal,Chat Frontline,A3005,0,0,,,N,"sir ji\nthe login code never arrives, tried 6 times\n10 days ago se\nurgent","issue: otp not received | checked otp logs -> number updated, resolved //SAM",legacy_fd\r\nTK-240046,2025-01-07 06:04,2025-01-07 06:14,2025-01-07 06:27,resolved,chat,C106239,VR908371,VA-AC-CH65,Other,Normal,Chat Frontline,A3013,0,4,1499,CANCEL,N,"ordered the wrong colour, don\'t ship it.  can someone fix this?","1. Order cancellation\n2. Checked shipment status\n3. Refunded Rs 1499 [closed]",legacy_fd\r\nTK-240047,2025-01-07 11:45,2025-01-07 14:45,2025-01-07 14:55,resolved,social,C101207,VR898430,VA-NB-ARC,Account & Login,Normal,Chat Frontline,A3012,0,0,,,N,"Hi team, Order VR898430 (my Arc). Not receiving OTP to login. I tried 5 times. Nothing changed. What do I do now?","Reported: login issue. Checked number on account. OTP resent, cx logged in. Cx informed.",legacy_fd\r\nTK-240048,2025-01-07 17:29,2025-01-07 17:32,2025-01-07 18:00,resolved,chat,C108277,,VA-EB-PL1,Delivery & Shipping,Normal,Logistics,A3031,0,5,2124,LOST-TRANSIT,N,"hello, bought my pulse around 26/12 from vireo.in. i haven\'t received my order. i checked wiht neighbours. nothing changed. can someone fix this?","1. ord not delivered\n2. raised ticket with crr parrtner\n3. rto conf, reshipped //OM",legacy_fd\r\nTK-

In [ ]:
print("Upload agents.csv")
files.upload()

Upload agents.csv

Saving agents.csv to agents (2).csv

{'agents (2).csv': b'agent_id,name,site,team,shift,tier,from_date,to_date\r\nA3001,Zoya Mehta,Indore,Chat Frontline,Night,1,2021-04-20,2025-06-29\r\nA3002,Tarun Mishra,Indore,Chat Frontline,Night,1,2023-02-12,2025-06-29\r\nA3002,Tarun Mishra,Indore,Chat Frontline,Day,1,2025-06-30,\r\nA3003,Harpreet Deshpande,Indore,Chat Frontline,Night,1,2023-06-14,2025-06-29\r\nA3003,Harpreet Deshpande,Indore,Chat Frontline,Day,1,2025-06-30,\r\nA3004,Krishna Naidu,Bengaluru,Chat Frontline,Day,1,2022-12-30,\r\nA3005,Sameer Joshi,Bengaluru,Chat Frontline,Morning,1,2021-07-28,\r\nA3006,Lakshmi Reddy,Bengaluru,Chat Frontline,Day,1,2021-02-05,\r\nA3007,Neha Gaikwad,Bengaluru,Chat Frontline,Morning,1,2023-09-10,\r\nA3008,Steven Kaur,Indore,Chat Frontline,Morning,1,2022-05-02,\r\nA3009,Ramesh Patel,Bengaluru,Chat Frontline,Morning,1,2024-06-02,\r\nA3010,Neha Chatterjee,Indore,Chat Frontline,Morning,1,2022-04-14,\r\nA3011,Karan Roy,Indore,Chat Frontline,Morning,1,2022-06-26,\r\nA3012,Lakshmi Sethi,Bengaluru,Chat Frontline,Day,1,2023-02-06,\r\nA3013,Ritika Chatterjee,Indore,Chat Frontline,Morning,1,2021-08-23,\r\nA3014,Diya Patil,Bengaluru,Chat Frontline,Morning,1,2021-08-19,\r\nA3015,Yash Agarwal,Bengaluru,Chat Frontline,Day,1,2023-09-30,\r\nA3016,Deepak Jadhav,Indore,Email Frontline,Night,1,2023-03-07,2025-06-29\r\nA3017,Shreya Bhatt,Indore,Email Frontline,Night,1,2023-05-22,2025-06-29\r\nA3018,Farah Sheikh,Bengaluru,Email Frontline,Morning,1,2024-09-24,\r\nA3019,Sai Sandhu,Bengaluru,Email Frontline,Morning,1,2024-03-04,\r\nA3020,Ramesh Ghosh,Bengaluru,Email Frontline,Day,1,2020-12-26,\r\nA3021,Aditya Dhillon,Bengaluru,Email Frontline,Day,1,2022-09-20,\r\nA3022,Steven Tiwari,Bengaluru,Email Frontline,Day,1,2022-10-14,\r\nA3023,Rahul Khanna,Bengaluru,Voice Frontline,Day,1,2022-07-13,\r\nA3024,Kunal Khanna,Bengaluru,Voice Frontline,Morning,1,2022-10-15,\r\nA3025,Lobsang Rao,Bengaluru,Voice Frontline,Morning,1,2022-12-30,\r\nA3026,Lakshmi Qureshi,Bengaluru,Voice Frontline,Day,1,2021-02-03,\r\nA3027,Dev Chatterjee,Indore,Logistics,Day,1,2023-12-23,\r\nA3028,Krishna Kaur,Indore,Logistics,Morning,1,2021-09-12,\r\nA3029,Rajat Iyer,Bengaluru,Logistics,Day,1,2022-06-18,\r\nA3030,Sunita Srivastava,Bengaluru,Logistics,Day,1,2022-10-07,\r\nA3031,Om Malhotra,Bengaluru,Logistics,Morning,1,2021-07-24,\r\nA3032,Aadhya Sheikh,Indore,Billing,Morning,1,2021-03-23,\r\nA3033,Amit Kulkarni,Bengaluru,Billing,Morning,1,2023-02-26,\r\nA3034,Thomas Patel,Bengaluru,Billing,Day,1,2022-03-04,\r\nA3035,Rohit Mukherjee,Bengaluru,Billing,Morning,1,2024-11-28,\r\nA3036,Rohit Shinde,Bengaluru,Returns Desk,Day,1,2023-08-17,\r\nA3037,Rahul Sen,Bengaluru,Returns Desk,Morning,1,2021-03-02,\r\nA3038,Amit Yadav,Bengaluru,Returns Desk,Day,1,2023-10-03,\r\nA3039,Riya Gaikwad,Bengaluru,Escalations & Warranty,Morning,2,2022-04-10,\r\nA3040,Thomas Arora,Bengaluru,Escalations & Warranty,Day,2,2024-07-26,\r\nA3041,Riya Fernandes,Indore,Escalations & Warranty,Day,2,2023-05-27,\r\nA3042,Steven Chopra,Bengaluru,Escalations & Warranty,Day,2,2022-06-11,\r\nA3043,Rohit Jain,Bengaluru,Escalations & Warranty,Morning,2,2022-01-28,\r\nA3044,Kunal Malhotra,Bengaluru,Escalations & Warranty,Day,2,2023-02-08,\r\n'}

In [ ]:
print("Upload orders.csv")
files.upload()

Upload orders.csv

Saving orders.csv to orders (2).csv

{'orders (2).csv': b'order_id,customer_id,sku,order_date,channel,qty,order_value_inr,lot_code\r\nVR899143,C103913,VA-AC-CH65,2024-06-15,vireo.in,1,1499,CH65-2405-2\r\nVR900081,C109313,VA-HP-ST2,2024-06-15,Amazon,2,9998,ST2-2403-3\r\nVR900737,C102597,VA-SW-NX1,2024-06-15,Amazon,2,8998,NX1-2403-4\r\nVR903662,C100806,VA-EB-PL1,2024-06-15,vireo.in,1,2124,PL1-2404-4\r\nVR909588,C101401,VA-AC-CBL,2024-06-15,vireo.in,1,399,CBL-2403-4\r\nVR880945,C100231,VA-AC-CH65,2024-06-16,Amazon,1,1274,CH65-2404-1\r\nVR881188,C102347,VA-SP-ORB,2024-06-16,Flipkart,1,4799,ORB-2404-1\r\nVR882291,C100679,VA-NB-ARC,2024-06-16,vireo.in,1,1039,ARC-2405-3\r\nVR883059,C107275,VA-EB-PL1,2024-06-16,Flipkart,1,2499,PL1-2403-2\r\nVR886305,C102205,VA-AC-CH65,2024-06-16,vireo.in,1,1499,CH65-2404-1\r\nVR887670,C109095,VA-EB-PL1,2024-06-16,vireo.in,1,1999,PL1-2405-2\r\nVR893851,C101873,VA-SP-ORB,2024-06-16,vireo.in,1,5099,ORB-2405-3\r\nVR905932,C101153,VA-SW-NX1,2024-06-16,Amazon,1,4749,NX1-2404-1\r\nVR885703,C109439,VA-SP-ORB,2024-06-17,Amazon,1,5399,ORB-2404-1\r\nVR886158,C103625,VA-SP-ORB,2024-06-17,vireo.in,1,5699,ORB-2404-1\r\nVR895230,C100767,VA-HP-ST2,2024-06-17,Flipkart,1,4749,ST2-2405-2\r\nVR895403,C104901,VA-EB-PL1,2024-06-17,vireo.in,1,2499,PL1-2404-4\r\nVR899645,C102000,VA-NB-ARC,2024-06-17,Amazon,1,1299,ARC-2403-3\r\nVR891013,C102563,VA-SW-NX1,2024-06-18,Amazon,1,4499,NX1-2405-2\r\nVR899836,C101026,VA-EB-PL1,2024-06-18,Flipkart,1,2249,PL1-2404-2\r\nVR900077,C100852,VA-NB-ARC,2024-06-18,Flipkart,1,1299,ARC-2404-1\r\nVR901908,C107070,VA-HP-ST2,2024-06-18,vireo.in,1,4999,ST2-2403-1\r\nVR903033,C109460,VA-AC-CH65,2024-06-18,vireo.in,1,1349,CH65-2404-1\r\nVR883113,C103651,VA-EB-PL1,2024-06-19,vireo.in,1,2499,PL1-2405-3\r\nVR884367,C102823,VA-EB-PL1,2024-06-19,vireo.in,1,2499,PL1-2404-4\r\nVR885248,C106467,VA-EB-PL1,2024-06-19,vireo.in,1,2124,PL1-2403-2\r\nVR885836,C102558,VA-EB-PL1,2024-06-19,Flipkart,1,2499,PL1-2403-3\r\nVR887833,C107132,VA-SW-NX1,2024-06-19,vireo.in,1,4499,NX1-2405-3\r\nVR897809,C107905,VA-SP-ORB,2024-06-19,Flipkart,1,5099,ORB-2405-3\r\nVR900814,C108837,VA-AC-CH65,2024-06-19,vireo.in,1,1499,CH65-2405-4\r\nVR904134,C106453,VA-EB-PL1,2024-06-19,Amazon,1,2499,PL1-2405-2\r\nVR905140,C106312,VA-AC-CH65,2024-06-19,vireo.in,1,1499,CH65-2403-2\r\nVR880011,C105318,VA-EB-PL1,2024-06-20,Amazon,1,1999,PL1-2404-3\r\nVR895664,C108808,VA-HP-ST2,2024-06-20,Amazon,2,9998,ST2-2405-2\r\nVR897380,C108850,VA-EB-PL1,2024-06-20,Amazon,1,2249,PL1-2404-4\r\nVR901857,C105503,VA-HP-ST2,2024-06-20,vireo.in,1,4749,ST2-2405-2\r\nVR907834,C103937,VA-AC-CH65,2024-06-20,Amazon,1,1499,CH65-2405-4\r\nVR881793,C106808,VA-EB-PL1,2024-06-21,vireo.in,1,2499,PL1-2404-2\r\nVR881859,C104761,VA-NB-ARC,2024-06-21,vireo.in,1,1299,ARC-2405-2\r\nVR883329,C106317,VA-AC-CH65,2024-06-21,Flipkart,1,1349,CH65-2405-3\r\nVR887404,C106970,VA-HP-ST2,2024-06-21,vireo.in,1,4499,ST2-2404-1\r\nVR899863,C109286,VA-EB-PL1,2024-06-21,Amazon,2,4498,PL1-2405-4\r\nVR882179,C108796,VA-EB-PL1,2024-06-22,vireo.in,1,2499,PL1-2405-2\r\nVR886784,C106968,VA-SW-NX1,2024-06-22,vireo.in,1,4749,NX1-2404-4\r\nVR887407,C105666,VA-HP-ST2,2024-06-22,Amazon,1,4499,ST2-2403-1\r\nVR902109,C102220,VA-SW-NX1,2024-06-22,Amazon,1,4749,NX1-2405-3\r\nVR904109,C105226,VA-SW-NX1,2024-06-22,Amazon,1,4499,NX1-2405-3\r\nVR905175,C106332,VA-AC-CH65,2024-06-22,vireo.in,1,1199,CH65-2404-1\r\nVR909048,C100331,VA-NB-ARC,2024-06-22,vireo.in,1,1299,ARC-2404-3\r\nVR881205,C103956,VA-NB-ARC,2024-06-23,vireo.in,1,1104,ARC-2403-1\r\nVR885315,C101929,VA-EB-PL1,2024-06-23,vireo.in,1,1999,PL1-2403-1\r\nVR885639,C106197,VA-SP-ORB,2024-06-23,vireo.in,1,5099,ORB-2405-1\r\nVR892200,C101185,VA-HP-ST2,2024-06-23,Amazon,1,4499,ST2-2404-2\r\nVR894316,C102505,VA-EB-PL1,2024-06-23,vireo.in,1,2124,PL1-2405-4\r\nVR894371,C102419,VA-SP-ORB,2024-06-23,vireo.in,1,5999,ORB-2404-2\r\nVR897526,C101548,VA-SW-NX1,2024-06-23,vireo.in,2,9998,NX1-2403-4\r\nVR897647,C108856,VA-EB-PL1,2024-06-23,vireo.in,1,2499,PL1-2403-2\r\nVR897968,C101694,VA-EB-PL1,2024-06-23,vireo.in,1,1999,PL1-2403-1\r\nVR901113,C100309,VA-AC-CH65,2024-06-23,vireo.in,1,1499,CH65-2405-2\r\nVR906004,C106025,VA-EB-PL1,2024-06-23,vireo.in,1,2374,PL1-2403-3\r\nVR906612,C109069,VA-SP-ORB,2024-06-23,Amazon,1,5699,ORB-2404-2\r\nVR884359,C102661,VA-SP-ORB,2024-06-24,Amazon,1,5999,ORB-2405-2\r\nVR885675,C101301,VA-EB-PL1,2024-06-24,vireo.in,1,2499,PL1-2404-1\r\nVR893259,C106556,VA-HP-ST2,2024-06-24,vireo.in,1,4499,ST2-2403-4\r\nVR897938,C104265,VA-AC-CH65,2024-06-24,Flipkart,1,1499,CH65-2404-4\r\nVR900259,C103946,VA-EB-PL1,2024-06-24,Amazon,1,2374,PL1-2403-1\r\nVR901640,C100701,VA-HP-ST2,2024-06-24,Amazon,1,4749,ST2-2404-2\r\nVR904706,C105715,VA-SP-ORB,2024-06-24,vireo.in,1,5999,ORB-2406-3\r\nVR886812,C105295,VA-SP-ORB,2024-06-25,Flipkart,1,5699,ORB-2403-1\r\nVR891910,C100161,VA-EB-PL1,2024-06-25,vireo.in,1,2249,PL1-2404-3\r\nVR907393,C106115,VA-EB-PL1,2024-06-25,vireo.in,1,2249,PL1-2403-3\r\nVR882184,C100406,VA-SP-ORB,2024-06-26,vireo.in,1,5099,ORB-2405-4\r\nVR887506,C106749,VA-EB-PL1,2024-06-26,Amazon,1,1999,PL1-2405-1\r\nVR889806,C104727,VA-EB-PL1,2024-06-26,vireo.in,1,2374,PL1-2403-3\r\nVR880717,C100901,VA-EB-PL1,2024-06-27,Amazon,1,2499,PL1-2404-4\r\nVR886033,C104225,VA-SW-NX1,2024-06-27,vireo.in,1,4999,NX1-2403-3\r\nVR886937,C102561,VA-HP-ST2,2024-06-27,vireo.in,1,4999,ST2-2405-2\r\nVR894452,C108799,VA-SP-ORB,2024-06-27,Amazon,1,5999,ORB-2405-2\r\nVR895902,C108428,VA-EB-PL1,2024-06-27,Amazon,1,2499,PL1-2404-3\r\nVR880622,C102326,VA-EB-PL1,2024-06-28,vireo.in,1,1999,PL1-2403-2\r\nVR888836,C104387,VA-SW-NX1,2024-06-28,Amazon,1,4999,NX1-2403-3\r\nVR890572,C101188,VA-SP-ORB,2024-06-28,vireo.in,1,4799,ORB-2404-2\r\nVR891047,C100611,VA-NB-ARC,2024-06-28,vireo.in,1,1299,ARC-2404-4\r\nVR892702,C104195,VA-HP-ST2,2024-06-28,vireo.in,2,7998,ST2-2404-4\r\nVR905259,C104451,VA-SP-ORB,2024-06-28,vireo.in,1,5999,ORB-2405-4\r\nVR906433,C107484,VA-NB-ARC,2024-06-28,Flipkart,1,1234,ARC-2403-1\r\nVR909220,C102509,VA-NB-ARC,2024-06-28,vireo.in,1,1299,ARC-2405-4\r\nVR880215,C105375,VA-EB-PL1,2024-06-29,vireo.in,1,1999,PL1-2404-3\r\nVR894349,C101542,VA-AC-CH65,2024-06-29,vireo.in,1,1499,CH65-2403-3\r\nVR906988,C108617,VA-EB-PL1,2024-06-29,Flipkart,1,2499,PL1-2405-1\r\nVR880443,C108544,VA-EB-PL1,2024-06-30,Amazon,1,2499,PL1-2404-2\r\nVR885382,C100609,VA-EB-PL1,2024-06-30,vireo.in,1,2249,PL1-2403-2\r\nVR895785,C108136,VA-EB-PL1,2024-06-30,Flipkart,1,2499,PL1-2406-3\r\nVR901506,C105088,VA-AC-CH65,2024-06-30,vireo.in,1,1199,CH65-2404-1\r\nVR904676,C103718,VA-SP-ORB,2024-06-30,Amazon,1,5999,ORB-2404-1\r\nVR906701,C100086,VA-AC-CBL,2024-06-30,Amazon,1,319,CBL-2404-1\r\nVR881011,C108587,VA-AC-CH65,2024-07-01,Amazon,1,1499,CH65-2404-3\r\nVR893257,C107195,VA-HP-ST2,2024-07-01,Amazon,2,9498,ST2-2403-3\r\nVR894133,C100674,VA-SP-ORB,2024-07-01,vireo.in,1,5999,ORB-2404-4\r\nVR895264,C100365,VA-SW-NX1,2024-07-01,Amazon,1,4999,NX1-2404-3\r\nVR897757,C100314,VA-AC-CBL,2024-07-01,Amazon,1,319,CBL-2405-1\r\nVR899318,C100152,VA-NB-ARC,2024-07-01,Amazon,1,1299,ARC-2404-3\r\nVR888326,C104357,VA-EB-PL1,2024-07-02,vireo.in,1,2249,PL1-2405-2\r\nVR891195,C107763,VA-SW-NX1,2024-07-02,Flipkart,1,4749,NX1-2404-1\r\nVR895843,C103095,VA-EB-PL1,2024-07-02,Amazon,1,2374,PL1-2405-2\r\nVR908680,C102305,VA-EB-PL1,2024-07-02,Amazon,1,2124,PL1-2404-3\r\nVR909815,C104665,VA-SP-ORB,2024-07-02,vireo.in,1,5999,ORB-2404-2\r\nVR887582,C102721,VA-HP-ST2,2024-07-03,vireo.in,1,4749,ST2-2406-2\r\nVR884248,C108271,VA-AC-CH65,2024-07-04,vireo.in,1,1424,CH65-2404-4\r\nVR885799,C108126,VA-SW-NX1,2024-07-04,Amazon,1,4999,NX1-2406-4\r\nVR900752,C103487,VA-EB-PL1,2024-07-04,Flipkart,2,4748,PL1-2406-1\r\nVR904235,C103488,VA-SP-ORB,2024-07-04,Amazon,1,5399,ORB-2405-4\r\nVR883337,C105536,VA-HP-ST2,2024-07-05,vireo.in,1,4999,ST2-2404-1\r\nVR892595,C106167,VA-SP-ORB,2024-07-05,vireo.in,1,5399,ORB-2406-2\r\nVR884655,C100190,VA-SP-ORB,2024-07-06,vireo.in,1,5999,ORB-2403-3\r\nVR885896,C106026,VA-HP-ST2,2024-07-06,Flipkart,1,3999,ST2-2405-3\r\nVR892158,C104724,VA-SP-ORB,2024-07-06,vireo.in,1,5999,ORB-2404-3\r\nVR895454,C107707,VA-NB-ARC,2024-07-06,Flipkart,1,1039,ARC-2403-3\r\nVR898324,C102110,VA-HP-ST2,2024-07-06,Flipkart,1,3999,ST2-2405-4\r\nVR903714,C103175,VA-EB-PL1,2024-07-06,vireo.in,1,1999,PL1-2404-1\r\nVR905796,C106061,VA-NB-ARC,2024-07-06,vireo.in,1,1299,ARC-2403-4\r\nVR909099,C102980,VA-EB-PL1,2024-07-06,vireo.in,1,2249,PL1-2404-3\r\nVR881870,C102933,VA-EB-PL1,2024-07-07,vireo.in,1,2499,PL1-2405-3\r\nVR887481,C109428,VA-EB-PL1,2024-07-07,Amazon,1,1999,PL1-2405-1\r\nVR898267,C107089,VA-HP-ST2,2024-07-07,vireo.in,1,4249,ST2-2404-3\r\nVR898404,C103261,VA-SP-ORB,2024-07-07,Flipkart,1,5999,ORB-2404-4\r\nVR901265,C101617,VA-EB-PL1,2024-07-07,vireo.in,1,2499,PL1-2403-1\r\nVR906409,C102747,VA-EB-PL1,2024-07-07,vireo.in,1,2374,PL1-2405-4\r\nVR907603,C103997,VA-NB-ARC,2024-07-07,vireo.in,1,1104,ARC-2406-1\r\nVR909600,C101334,VA-EB-PL1,2024-07-07,vireo.in,1,2374,PL1-2405-3\r\nVR881617,C105165,VA-SP-ORB,2024-07-08,vireo.in,1,5399,ORB-2404-2\r\nVR887184,C101682,VA-EB-PL1,2024-07-08,Amazon,1,2499,PL1-2405-1\r\nVR889776,C106533,VA-AC-CBL,2024-07-08,Amazon,1,399,CBL-2404-1\r\nVR903605,C106620,VA-NB-ARC,2024-07-08,Amazon,1,1299,ARC-2404-1\r\nVR880064,C101412,VA-EB-PL1,2024-07-09,vireo.in,1,2499,PL1-2403-3\r\nVR882373,C102657,VA-SP-ORB,2024-07-09,Amazon,1,5999,ORB-2406-4\r\nVR886020,C107636,VA-SP-ORB,2024-07-09,Flipkart,1,5999,ORB-2403-1\r\nVR888616,C100857,VA-EB-PL1,2024-07-09,Amazon,1,2499,PL1-2405-1\r\nVR890642,C109270,VA-EB-PL1,2024-07-09,vireo.in,1,2124,PL1-2403-1\r\nVR894741,C105901,VA-NB-ARC,2024-07-09,Amazon,1,1039,ARC-2404-1\r\nVR898420,C107916,VA-NB-ARC,2024-07-09,Amazon,1,1299,ARC-2405-2\r\nVR902209,C106023,VA-NB-ARC,2024-07-09,vireo.in,1,1299,ARC-2404-1\r\nVR902466,C108488,VA-AC-CH65,2024-07-09,Amazon,1,1499,CH65-2406-2\r\nVR902488,C106146,VA-SP-ORB,2024-07-09,Flipkart,1,5399,ORB-2406-3\r\nVR902973,C107920,VA-HP-ST2,2024-07-09,vireo.in,1,4499,ST2-2405-3\r\nVR903153,C100292,VA-AC-CH65,2024-07-09,vireo.in,2,2698,CH65-2405-4\r\nVR903474,C102251,VA-EB-PL1,2024-07-09,vireo.in,1,2124,PL1-2404-2\r\nVR909438,C100070,VA-EB-PL1,2024-07-09,Amazon,1,1999,PL1-2406-3\r\nVR884335,C103477,VA-EB-PL1,2024-07-10,vireo.in,1,2499,PL1-2404-3\r\nVR884390,C100033,VA-HP-ST2,2024-07-10,Amazon,1,4999,ST2-2404-3\r\nVR884581,C100454,VA-EB-PL1,2024-07-10,vireo.in,1,2499,PL1-2405-3\r\nVR889217,C101631,VA-EB-PL1,2024-07-10,vireo.in,1,2499,PL1-2404-2\r\nVR892609,C100555,VA-EB-PL1,2024-07-10,vireo.in,1,2249,PL1-2404-4\r\nVR892801,C100969,VA-SP-ORB,2024-07-10,Flipkart,2,9598,ORB-2405-1\r\nVR898371,C105191,VA-AC-CBL,2024-07-10,vireo.in,1,399,CBL-2404-1\r\nVR901710,C104976,VA-SW-NX1,2024-07-10,vireo.in,1,3999,NX1-2405-3\r\nVR903910,C104758,VA-AC-CH65,2024-07-10,Amazon,2,2998,CH65-2404-2\r\nVR882205,C106443,VA-EB-PL1,2024-07-11,vireo.in,1,2249,PL1-2405-2\r\nVR885408,C107157,VA-SP-ORB,2024-07-11,Flipkart,1,5699,ORB-2406-2\r\nVR885573,C100179,VA-NB-ARC,2024-07-11,vireo.in,1,1299,ARC-2405-3\r\nVR898106,C103665,VA-EB-PL1,2024-07-11,Amazon,1,2249,PL1-2406-2\r\nVR899212,C100943,VA-AC-CH65,2024-07-11,Amazon,1,1274,CH65-2405-1\r\nVR902309,C103107,VA-HP-ST2,2024-07-11,vireo.in,1,4999,ST2-2405-3\r\nVR904058,C107883,VA-EB-PL1,2024-07-11,Amazon,1,2499,PL1-2405-3\r\nVR904320,C105140,VA-EB-PL1,2024-07-11,Amazon,1,2249,PL1-2406-4\r\nVR885585,C107250,VA-EB-PL1,2024-07-12,Amazon,1,2374,PL1-2403-2\r\nVR889681,C106089,VA-EB-PL1,2024-07-12,Flipkart,1,2249,PL1-2404-2\r\nVR890739,C100022,VA-EB-PL1,2024-07-12,vireo.in,1,2499,PL1-2406-2\r\nVR891069,C103419,VA-SW-NX1,2024-07-12,Flipkart,1,4749,NX1-2406-2\r\nVR894580,C101099,VA-AC-CH65,2024-07-12,vireo.in,1,1424,CH65-2403-3\r\nVR895005,C102721,VA-AC-CH65,2024-07-12,Amazon,1,1424,CH65-2405-3\r\nVR895242,C109097,VA-EB-PL1,2024-07-12,vireo.in,1,1999,PL1-2404-3\r\nVR901206,C103894,VA-SW-NX1,2024-07-12,vireo.in,1,4499,NX1-2404-1\r\nVR901450,C101206,VA-EB-PL1,2024-07-12,Flipkart,1,2249,PL1-2406-4\r\nVR901674,C108669,VA-EB-PL1,2024-07-12,Flipkart,1,2499,PL1-2405-4\r\nVR886939,C100459,VA-NB-ARC,2024-07-13,vireo.in,1,1104,ARC-2406-1\r\nVR897116,C104216,VA-AC-CH65,2024-07-13,Amazon,1,1349,CH65-2405-1\r\nVR900959,C104328,VA-AC-CH65,2024-07-13,Amazon,1,1349,CH65-2405-3\r\nVR882629,C104620,VA-EB-PL1,2024-07-14,Amazon,1,1999,PL1-2405-2\r\nVR892017,C102335,VA-NB-ARC,2024-07-14,vireo.in,1,1299,ARC-2404-4\r\nVR898422,C105965,VA-EB-PL1,2024-07-14,vireo.in,1,2249,PL1-2405-2\r\nVR902414,C108511,VA-EB-PL1,2024-07-14,Flipkart,1,2499,PL1-2406-4\r\nVR903099,C107680,VA-EB-PL1,2024-07-14,vireo.in,1,2374,PL1-2404-3\r\nVR908197,C108471,VA-EB-PL1,2024-07-14,Flipkart,1,2499,PL1-2404-1\r\nVR881362,C106117,VA-SP-ORB,2024-07-15,Amazon,1,5099,ORB-2405-2\r\nVR888115,C104059,VA-EB-PL1,2024-07-15,vireo.in,1,2499,PL1-2406-2\r\nVR897451,C100883,VA-SW-NX1,2024-07-15,vireo.in,1,4999,NX1-2403-2\r\nVR899914,C106062,VA-SP-ORB,2024-07-15,Amazon,1,5099,ORB-2406-3\r\nVR885302,C100865,VA-EB-PL1,2024-07-16,vireo.in,1,2499,PL1-2404-3\r\nVR887540,C109143,VA-HP-ST2,2024-07-16,vireo.in,1,4749,ST2-2403-2\r\nVR899593,C103020,VA-SP-ORB,2024-07-16,vireo.in,1,5399,ORB-2406-2\r\nVR902221,C101197,VA-HP-ST2,2024-07-16,Amazon,1,4499,ST2-2405-1\r\nVR904688,C102949,VA-HP-ST2,2024-07-16,Amazon,1,4999,ST2-2404-4\r\nVR885635,C101469,VA-EB-PL1,2024-07-17,Flipkart,1,2124,PL1-2405-1\r\nVR889090,C101164,VA-NB-ARC,2024-07-17,vireo.in,1,1299,ARC-2405-4\r\nVR901780,C103924,VA-EB-PL1,2024-07-17,vireo.in,1,2499,PL1-2405-2\r\nVR883862,C101753,VA-SP-ORB,2024-07-18,vireo.in,1,5099,ORB-2406-2\r\nVR889239,C101192,VA-NB-ARC,2024-07-18,Amazon,1,1299,ARC-2406-4\r\nVR893804,C107820,VA-EB-PL1,2024-07-18,Flipkart,1,2124,PL1-2405-2\r\nVR904261,C104659,VA-EB-PL1,2024-07-18,vireo.in,1,2374,PL1-2406-2\r\nVR884957,C100115,VA-EB-PL1,2024-07-19,vireo.in,1,2499,PL1-2406-2\r\nVR888101,C102581,VA-SP-ORB,2024-07-19,vireo.in,1,5999,ORB-2404-3\r\nVR895233,C106969,VA-HP-ST2,2024-07-19,vireo.in,1,3999,ST2-2405-4\r\nVR898047,C105595,VA-NB-ARC,2024-07-19,Amazon,1,1169,ARC-2406-3\r\nVR899494,C109394,VA-HP-ST2,2024-07-19,Amazon,1,4999,ST2-2405-1\r\nVR906906,C101723,VA-EB-PL1,2024-07-19,Flipkart,1,1999,PL1-2405-3\r\nVR880178,C104018,VA-EB-PL1,2024-07-20,Flipkart,1,2374,PL1-2405-1\r\nVR891028,C108858,VA-EB-PL1,2024-07-20,vireo.in,1,1999,PL1-2406-2\r\nVR894255,C105837,VA-EB-PL1,2024-07-20,vireo.in,1,2249,PL1-2406-2\r\nVR894497,C101810,VA-SP-ORB,2024-07-20,Amazon,1,5099,ORB-2405-2\r\nVR896014,C104739,VA-EB-PL1,2024-07-20,vireo.in,2,4998,PL1-2405-4\r\nVR901178,C109222,VA-HP-ST2,2024-07-20,Flipkart,1,4749,ST2-2405-3\r\nVR885789,C106231,VA-EB-PL1,2024-07-21,Flipkart,1,2499,PL1-2404-4\r\nVR896344,C102950,VA-AC-CBL,2024-07-21,Amazon,1,319,CBL-2404-3\r\nVR901365,C108661,VA-EB-PL1,2024-07-21,Amazon,2,3998,PL1-2405-3\r\nVR903853,C103142,VA-NB-ARC,2024-07-21,vireo.in,1,1299,ARC-2405-2\r\nVR880126,C107749,VA-HP-ST2,2024-07-22,vireo.in,1,3999,ST2-2406-4\r\nVR884622,C103307,VA-HP-ST2,2024-07-22,Amazon,1,4499,ST2-2404-4\r\nVR886034,C100069,VA-NB-ARC,2024-07-22,vireo.in,1,1299,ARC-2404-3\r\nVR888673,C102196,VA-EB-PL1,2024-07-22,Amazon,1,1999,PL1-2406-4\r\nVR894898,C103491,VA-HP-ST2,2024-07-22,Amazon,1,4249,ST2-2406-3\r\nVR895799,C107212,VA-AC-CBL,2024-07-22,vireo.in,1,399,CBL-2406-1\r\nVR896330,C101532,VA-SP-ORB,2024-07-22,Flipkart,1,5999,ORB-2404-3\r\nVR900147,C108259,VA-NB-ARC,2024-07-22,Amazon,1,1104,ARC-2405-1\r\nVR900353,C106252,VA-SP-ORB,2024-07-22,Amazon,1,5999,ORB-2404-2\r\nVR906274,C100160,VA-SP-ORB,2024-07-22,Amazon,1,5399,ORB-2404-2\r\nVR883024,C100624,VA-EB-PL1,2024-07-23,vireo.in,1,1999,PL1-2406-1\r\nVR886337,C107429,VA-AC-CH65,2024-07-23,Flipkart,1,1499,CH65-2406-4\r\nVR901036,C107001,VA-EB-PL1,2024-07-23,Amazon,1,1999,PL1-2406-1\r\nVR903698,C104745,VA-SW-NX1,2024-07-23,Amazon,1,4999,NX1-2405-1\r\nVR906246,C109138,VA-EB-PL1,2024-07-23,vireo.in,1,2499,PL1-2407-1\r\nVR906821,C108084,VA-NB-ARC,2024-07-23,vireo.in,1,1234,ARC-2405-1\r\nVR880903,C101133,VA-EB-PL1,2024-07-24,vireo.in,1,2499,PL1-2406-2\r\nVR882628,C100939,VA-NB-ARC,2024-07-24,vireo.in,1,1299,ARC-2404-4\r\nVR886805,C103882,VA-EB-PL1,2024-07-24,vireo.in,1,2499,PL1-2406-2\r\nVR892910,C101961,VA-HP-ST2,2024-07-24,Flipkart,1,4999,ST2-2406-2\r\nVR895320,C108559,VA-AC-CBL,2024-07-24,Flipkart,1,379,CBL-2406-4\r\nVR905390,C104848,VA-EB-PL1,2024-07-24,vireo.in,1,2249,PL1-2404-1\r\nVR889712,C106786,VA-HP-ST2,2024-07-25,vireo.in,1,4749,ST2-2404-2\r\nVR891411,C105664,VA-SW-NX1,2024-07-25,Amazon,1,4999,NX1-2406-3\r\nVR892166,C102445,VA-EB-PL1,2024-07-25,vireo.in,1,2499,PL1-2406-3\r\nVR894967,C100527,VA-EB-PL1,2024-07-25,vireo.in,1,2374,PL1-2404-1\r\nVR904279,C103226,VA-HP-ST2,2024-07-25,vireo.in,1,4749,ST2-2406-3\r\nVR909823,C102528,VA-EB-PL1,2024-07-25,Flipkart,1,2374,PL1-2406-3\r\nVR882503,C105685,VA-EB-PL1,2024-07-26,Flipkart,1,2124,PL1-2406-2\r\nVR888671,C107231,VA-SP-ORB,2024-07-26,vireo.in,1,4799,ORB-2405-1\r\nVR894615,C108547,VA-AC-CH65,2024-07-26,Amazon,1,1424,CH65-2405-1\r\nVR901604,C101540,VA-EB-PL1,2024-07-26,Amazon,1,2499,PL1-2404-4\r\nVR904293,C106828,VA-NB-ARC,2024-07-26,Flipkart,1,1299,ARC-2405-3\r\nVR906204,C103257,VA-SW-NX1,2024-07-26,Amazon,2,8998,NX1-2406-3\r\nVR882899,C100412,VA-AC-CBL,2024-07-27,Flipkart,1,339,CBL-2407-3\r\nVR883965,C107701,VA-EB-PL1,2024-07-27,Flipkart,1,1999,PL1-2404-4\r\nVR892002,C108775,VA-EB-PL1,2024-07-27,vireo.in,1,2374,PL1-2404-2\r\nVR907700,C103180,VA-EB-PL1,2024-07-27,Amazon,1,2249,PL1-2405-4\r\nVR881438,C101470,VA-NB-ARC,2024-07-28,vireo.in,1,1104,ARC-2405-3\r\nVR883745,C107263,VA-AC-CBL,2024-07-28,vireo.in,1,399,CBL-2405-4\r\nVR884293,C105510,VA-HP-ST2,2024-07-28,vireo.in,2,9998,ST2-2406-4\r\nVR888686,C106840,VA-EB-PL1,2024-07-28,Amazon,1,2499,PL1-2405-1\r\nVR891453,C106253,VA-AC-CBL,2024-07-28,vireo.in,1,319,CBL-2404-2\r\nVR895542,C104335,VA-NB-ARC,2024-07-28,Amazon,1,1104,ARC-2406-3\r\nVR899454,C101549,VA-NB-ARC,2024-07-28,vireo.in,1,1299,ARC-2407-4\r\nVR880187,C107958,VA-AC-CBL,2024-07-29,vireo.in,1,399,CBL-2405-1\r\nVR882049,C106628,VA-NB-ARC,2024-07-29,Flipkart,1,1169,ARC-2404-2\r\nVR887467,C103405,VA-HP-ST2,2024-07-29,Amazon,1,4499,ST2-2405-1\r\nVR891421,C105292,VA-HP-ST2,2024-07-29,vireo.in,1,4999,ST2-2406-3\r\nVR900316,C103317,VA-EB-PL1,2024-07-29,vireo.in,1,1999,PL1-2405-3\r\nVR902901,C103739,VA-EB-PL1,2024-07-29,Amazon,1,2499,PL1-2405-4\r\nVR907469,C103696,VA-EB-PL1,2024-07-29,Amazon,1,2124,PL1-2406-4\r\nVR887128,C105030,VA-SW-NX1,2024-07-30,Amazon,1,4499,NX1-2405-4\r\nVR887698,C100163,VA-NB-ARC,2024-07-30,Flipkart,1,1234,ARC-2406-1\r\nVR889538,C100857,VA-EB-PL1,2024-07-30,vireo.in,1,2249,PL1-2404-3\r\nVR897967,C107007,VA-SW-NX1,2024-07-30,vireo.in,1,4999,NX1-2407-4\r\nVR906172,C102078,VA-EB-PL1,2024-07-30,vireo.in,1,1999,PL1-2404-3\r\nVR886771,C106132,VA-EB-PL1,2024-07-31,vireo.in,1,2499,PL1-2406-1\r\nVR890172,C105408,VA-EB-PL1,2024-07-31,Amazon,1,2499,PL1-2407-2\r\nVR894873,C105556,VA-SP-ORB,2024-07-31,Amazon,1,5399,ORB-2406-1\r\nVR896542,C105760,VA-EB-PL1,2024-07-31,vireo.in,1,2374,PL1-2406-3\r\nVR903067,C103680,VA-AC-CH65,2024-07-31,Amazon,1,1424,CH65-2407-3\r\nVR907947,C101511,VA-HP-ST2,2024-07-31,Amazon,2,9498,ST2-2404-2\r\nVR880570,C100019,VA-EB-PL1,2024-08-01,Amazon,1,2124,PL1-2407-4\r\nVR881957,C100053,VA-EB-PL1,2024-08-01,Amazon,2,4998,PL1-2405-1\r\nVR886694,C105684,VA-SP-ORB,2024-08-01,Amazon,1,5399,ORB-2407-2\r\nVR886976,C102395,VA-SW-FIT,2024-08-01,Flipkart,2,3998,FIT-2405-3\r\nVR887468,C101838,VA-NB-ARC,2024-08-01,vireo.in,1,1104,ARC-2405-4\r\nVR887914,C107651,VA-SP-ORB,2024-08-01,Flipkart,1,5399,ORB-2407-1\r\nVR894159,C108541,VA-EB-PL1,2024-08-01,Flipkart,1,2499,PL1-2405-3\r\nVR905662,C100406,VA-EB-PL1,2024-08-01,vireo.in,1,2249,PL1-2405-2\r\nVR906079,C108391,VA-AC-CH65,2024-08-01,vireo.in,1,1499,CH65-2405-2\r\nVR909068,C109221,VA-SP-ORB,2024-08-01,vireo.in,1,5399,ORB-2405-3\r\nVR882363,C104177,VA-SW-FIT,2024-08-02,vireo.in,1,1899,FIT-2405-1\r\nVR883844,C101241,VA-SW-FIT,2024-08-02,vireo.in,1,1999,FIT-2406-2\r\nVR884245,C103616,VA-SP-ORB,2024-08-02,vireo.in,1,5399,ORB-2406-2\r\nVR890357,C102334,VA-SP-ORB,2024-08-02,vireo.in,1,5999,ORB-2407-2\r\nVR892137,C105028,VA-AC-CBL,2024-08-02,vireo.in,1,359,CBL-2406-2\r\nVR897217,C101512,VA-EB-PL1,2024-08-02,Flipkart,1,2499,PL1-24

In [ ]:
print("Upload customers.csv")
files.upload()

Upload customers.csv

Saving customers.csv to customers (2).csv

{'customers (2).csv': b"customer_id,name,city,state,signup_date,care_plus\r\nC100000,Karan Mishra,Delhi,DL,2024-07-02,N\r\nC100001,Kavya Khan,Bhopal,MP,2024-08-22,Y\r\nC100002,Yash Bose,Kolkata,WB,2022-10-06,Y\r\nC100003,Sai Yadav,Nashik,MH,2023-07-26,Y\r\nC100004,Komal Joshi,Jaipur,RJ,2023-02-12,Y\r\nC100005,Daniel Reddy,Ranchi,JH,2022-11-23,N\r\nC100006,Nisha Saxena,Hyderabad,TS,2023-11-11,N\r\nC100007,Geeta Shah,Patna,BR,2024-06-15,N\r\nC100008,Ritika Mathew,Ranchi,JH,2024-08-31,N\r\nC100009,Pooja Bansal,Delhi,DL,2023-06-29,N\r\nC100010,Krishna Kumar,Bengaluru,KA,2024-10-02,N\r\nC100011,Rahul Shinde,Indore,MP,2023-05-08,Y\r\nC100012,Anjali Agarwal,Bhubaneswar,OR,2023-06-22,Y\r\nC100013,Anjali Mukherjee,Bhopal,MP,2024-12-07,Y\r\nC100014,Payal Banerjee,Vadodara,GJ,2022-08-29,N\r\nC100015,Ritika Kapoor,Guwahati,AS,2023-12-08,Y\r\nC100016,Sai Arora,Patna,BR,2023-07-16,N\r\nC100017,Saanvi Kaur,Pune,MH,2023-09-03,N\r\nC100018,Sai Khan,Guwahati,AS,2023-12-15,Y\r\nC100019,Daniel Siddiqui,Bhopal,MP,2022-09-28,N\r\nC100020,Gurpreet Patil,Guwahati,AS,2024-12-10,N\r\nC100021,Sukhwinder Siddiqui,Ahmedabad,GJ,2023-09-29,Y\r\nC100022,Aadhya Sheikh,Bhopal,MP,2024-09-23,N\r\nC100023,Rahul Pandey,Bhopal,MP,2024-05-26,N\r\nC100024,Ankit Mathew,Bengaluru,KA,2024-03-06,N\r\nC100025,Imran Shinde,Noida,UP,2023-04-08,Y\r\nC100026,Yash Jain,Visakhapatnam,AP,2023-06-25,N\r\nC100027,Ishaan Reddy,Indore,MP,2023-03-27,N\r\nC100028,Rajat Bose,Kolkata,WB,2023-01-10,N\r\nC100029,Sameer Menon,Jaipur,RJ,2024-03-17,N\r\nC100030,Diya Mishra,Indore,MP,2024-11-25,Y\r\nC100031,Jaspreet Naidu,Bengaluru,KA,2023-02-24,N\r\nC100032,Tenzin Sharma,Vadodara,GJ,2023-01-08,N\r\nC100033,Shreya Rathore,Raipur,CG,2022-11-19,Y\r\nC100034,Farah Yadav,Lucknow,UP,2022-12-18,Y\r\nC100035,Varun Varghese,Chandigarh,CH,2022-10-22,N\r\nC100036,Deepak Banerjee,Kochi,KL,2024-10-11,N\r\nC100037,Siddharth Mukherjee,Coimbatore,TN,2024-01-30,N\r\nC100038,Om Fernandes,Delhi,DL,2023-01-25,N\r\nC100039,Ankit Reddy,Guwahati,AS,2024-10-11,N\r\nC100040,Payal Patel,Patna,BR,2024-03-21,N\r\nC100041,Om Ghosh,Dehradun,UK,2023-07-15,N\r\nC100042,Joseph Pawar,Ahmedabad,GJ,2023-11-19,N\r\nC100043,Kabir Pillai,Ahmedabad,GJ,2023-01-12,N\r\nC100044,Aditya Shinde,Chandigarh,CH,2023-09-21,Y\r\nC100045,Meera Chopra,Nagpur,MH,2024-12-30,N\r\nC100046,Megha Qureshi,Raipur,CG,2024-02-11,N\r\nC100047,Nikhil Rao,Patna,BR,2023-07-23,N\r\nC100048,Om Sandhu,Jaipur,RJ,2023-03-19,N\r\nC100049,Ankit Menon,Mumbai,MH,2024-08-09,N\r\nC100050,Varun Pereira,Ahmedabad,GJ,2024-07-21,N\r\nC100051,Diya Nair,Mumbai,MH,2024-04-15,N\r\nC100052,Rohit Rathore,Bhopal,MP,2022-11-26,Y\r\nC100053,Payal Pillai,Hyderabad,TS,2024-11-09,Y\r\nC100054,Bhavna Qureshi,Bhubaneswar,OR,2023-04-20,Y\r\nC100055,Kunal Patil,Delhi,DL,2022-08-06,N\r\nC100056,Vikram Bhatt,Surat,GJ,2024-03-02,N\r\nC100057,Yash Naidu,Visakhapatnam,AP,2023-08-16,N\r\nC100058,Gurpreet Gaikwad,Chennai,TN,2023-02-05,N\r\nC100059,Joseph Jain,Lucknow,UP,2024-03-15,Y\r\nC100060,Kabir Menon,Chandigarh,CH,2022-09-20,N\r\nC100061,Zaid Ghosh,Kolkata,WB,2023-06-07,Y\r\nC100062,Bhavna Mathew,Indore,MP,2023-02-05,N\r\nC100063,Aadhya Iyer,Noida,UP,2023-10-21,N\r\nC100064,Pooja Reddy,Pune,MH,2023-05-15,N\r\nC100065,Tanvi Kaur,Mumbai,MH,2023-12-25,N\r\nC100066,Om Joshi,Delhi,DL,2024-01-22,N\r\nC100067,Dev Pereira,Hyderabad,TS,2024-01-26,N\r\nC100068,Nikhil Das,Dehradun,UK,2024-01-02,N\r\nC100069,Ayaan Sethi,Indore,MP,2024-07-11,Y\r\nC100070,Shreya Gill,Delhi,DL,2024-02-22,Y\r\nC100071,Vivaan Bose,Dehradun,UK,2022-11-07,N\r\nC100072,Geeta Mathew,Raipur,CG,2024-02-12,Y\r\nC100073,Abhishek Chatterjee,Bhopal,MP,2023-08-16,Y\r\nC100074,Megha Varghese,Chennai,TN,2024-04-09,N\r\nC100075,Gurpreet Sen,Coimbatore,TN,2023-05-01,N\r\nC100076,Vikram Yadav,Nagpur,MH,2022-08-23,N\r\nC100077,Suresh Joshi,Lucknow,UP,2024-07-23,N\r\nC100078,Dev Chauhan,Chennai,TN,2024-09-13,Y\r\nC100079,Divya Das,Bhubaneswar,OR,2023-02-24,N\r\nC100080,Gurpreet Rao,Nashik,MH,2023-08-08,N\r\nC100081,Nisha Singh,Bhopal,MP,2023-11-19,Y\r\nC100082,Tarun Goyal,Coimbatore,TN,2023-11-04,Y\r\nC100083,Pranav Sheikh,Bhopal,MP,2023-11-24,N\r\nC100084,Megha Nair,Mumbai,MH,2023-01-02,N\r\nC100085,Aadhya Jadhav,Noida,UP,2022-11-30,N\r\nC100086,Simran Siddiqui,Bengaluru,KA,2023-09-30,N\r\nC100087,Zoya Sharma,Patna,BR,2024-02-01,Y\r\nC100088,Arjun Patil,Delhi,DL,2024-07-10,N\r\nC100089,Nisha Pereira,Visakhapatnam,AP,2022-12-10,N\r\nC100090,Nisha Bansal,Pune,MH,2024-07-23,Y\r\nC100091,Nikhil Singh,Bhubaneswar,OR,2023-10-25,Y\r\nC100092,Krishna Agarwal,Mysuru,KA,2022-10-29,Y\r\nC100093,Daniel Gaikwad,Visakhapatnam,AP,2023-01-05,N\r\nC100094,Aadhya Sen,Nagpur,MH,2024-04-26,N\r\nC100095,Harsh Srivastava,Noida,UP,2024-08-20,N\r\nC100096,Harsh Tiwari,Kochi,KL,2024-06-22,N\r\nC100097,Pooja Naidu,Kolkata,WB,2023-10-28,N\r\nC100098,Nikhil Khan,Bengaluru,KA,2023-06-28,N\r\nC100099,Simran Saxena,Bhopal,MP,2024-01-17,N\r\nC100100,Vihaan Siddiqui,Visakhapatnam,AP,2023-10-16,N\r\nC100101,Daniel Desai,Delhi,DL,2023-01-20,Y\r\nC100102,Simran Bhatt,Chandigarh,CH,2024-12-21,N\r\nC100103,Sukhwinder Bhatia,Ranchi,JH,2022-12-07,N\r\nC100104,Ramesh Kaur,Patna,BR,2023-12-20,N\r\nC100105,Sameer Verma,Patna,BR,2023-04-15,N\r\nC100106,Vikram Kaur,Bhopal,MP,2024-08-03,N\r\nC100107,Sameer Pandey,Nashik,MH,2022-09-03,Y\r\nC100108,Tarun Rathore,Vadodara,GJ,2022-08-19,N\r\nC100109,Gurpreet Pandey,Patna,BR,2024-03-14,N\r\nC100110,Daniel Saxena,Mumbai,MH,2024-08-11,Y\r\nC100111,Rohit Sharma,Mysuru,KA,2022-10-21,Y\r\nC100112,Diya Chatterjee,Hyderabad,TS,2023-10-25,N\r\nC100113,Karan Mittal,Bhubaneswar,OR,2024-03-06,N\r\nC100114,Yash D'Souza,Guwahati,AS,2023-05-30,N\r\nC100115,Amit Kaur,Bhubaneswar,OR,2023-08-24,N\r\nC100116,Vihaan Patil,Bengaluru,KA,2022-09-11,N\r\nC100117,Suresh Arora,Mysuru,KA,2022-12-02,Y\r\nC100118,Karan Trivedi,Bhopal,MP,2023-04-22,N\r\nC100119,Kabir Mathew,Hyderabad,TS,2024-08-30,N\r\nC100120,Arjun Chopra,Chennai,TN,2022-09-12,N\r\nC100121,Sameer Tiwari,Ranchi,JH,2022-12-13,N\r\nC100122,Priya Dutta,Chandigarh,CH,2024-07-08,N\r\nC100123,Rohan Reddy,Nagpur,MH,2024-11-19,N\r\nC100124,Farah Dutta,Coimbatore,TN,2023-02-07,N\r\nC100125,Nisha Khan,Kochi,KL,2023-03-09,Y\r\nC100126,Joseph Sandhu,Surat,GJ,2022-10-03,Y\r\nC100127,Simran Jadhav,Nagpur,MH,2023-02-02,Y\r\nC100128,Nisha Joshi,Hyderabad,TS,2024-12-02,Y\r\nC100129,Abhishek Ansari,Dehradun,UK,2023-02-27,N\r\nC100130,Swati Sen,Guwahati,AS,2024-12-05,N\r\nC100131,Harpreet Verma,Raipur,CG,2022-12-01,N\r\nC100132,Manish Mukherjee,Chennai,TN,2024-06-18,N\r\nC100133,Jaspreet Tiwari,Delhi,DL,2023-07-06,Y\r\nC100134,Abhishek Roy,Mysuru,KA,2022-10-25,N\r\nC100135,Tenzin Iyer,Kochi,KL,2023-10-04,N\r\nC100136,Ritika Sharma,Noida,UP,2024-01-18,Y\r\nC100137,Varun Naidu,Jaipur,RJ,2024-08-13,Y\r\nC100138,Manish George,Hyderabad,TS,2023-07-10,N\r\nC100139,Payal Mathew,Indore,MP,2024-04-23,N\r\nC100140,Abhishek Gaikwad,Dehradun,UK,2024-12-24,N\r\nC100141,Sukhwinder Rathore,Gurugram,HR,2022-12-21,N\r\nC100142,Nikhil Arora,Guwahati,AS,2023-05-22,N\r\nC100143,Zoya Sandhu,Hyderabad,TS,2024-09-05,N\r\nC100144,Ankit Sharma,Guwahati,AS,2023-08-02,N\r\nC100145,Swati Das,Ranchi,JH,2024-07-11,N\r\nC100146,Harpreet Ansari,Chennai,TN,2024-02-19,Y\r\nC100147,Ayaan Khan,Ahmedabad,GJ,2024-05-18,N\r\nC100148,Shreya Khan,Indore,MP,2022-10-19,N\r\nC100149,Ramesh Bose,Kochi,KL,2024-06-14,N\r\nC100150,Sneha Fernandes,Nagpur,MH,2024-05-13,N\r\nC100151,Kavya Sethi,Chennai,TN,2023-02-06,Y\r\nC100152,Lakshmi Mehta,Nashik,MH,2023-01-07,N\r\nC100153,Farah Sen,Chennai,TN,2023-11-13,N\r\nC100154,Zoya Fernandes,Pune,MH,2023-12-03,Y\r\nC100155,Anjali Menon,Bhubaneswar,OR,2024-07-18,N\r\nC100156,Deepak Kumar,Ahmedabad,GJ,2022-11-28,N\r\nC100157,Nikhil Kulkarni,Kolkata,WB,2024-03-16,Y\r\nC100158,Om Bhatt,Guwahati,AS,2023-06-18,N\r\nC100159,Divya Reddy,Indore,MP,2023-11-17,N\r\nC100160,Farah Gupta,Thiruvananthapuram,KL,2024-01-29,Y\r\nC100161,Kabir Iyer,Pune,MH,2024-02-26,Y\r\nC100162,Rahul Shah,Bhopal,MP,2023-04-23,Y\r\nC100163,Neha Saxena,Mumbai,MH,2024-10-14,N\r\nC100164,Manpreet Singh,Nagpur,MH,2023-10-11,Y\r\nC100165,Anjali Sheikh,Nashik,MH,2022-09-27,N\r\nC100166,Isha Kulkarni,Pune,MH,2023-09-09,N\r\nC100167,Ananya Desai,Dehradun,UK,2024-09-10,N\r\nC100168,Sunita Goyal,Chandigarh,CH,2022-12-13,N\r\nC100169,Siddharth Ghosh,Vadodara,GJ,2023-05-18,N\r\nC100170,Vivaan Patel,Raipur,CG,2023-01-09,Y\r\nC100171,Imran Kapoor,Bengaluru,KA,2024-01-09,N\r\nC100172,Sukhwinder Dhillon,Nashik,MH,2022-07-29,N\r\nC100173,Krishna Ansari,Kochi,KL,2024-03-13,N\r\nC100174,Zoya Deshpande,Pune,MH,2024-01-06,Y\r\nC100175,Rohan Srivastava,Nashik,MH,2023-11-01,Y\r\nC100176,Priya Gupta,Kolkata,WB,2022-12-05,N\r\nC100177,Nikhil Menon,Patna,BR,2024-07-10,N\r\nC100178,Nikhil Iyer,Bhopal,MP,2024-06-05,N\r\nC100179,Nikhil Jain,Gurugram,HR,2024-08-26,N\r\nC100180,Varun Malhotra,Dehradun,UK,2024-06-30,N\r\nC100181,Nisha Siddiqui,Bengaluru,KA,2022-12-29,Y\r\nC100182,Harsh Joshi,Chennai,TN,2024-12-03,N\r\nC100183,Zaid Ansari,Patna,BR,2023-03-18,N\r\nC100184,Arjun Dhillon,Bengaluru,KA,2024-08-04,N\r\nC100185,Daniel Srivastava,Thiruvananthapuram,KL,2023-08-16,N\r\nC100186,Simran Kapoor,Lucknow,UP,2023-06-12,Y\r\nC100187,Harpreet Mehta,Mysuru,KA,2022-12-25,Y\r\nC100188,Imran Shah,Chandigarh,CH,2024-10-12,N\r\nC100189,Mohammed Banerjee,Mumbai,MH,2023-01-22,N\r\nC100190,Riya Ansari,Patna,BR,2024-08-09,N\r\nC100191,Rohan Sheikh,Chennai,TN,2023-11-15,N\r\nC100192,Payal Nair,Chennai,TN,2023-03-20,N\r\nC100193,Ishaan Rao,Thiruvananthapuram,KL,2023-09-10,N\r\nC100194,Pooja Dutta,Thiruvananthapuram,KL,2024-07-31,N\r\nC100195,Deepak Sandhu,Chennai,TN,2023-02-27,N\r\nC100196,Pooja Das,Ahmedabad,GJ,2023-11-16,N\r\nC100197,Manpreet Chauhan,Gurugram,HR,2023-01-23,N\r\nC100198,Varun Sheikh,Mysuru,KA,2024-05-20,Y\r\nC100199,Yash Siddiqui,Pune,MH,2022-07-26,N\r\nC100200,Abhishek Ansari,Coimbatore,TN,2023-11-28,N\r\nC100201,Sukhwinder Mathew,Thiruvananthapuram,KL,2024-07-27,N\r\nC100202,Aishwarya Goyal,Coimbatore,TN,2023-07-19,N\r\nC100203,Faisal Yadav,Indore,MP,2022-07-18,Y\r\nC100204,Om Rao,Gurugram,HR,2022-07-16,N\r\nC100205,Ramesh Shah,Bhopal,MP,2024-12-05,N\r\nC100206,Kabir Varghese,Coimbatore,TN,2022-09-23,Y\r\nC100207,Dev Patel,Noida,UP,2024-09-24,N\r\nC100208,Isha Jain,Delhi,DL,2024-01-05,N\r\nC100209,Geeta Arora,Gurugram,HR,2024-02-29,Y\r\nC100210,Harsh Sharma,Chennai,TN,2023-03-06,N\r\nC100211,Meera Chopra,Delhi,DL,2023-10-08,Y\r\nC100212,Deepak Mittal,Delhi,DL,2024-09-17,N\r\nC100213,Manpreet Srivastava,Hyderabad,TS,2024-07-16,Y\r\nC100214,Diya Sandhu,Mysuru,KA,2022-11-12,N\r\nC100215,Vikram Ansari,Nashik,MH,2023-08-09,N\r\nC100216,Ayaan Naidu,Chandigarh,CH,2023-08-16,Y\r\nC100217,Suresh Malhotra,Kochi,KL,2023-01-16,N\r\nC100218,Priya Joshi,Ahmedabad,GJ,2024-03-24,N\r\nC100219,Varun Deshpande,Jaipur,RJ,2022-11-20,N\r\nC100220,Aarav Fernandes,Noida,UP,2023-10-04,N\r\nC100221,Sai Iyer,Visakhapatnam,AP,2024-05-21,N\r\nC100222,Vivaan Chauhan,Bengaluru,KA,2022-10-08,N\r\nC100223,Isha Mehta,Surat,GJ,2024-04-11,N\r\nC100224,Reyansh Singh,Noida,UP,2024-10-12,Y\r\nC100225,Megha Dutta,Ahmedabad,GJ,2024-07-15,N\r\nC100226,Isha Sheikh,Bengaluru,KA,2022-09-23,Y\r\nC100227,Nisha Joshi,Chandigarh,CH,2023-07-01,Y\r\nC100228,Varun Banerjee,Jaipur,RJ,2022-08-22,Y\r\nC100229,Nikhil Sandhu,Gurugram,HR,2022-12-23,Y\r\nC100230,Amit Malhotra,Bengaluru,KA,2024-03-14,Y\r\nC100231,Pranav Saxena,Surat,GJ,2022-09-16,Y\r\nC100232,Manpreet Dutta,Kolkata,WB,2023-06-29,N\r\nC100233,Pooja Pandey,Bengaluru,KA,2023-02-04,Y\r\nC100234,Faisal Nair,Ahmedabad,GJ,2023-04-04,Y\r\nC100235,Manish Bose,Pune,MH,2024-02-16,Y\r\nC100236,Payal Reddy,Chennai,TN,2023-02-01,Y\r\nC100237,Reyansh Desai,Surat,GJ,2024-11-19,N\r\nC100238,Zaid Pandey,Ahmedabad,GJ,2023-06-13,N\r\nC100239,Tanvi Siddiqui,Nashik,MH,2024-03-21,Y\r\nC100240,Mohammed Fernandes,Surat,GJ,2024-12-07,N\r\nC100241,Faisal Sandhu,Vadodara,GJ,2023-05-08,N\r\nC100242,Nisha Reddy,Bengaluru,KA,2024-03-27,N\r\nC100243,Abhishek Pereira,Ranchi,JH,2023-08-07,N\r\nC100244,Daniel Ansari,Bengaluru,KA,2024-10-11,Y\r\nC100245,Sneha Banerjee,Gurugram,HR,2023-09-08,N\r\nC100246,Aditya Mishra,Nagpur,MH,2023-01-03,Y\r\nC100247,Manish Desai,Chennai,TN,2024-11-01,N\r\nC100248,Deepak Shinde,Visakhapatnam,AP,2023-03-18,Y\r\nC100249,Lakshmi Khan,Hyderabad,TS,2024-04-29,Y\r\nC100250,Vihaan Srivastava,Pune,MH,2022-12-08,N\r\nC100251,Priya Dhillon,Visakhapatnam,AP,2023-04-26,Y\r\nC100252,Megha Mathew,Ahmedabad,GJ,2023-07-13,N\r\nC100253,Diya Varghese,Mumbai,MH,2024-03-10,N\r\nC100254,Ankit Fernandes,Bhubaneswar,OR,2023-05-04,N\r\nC100255,Zoya Qureshi,Raipur,CG,2024-01-20,N\r\nC100256,Tanvi Deshpande,Patna,BR,2022-08-23,N\r\nC100257,Gurpreet Ghosh,Bhubaneswar,OR,2022-11-21,N\r\nC100258,Divya Siddiqui,Pune,MH,2023-11-11,N\r\nC100259,Krishna Kaur,Kolkata,WB,2023-10-21,N\r\nC100260,Rajat Gill,Delhi,DL,2024-08-08,Y\r\nC100261,Tanvi Arora,Indore,MP,2022-11-21,Y\r\nC100262,Reyansh Sethi,Raipur,CG,2023-11-10,N\r\nC100263,Vikram Pillai,Guwahati,AS,2022-12-27,Y\r\nC100264,Nisha Mittal,Vadodara,GJ,2024-09-15,N\r\nC100265,Varun Srivastava,Ahmedabad,GJ,2022-11-20,N\r\nC100266,Abhishek Reddy,Surat,GJ,2023-05-09,Y\r\nC100267,Geeta Jadhav,Dehradun,UK,2023-03-12,N\r\nC100268,Rahul Chatterjee,Kochi,KL,2022-10-07,N\r\nC100269,Payal Banerjee,Nagpur,MH,2024-11-18,N\r\nC100270,Rohan Jain,Nashik,MH,2024-10-16,N\r\nC100271,Joseph Agarwal,Guwahati,AS,2023-10-08,Y\r\nC100272,Arjun Naidu,Thiruvananthapuram,KL,2023-08-09,N\r\nC100273,Faisal Khanna,Bengaluru,KA,2024-04-24,Y\r\nC100274,Manish Shah,Delhi,DL,2023-02-01,N\r\nC100275,Ananya Khan,Dehradun,UK,2023-08-17,N\r\nC100276,Priya Jain,Mysuru,KA,2024-07-15,Y\r\nC100277,Ayaan Shinde,Lucknow,UP,2023-06-30,N\r\nC100278,Diya Gill,Nagpur,MH,2023-12-05,N\r\nC100279,Farah Jadhav,Bengaluru,KA,2022-11-21,N\r\nC100280,Daniel Tiwari,Ranchi,JH,2024-11-13,Y\r\nC100281,Simran Bhatia,Mysuru,KA,2024-02-23,Y\r\nC100282,Kunal Jain,Chandigarh,CH,2024-06-19,Y\r\nC100283,Lakshmi Rao,Nashik,MH,2024-12-23,Y\r\nC100284,Vikram Chauhan,Pune,MH,2024-09-25,Y\r\nC100285,Komal Chatterjee,Kochi,KL,2022-08-18,N\r\nC100286,Faisal Chopra,Bhubaneswar,OR,2022-09-30,Y\r\nC100287,Sneha Reddy,Mumbai,MH,2024-05-12,Y\r\nC100288,Geeta Khanna,Chandigarh,CH,2023-06-24,N\r\nC100289,Diya Joshi,Nashik,MH,2023-11-25,Y\r\nC100290,Diya Jadhav,Jaipur,RJ,2023-05-09,N\r\nC100291,Steven Singh,Noida,UP,2022-08-12,N\r\nC100292,Kunal Varghese,Jaipur,RJ,2024-01-18,N\r\nC100293,Vihaan Chauhan,Coimbatore,TN,2022-12-06,N\r\nC100294,Krishna Sethi,Bhopal,MP,2024-08-15,Y\r\nC100295,Aadhya Pandey,Kochi,KL,2024-12-19,N\r\nC100296,Siddharth Reddy,Hyderabad,TS,2024-10-28,N\r\nC100297,Aadhya Rathore,Bhubaneswar,OR,2024-12-23,Y\r\nC100298,Varun Malhotra,Hyderabad,TS,2023-07-22,Y\r\nC100299,Divya Chopra,Thiruvananthapuram,KL,2024-12-29,Y\r\nC100300,Ishaan Roy,Jaipur,RJ,2022-08-19,N\r\nC100301,Nikhil Mukherjee,Guwahati,AS,2024-11-27,N\r\nC100302,Aditya Verma,Chennai,TN,2023-06-25,N\r\nC100303,Pranav Sheikh,Pune,MH,2024-09-29,Y\r\nC100304,Zoya Rathore,Mysuru,KA,2024-09-25,N\r\nC100305,Zoya Patel,Nagpur,MH,2022-12-03,N\r\nC100306,Mohammed Jain,Kolkata,WB,2024-04-06,N\r\nC100307,Meera Mishra,Raipur,CG,2024-08-19,N\r\nC100308,Sunita Goyal,Ahmedabad,GJ,2023-06-07,N\r\nC100309,Aditya Shinde,Noida,UP,2023-02-10,Y\r\nC100310,Daniel Kumar,Bhubaneswar,OR,2024-04-03,N\r\nC100311,Megha Deshpande,Lucknow,UP,2023-10-27,N\r\nC100312,Aishwarya Iyer,Delhi,DL,2024-09-20,Y\r\nC100313,Ritika Pawar,Kolkata,WB,2023-11-18,Y\r\nC100314,Kabir Jain,Mumbai,MH,2022-08-05,Y\r\nC100315,Priya Goyal,Pune,MH,2022-10-10,N\r\nC100316,Simran Khan,Nagpur,MH,2023-06-12,Y\r\nC100317,Ananya Tiwari,Bengaluru,KA,2023-12-11,N\r\nC100318,Priya Dutta,Raipur,CG,2022-08-20,N\r\nC100319,Ishaan Kulkarni,Nashik,MH,2023-08-15,Y\r\nC100320,Megha Gill,Patna,BR,2023-01-03,N\r\nC100321,Reyansh Mukherjee,Lucknow,UP,2022-09-29,N\r\nC100322,Jaspreet Singh,Bhopal,MP,2023-10-24,N\r\nC100323,Arjun Shah,Mumbai,MH,2024-02-03,N\r\nC100324,Pooja Pillai,Vadodara,GJ,2024-12-13,N\r\nC100325,Arjun Bose,Guwahati,AS,2022-09-06,N\r\nC100326,Reyansh Goyal,Mumbai,MH,2022-08-06,Y\r\nC100327,Ramesh Menon,Nashik,MH,2022-09-12,N\r\nC100328,Abhishek Chopra,Patna,BR,2024-04-28,N\r\nC100329,Jaspreet Jain,Indore,MP,2023-01-07,N\r\nC100330,Ramesh Mishra,Dehradun,UK,2023-11-16,Y\r\nC100331,Pranav Chatterjee,Patna,BR,2024-07-22,Y\r\nC100332,Saanvi Sharma,Indore,MP,2022-12-14,N\r\nC100333,Bhavna Gill,Noida,UP,2023-03-07,N\r\nC100334,Sneha Pillai,Mysuru,KA,2022-09-14,N\r\nC100335,Dev Patel,Patna,BR,2022-10-13,N\r\nC100336,Dev Gill,Pune,MH,2022-09-01,Y\r\nC100337,Priya Sandhu,Indore,MP,2024-07-14,Y\r\nC100338,Thomas Trivedi,Delhi,DL,2023-08-15,N\r\nC100339,Megha Jain,Gurugram,HR,2022-12-25,N\r\nC100340,Vikram George,Noida,UP,2024-05-08,Y\r\nC100341,Daniel Qureshi,Kolkata,WB,2023-05-09,N\r\nC100342,Pooja Chopra,Thiruvananthapuram,KL,2024-08-07,N\r\nC100343,Aadhya Patil,Ahmedabad,GJ,2024-09-10,N\r\nC100344,Vihaan Deshpande,Hyderabad,TS,2023-01-08,Y\r\nC100345,Isha Rao,Raipur,CG,2024-01-11,N\r\nC100346,Diya Pandey,Raipur,CG,2024-04-19,Y\r\nC100347,Nisha Goyal,Bhopal,MP,2024-05-27,N\r\nC100348,Manish Roy,Nagpur,MH,2024-11-17,Y\r\nC100349,Tarun Pawar,Jaipur,RJ,2023-12-11,N\r\nC100350,Arjun Gill,Vadodara,GJ,2022-12-05,N\r\nC100351,Tarun Khanna,Bhubaneswar,OR,2024-12-18,N\r\nC100352,Simran Das,Chennai,TN,2023-11-30,N\r\nC100353,Bhavna Gupta,Mysuru,KA,2023-11-20,N\r\nC100354,Sukhwinder Pawar,Bhubaneswar,OR,2024-11-06,Y\r\nC100355,Diya Shinde,Noida,UP,2022-07-22,N\r\nC100356,Kavya Chatterjee,Bengaluru,KA,2022-10-18,N\r\nC100357,Vikram Singh,Pune,MH,2022-10-12,N\r\nC100358,Harpreet Pawar,Coimbatore,TN,2023-08-10,N\r\nC100359,Gurpreet Gaikwad,Noida,UP,2023-01-03,Y\r\nC100360,Sameer Saxena,Guwahati,AS,2024-03-06,N\r\nC100361,Reyansh Shah,Indore,MP,2024-12-29,Y\r\nC100362,Isha Bhatia,Gurugram,HR,2023-06-15,Y\r\nC100363,Sameer Srivastava,Raipur,CG,2024-01-08,N\r\nC100364,Daniel Menon,Indore,MP,2023-07-20,Y\r\nC100365,Riya Shinde,Patna,BR,2022-07-21,N\r\nC100366,Harsh Sen,Kochi,KL,2024-08-27,N\r\nC100367,Vikram Ghosh,Mumbai,MH,2022-09-13,N\r\nC100368,Krishna Rao,Jaipur,RJ,2022-12-21,N\r\nC100369,Pooja Reddy,Bhopal,MP,2024-12-29,N\r\nC100370,Yash Sandhu,Ranchi,JH,2022-07-31,Y\r\nC100371,Priya Jadhav,Ranchi,JH,2022-10-27,N\r\nC100372,Mohammed Mathew,Patna,BR,2024-10-31,Y\r\nC100373,Lakshmi Khanna,Ahmedabad,GJ,2022-11-04,N\r\nC100374,Joseph Nair,Ahmedabad,GJ,2023-07-26,N\r\nC100375,Meera Varghese,Surat,GJ,2024-12-13,N\r\nC100376,Sukhwinder Gaikwad,Ahmedabad,GJ,2024-01-07,N\r\nC100377,Yash Desai,Gurugram,HR,2023-10-08,Y\r\nC100378,Ayaan Pawar,Coimbatore,TN,2022-12-19,N\r\nC100379,Kabir Pillai,Kochi,KL,2023-04-14,N\r\nC100380,Faisal Fernandes,Ahmedabad,GJ,2022-12-07,N\r\nC100381,Aditya Trivedi,Kochi,KL,2024-01-30,Y\r\nC100382,Zoya Saxena,Thiruvananthapuram,KL,2022-07-29,N\r\nC100383,Ishaan Bhatt,Raipur,CG,2023-06-04,Y\r\nC100384,Ananya Shinde,Patna,BR,2022-11-01,N\r\nC100385,Megha Fernandes,Ranchi,JH,2024-06-30,Y\r\nC100386,Arjun Arora,Thiruvananthapuram,KL,2022-09-30,Y\r\nC100387,Nikhil Banerjee,Kolkata,WB,2023-05-30,Y\r\nC100388,Farah Chopra,Patna,BR,2022-07-18,Y\r\nC100389,Manish Gaikwad,Gurugram,HR,2022-12-25,Y\r\nC100390,Simran Sandhu,Thiruvananthapuram,KL,2023-07-16,Y\r\nC100391,Abhishek Kapoor,Thiruvananthapuram,KL,2023-11-19,Y\r\nC100392,Sukhwinder Joshi,Chennai,TN,2024-05-02,N\r\nC100393,Farah Sandhu,Gurugram,HR,2022-07-18,Y\r\nC100394,Suresh Fernandes,Mumbai,MH,2023-04-17,Y\r\nC100395,Shreya Sen,Nashik,MH,2024-07-21,Y\r\nC100396,Zaid Yadav,Guwahati,AS,2024-09-27,N\r\nC100397,Diya Bhatia,Nashik,MH,2024-06-27,Y\r\nC100398,Vivaan Menon,Patna,BR,2024-08-05,N\r\nC100399,Thomas Arora,Nashik,MH,2024-05-14,Y\r\nC100400,Yash Gupta,Gurugram,HR,2022-10-23,Y\r\nC100401,Megha Nair,Kochi,KL,2022-12-06,N\r\nC100402,Komal Pillai,Ranchi,JH,2024-05-02,N\r\nC100403,Megha Singh,Indore,MP,2024-03-02,N\r\nC100404,Vihaan Qureshi,Patna,BR,2023-03-11,N\r\nC100405,Diya Chopra,Thiruvananthapuram,KL,2024-11-28,N\r\nC100406,Saanvi Ghosh,Lucknow,UP,2023-06-30,Y\r\nC100407,Ankit Chauhan,Ahmedabad,GJ,2024-12-31,N\r\nC100408,Mohammed Saxena,Coimbatore,TN,2022-11

In [ ]:
print("Upload products.csv")
files.upload()

Upload products.csv

Saving products.csv to products (2).csv

{'products (2).csv': b'sku,product_name,family,launch_date,unit_cost_inr,retail_price_inr,warranty_months\r\nVA-EB-PL2,Pulse 2 True Wireless Earbuds,earbuds,2025-07-15,1480,3499,12\r\nVA-EB-PL1,Pulse True Wireless Earbuds,earbuds,2024-03-01,1120,2499,12\r\nVA-EB-AIR,AirLite Earbuds,earbuds,2024-09-10,760,1799,12\r\nVA-HP-ST3,Strata 3 Over-Ear Headphones,headphones,2024-11-20,2650,6999,12\r\nVA-HP-ST2,Strata 2 Over-Ear Headphones,headphones,2023-10-01,2100,4999,12\r\nVA-SP-ORB,Orbit Smart Speaker,speaker,2024-06-05,2300,5999,12\r\nVA-SP-MINI,Orbit Mini Speaker,speaker,2025-02-14,980,2499,12\r\nVA-SW-NX2,Nexa 2 Smartwatch,watch,2025-01-20,2450,6499,12\r\nVA-SW-NX1,Nexa Smartwatch,watch,2023-12-05,1900,4999,12\r\nVA-SW-FIT,Nexa Fit Band,watch,2024-08-01,850,1999,12\r\nVA-NB-ARC,Arc Neckband,earbuds,2024-05-12,540,1299,12\r\nVA-AC-CH65,65W GaN Charger,accessory,2024-04-01,610,1499,6\r\nVA-AC-CBL,USB-C Braided Cable,accessory,2024-04-01,90,399,6\r\nVA-AC-CASE,Pulse Charging Case (spare),accessory,2025-08-01,620,1299,6\r\n'}

In [ ]:
# Cell 4: Load datasets

tickets = pd.read_csv("tickets.csv")
agents = pd.read_csv("agents.csv")
orders = pd.read_csv("orders.csv")
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")

print("Datasets loaded successfully.\n")

print(f"tickets   : {tickets.shape[0]:,} rows × {tickets.shape[1]} columns")
print(f"agents    : {agents.shape[0]:,} rows × {agents.shape[1]} columns")
print(f"orders    : {orders.shape[0]:,} rows × {orders.shape[1]} columns")
print(f"customers : {customers.shape[0]:,} rows × {customers.shape[1]} columns")
print(f"products  : {products.shape[0]:,} rows × {products.shape[1]} columns")

✅ Datasets loaded successfully.

tickets   : 11,816 rows × 21 columns
agents    : 0 rows × 1 columns
orders    : 0 rows × 1 columns
customers : 0 rows × 1 columns
products  : 0 rows × 1 columns

In [ ]:
# Cell 5: Validate required ticket columns

required_ticket_columns = {
    "ticket_id",
    "created_at",
    "first_response_at",
    "resolved_at",
    "status",
    "channel",
    "customer_id",
    "order_id",
    "product_sku",
    "category",
    "priority",
    "assigned_team",
    "agent_id",
    "transfers",
    "csat_score",
    "refund_amount_inr",
    "refund_reason_code",
    "replacement_issued",
    "customer_message",
    "agent_notes",
    "source_system"
}

actual_ticket_columns = set(tickets.columns)

missing_ticket_columns = required_ticket_columns - actual_ticket_columns

if missing_ticket_columns:
    raise ValueError(
        f" Missing ticket columns: {sorted(missing_ticket_columns)}"
    )

print("All required ticket columns are present.")

print("\nTicket columns:")
for i, column in enumerate(tickets.columns, start=1):
    print(f"{i:2}. {column}")

✅ All required ticket columns are present.

Ticket columns:
 1. ticket_id
 2. created_at
 3. first_response_at
 4. resolved_at
 5. status
 6. channel
 7. customer_id
 8. order_id
 9. product_sku
10. category
11. priority
12. assigned_team
13. agent_id
14. transfers
15. csat_score
16. refund_amount_inr
17. refund_reason_code
18. replacement_issued
19. customer_message
20. agent_notes
21. source_system

In [ ]:
# Cell 6: Inspect raw tickets

print("First 5 ticket records:")
display(tickets.head())

print("\nData types:")
display(tickets.dtypes.to_frame("dtype"))

print("\nTicket status distribution:")
display(
    tickets["status"]
    .value_counts(dropna=False)
    .rename_axis("status")
    .reset_index(name="tickets")
)

print("\nChannel distribution:")
display(
    tickets["channel"]
    .value_counts(dropna=False)
    .rename_axis("channel")
    .reset_index(name="tickets")
)

First 5 ticket records:

,ticket_id,created_at,first_response_at,resolved_at,status,channel,customer_id,order_id,product_sku,category,priority,assigned_team,agent_id,transfers,csat_score,refund_amount_inr,refund_reason_code,replacement_issued,customer_message,agent_notes,source_system
0,TK-240001,2025-01-01 06:12,2025-01-01 06:20,2025-01-02 06:33,resolved,voice,C102873,NaN,VA-EB-AIR,Billing & Payments,High,Billing,A3033,0,3.0,764.0,RETURN-QC-OK,N,[IVR transcript] you picked up the item 4 days...,re: refund pending | chk reverse pickup qc sta...,legacy_fd
1,TK-240002,2025-01-01 09:01,2025-01-01 09:34,2025-01-01 09:45,resolved,social,C103321,NaN,VA-HP-ST3,Other,Normal,Chat Frontline,A3015,0,0.0,NaN,NaN,N,product: my strata 3 headphones\norder: vr8959...,Reported: promo code invalid. Checked coupon v...,legacy_fd
2,TK-240004,2025-01-02 00:41,2025-01-02 03:41,2025-01-04 03:59,resolved,email,C100687,VR895382,VA-EB-PL1,Delivery & Shipping,Normal,Logistics,A3028,0,4.0,NaN,NaN,N,"hi there,\norder vr895382 (my pulse). i haven'...",Cust contacted re order not delivered. Confiir...,legacy_fd
3,TK-240006,2025-01-02 02:21,2025-01-02 03:38,2025-01-12 04:37,resolved,social,C104148,NaN,VA-EB-PL1,Audio Quality,Normal,Chat Frontline,A3044,1,3.0,NaN,NaN,N,honestly regretting this purchase. bought the ...,1. Audio distortion\n2. Asked for a recording\...,legacy_fd
4,TK-240007,2025-01-02 04:05,2025-01-02 04:38,2025-01-02 05:09,resolved,social,C103733,VR883581,VA-EB-PL1,Billing & Payments,Normal,Billing,A3035,0,0.0,NaN,NaN,N,"paid via UPI, amount deducted, no order confir...",cx: amount deducted without order | asked for ...,legacy_fd

Data types:

                      dtype
ticket_id            object
created_at           object
first_response_at    object
resolved_at          object
status               object
channel              object
customer_id          object
order_id             object
product_sku          object
category             object
priority             object
assigned_team        object
agent_id             object
transfers             int64
csat_score          float64
refund_amount_inr   float64
refund_reason_code   object
replacement_issued   object
customer_message     object
agent_notes          object
source_system        object

Ticket status distribution:

     status  tickets
0  resolved    10116
1    closed     1076
2      open      372
3   pending      252

Channel distribution:

  channel  tickets
0    chat     5235
1   email     3844
2   voice     1566
3  social     1171

In [ ]:
# Cell 7: Duplicate ticket audit

duplicate_mask = tickets["ticket_id"].duplicated(keep=False)

duplicate_rows = tickets.loc[duplicate_mask].copy()

duplicate_ticket_ids = duplicate_rows["ticket_id"].nunique()

print(f"Total raw rows              : {len(tickets):,}")
print(f"Unique ticket IDs           : {tickets['ticket_id'].nunique():,}")
print(f"Rows in duplicated ticket IDs: {len(duplicate_rows):,}")
print(f"Duplicated ticket IDs       : {duplicate_ticket_ids:,}")

print("\nDuplicate source-system combinations:")
display(
    duplicate_rows
    .groupby(["ticket_id", "source_system"])
    .size()
    .reset_index(name="rows")
    .head(20)
)

Total raw rows              : 11,816
Unique ticket IDs           : 11,200
Rows in duplicated ticket IDs: 1,232
Duplicated ticket IDs       : 616

Duplicate source-system combinations:

    ticket_id source_system  rows
0   TK-240016      helpdesk     1
1   TK-240016     legacy_fd     1
2   TK-240018      helpdesk     1
3   TK-240018     legacy_fd     1
4   TK-240021      helpdesk     1
5   TK-240021     legacy_fd     1
6   TK-240025      helpdesk     1
7   TK-240025     legacy_fd     1
8   TK-240030      helpdesk     1
9   TK-240030     legacy_fd     1
10  TK-240032      helpdesk     1
11  TK-240032     legacy_fd     1
12  TK-240039      helpdesk     1
13  TK-240039     legacy_fd     1
14  TK-240041      helpdesk     1
15  TK-240041     legacy_fd     1
16  TK-240044      helpdesk     1
17  TK-240044     legacy_fd     1
18  TK-240045      helpdesk     1
19  TK-240045     legacy_fd     1

In [ ]:
# Cell 8: Inspect duplicate migration records

duplicate_source_counts = (
    duplicate_rows
    .groupby("ticket_id")["source_system"]
    .agg(lambda x: sorted(set(x)))
    .reset_index(name="source_systems")
)

print("How many duplicated tickets contain both source systems?")

both_systems = duplicate_source_counts[
    duplicate_source_counts["source_systems"].apply(
        lambda x: set(x) == {"helpdesk", "legacy_fd"}
    )
]

print(f"Duplicated IDs with helpdesk + legacy_fd: {len(both_systems):,}")

print("\nExample duplicated ticket:")
if len(both_systems) > 0:
    example_ticket_id = both_systems.iloc[0]["ticket_id"]

    display(
        tickets[
            tickets["ticket_id"] == example_ticket_id
        ].sort_values("source_system")
    )

How many duplicated tickets contain both source systems?
Duplicated IDs with helpdesk + legacy_fd: 616

Example duplicated ticket:

,ticket_id,created_at,first_response_at,resolved_at,status,channel,customer_id,order_id,product_sku,category,priority,assigned_team,agent_id,transfers,csat_score,refund_amount_inr,refund_reason_code,replacement_issued,customer_message,agent_notes,source_system
12,TK-240016,2025-01-03 03:38,2025-01-03 03:57,2025-01-03 04:25,resolved,voice,C103315,NaN,VA-AC-CH65,Other,Normal,Voice Frontline,A3024,0,NaN,1499.0,DUP-PAYMENT,N,[IVR transcript] helo teh page failed after i ...,cx: failed order after payment | asked for utr...,helpdesk
13,TK-240016,2025-01-03 03:38,2025-01-03 03:57,2025-01-03 04:25,resolved,voice,C103315,NaN,VA-AC-CH65,Other,Normal,Voice Frontline,A3024,0,0.0,1499.0,DUP-PAYMENT,N,[IVR transcript] helo teh page failed after i ...,cx: failed order after payment | asked for utr...,legacy_fd

In [ ]:
# Cell 9: Deduplicate tickets

tickets_clean = tickets.copy()

# Prefer the current helpdesk record over the legacy migration record.
source_priority = {
    "helpdesk": 0,
    "legacy_fd": 1
}

tickets_clean["_source_priority"] = (
    tickets_clean["source_system"]
    .map(source_priority)
    .fillna(99)
)

tickets_clean = (
    tickets_clean
    .sort_values(
        by=["ticket_id", "_source_priority"],
        kind="stable"
    )
    .drop_duplicates(
        subset="ticket_id",
        keep="first"
    )
    .drop(columns="_source_priority")
    .reset_index(drop=True)
)

print("Canonical ticket dataset created.\n")

print(f"Raw ticket rows       : {len(tickets):,}")
print(f"Clean ticket rows     : {len(tickets_clean):,}")
print(f"Rows removed          : {len(tickets) - len(tickets_clean):,}")
print(f"Unique ticket IDs     : {tickets_clean['ticket_id'].nunique():,}")

✅ Canonical ticket dataset created.

Raw ticket rows       : 11,816
Clean ticket rows     : 11,200
Rows removed          : 616
Unique ticket IDs     : 11,200

In [ ]:
# Cell 10: Convert UTC timestamps to IST

timestamp_columns = [
    "created_at",
    "first_response_at",
    "resolved_at"
]

for column in timestamp_columns:
    # Parse the CSV timestamp explicitly as UTC.
    tickets_clean[column] = pd.to_datetime(
        tickets_clean[column],
        errors="coerce",
        utc=True
    )

    # Convert UTC → Asia/Kolkata (IST).
    tickets_clean[f"{column}_ist"] = (
        tickets_clean[column]
        .dt.tz_convert("Asia/Kolkata")
    )

print("UTC → IST conversion completed.\n")

display(
    tickets_clean[
        [
            "ticket_id",
            "created_at",
            "created_at_ist",
            "first_response_at",
            "first_response_at_ist",
            "resolved_at",
            "resolved_at_ist"
        ]
    ].head(10)
)

✅ UTC → IST conversion completed.

   ticket_id                created_at            created_at_ist         first_response_at     first_response_at_ist               resolved_at           resolved_at_ist
0  TK-240001 2025-01-01 06:12:00+00:00 2025-01-01 11:42:00+05:30 2025-01-01 06:20:00+00:00 2025-01-01 11:50:00+05:30 2025-01-02 06:33:00+00:00 2025-01-02 12:03:00+05:30
1  TK-240002 2025-01-01 09:01:00+00:00 2025-01-01 14:31:00+05:30 2025-01-01 09:34:00+00:00 2025-01-01 15:04:00+05:30 2025-01-01 09:45:00+00:00 2025-01-01 15:15:00+05:30
2  TK-240004 2025-01-02 00:41:00+00:00 2025-01-02 06:11:00+05:30 2025-01-02 03:41:00+00:00 2025-01-02 09:11:00+05:30 2025-01-04 03:59:00+00:00 2025-01-04 09:29:00+05:30
3  TK-240006 2025-01-02 02:21:00+00:00 2025-01-02 07:51:00+05:30 2025-01-02 03:38:00+00:00 2025-01-02 09:08:00+05:30 2025-01-12 04:37:00+00:00 2025-01-12 10:07:00+05:30
4  TK-240007 2025-01-02 04:05:00+00:00 2025-01-02 09:35:00+05:30 2025-01-02 04:38:00+00:00 2025-01-02 10:08:00+05:30 2025-01-02 05:09:00+00:00 2025-01-02 10:39:00+05:30
5  TK-240008 2025-01-02 08:06:00+00:00 2025-01-02 13:36:00+05:30 2025-01-02 08:16:00+00:00 2025-01-02 13:46:00+05:30 2025-01-02 08:25:00+00:00 2025-01-02 13:55:00+05:30
6  TK-240009 2025-01-02 10:01:00+00:00 2025-01-02 15:31:00+05:30 2025-01-02 11:42:00+00:00 2025-01-02 17:12:00+05:30 2025-01-02 11:56:00+00:00 2025-01-02 17:26:00+05:30
7  TK-240010 2025-01-02 11:24:00+00:00 2025-01-02 16:54:00+05:30 2025-01-02 11:28:00+00:00 2025-01-02 16:58:00+05:30 2025-01-03 18:32:00+00:00 2025-01-04 00:02:00+05:30
8  TK-240011 2025-01-02 12:45:00+00:00 2025-01-02 18:15:00+05:30 2025-01-02 13:24:00+00:00 2025-01-02 18:54:00+05:30 2025-01-02 13:45:00+00:00 2025-01-02 19:15:00+05:30
9  TK-240012 2025-01-02 14:15:00+00:00 2025-01-02 19:45:00+05:30 2025-01-02 14:29:00+00:00 2025-01-02 19:59:00+05:30 2025-01-02 14:51:00+00:00 2025-01-02 20:21:00+05:30

In [ ]:
# CELL 11 — Timestamp quality checks

timestamp_check = pd.DataFrame({
    "column": timestamp_columns,
    "missing_values": [
        tickets_clean[col].isna().sum()
        for col in timestamp_columns
    ],
    "invalid_or_missing_pct": [
        round(tickets_clean[col].isna().mean() * 100, 2)
        for col in timestamp_columns
    ]
})

print("Timestamp quality check:")
display(timestamp_check)

# First response cannot be before ticket creation
invalid_response_order = (
    tickets_clean["first_response_at"] < tickets_clean["created_at"]
).sum()

# Resolution cannot be before ticket creation
invalid_resolution_order = (
    tickets_clean["resolved_at"] < tickets_clean["created_at"]
).sum()

print(f"\nFirst response before creation : {invalid_response_order:,}")
print(f"Resolution before creation    : {invalid_resolution_order:,}")

if invalid_response_order > 0 or invalid_resolution_order > 0:
    raise ValueError("❌ Invalid timestamp ordering detected.")

print("Timestamp ordering checks passed.")

Timestamp quality check:

              column  missing_values  invalid_or_missing_pct
0         created_at               0                    0.00
1  first_response_at               0                    0.00
2        resolved_at             589                    5.26

First response before creation : 0
Resolution before creation    : 0
✅ Timestamp ordering checks passed.

In [ ]:
# CELL 12 — Calculate first-response time

tickets_clean["response_time_minutes"] = (
    tickets_clean["first_response_at"] - tickets_clean["created_at"]
).dt.total_seconds() / 60

# Basic quality checks
negative_response_times = (
    tickets_clean["response_time_minutes"] < 0
).sum()

missing_response_times = (
    tickets_clean["response_time_minutes"].isna()
).sum()

print(f"Negative response times : {negative_response_times:,}")
print(f"Missing response times  : {missing_response_times:,}")

if negative_response_times > 0:
    raise ValueError("Negative response times detected.")

if missing_response_times > 0:
    raise ValueError("Missing response times detected.")

print("\nResponse-time summary (minutes):")
display(
    tickets_clean["response_time_minutes"]
    .describe()
    .to_frame("minutes")
)

print(" Response-time calculation completed.")

Negative response times : 0
Missing response times  : 0

Response-time summary (minutes):

            minutes
count  11200.000000
mean     155.174643
std      229.881160
min        0.000000
25%        7.000000
50%       51.000000
75%      241.000000
max     5155.000000

 Response-time calculation completed.

In [ ]:
# CELL 13 — Apply channel-specific SLA targets

sla_minutes = {
    "chat": 15,
    "voice": 120,
    "social": 240,
    "email": 480
}

tickets_clean["sla_target_minutes"] = (
    tickets_clean["channel"]
    .str.lower()
    .map(sla_minutes)
)

unknown_channels = tickets_clean.loc[
    tickets_clean["sla_target_minutes"].isna(),
    "channel"
].dropna().unique()

if len(unknown_channels) > 0:
    raise ValueError(
        f"Unknown channel(s) found: {sorted(unknown_channels.tolist())}"
    )

print("SLA targets applied successfully:\n")

sla_summary = (
    tickets_clean[["channel", "sla_target_minutes"]]
    .drop_duplicates()
    .sort_values("channel")
)

display(sla_summary)

print(" Channel-specific SLA targets applied.")

SLA targets applied successfully:

  channel  sla_target_minutes
7    chat                  15
2   email                 480
1  social                 240
0   voice                 120

 Channel-specific SLA targets applied.

In [ ]:
# CELL 14 — Determine SLA breach

tickets_clean["sla_breach"] = (
    tickets_clean["response_time_minutes"]
    > tickets_clean["sla_target_minutes"]
)

tickets_clean["sla_status"] = np.where(
    tickets_clean["sla_breach"],
    "BREACH",
    "PASS"
)

print("Overall SLA status:")
display(
    tickets_clean["sla_status"]
    .value_counts()
    .rename_axis("sla_status")
    .reset_index(name="tickets")
)

print("\nBreach rate:")
overall_breach_rate = tickets_clean["sla_breach"].mean() * 100
print(f"{overall_breach_rate:.2f}%")

print("SLA breach calculation completed.")

Overall SLA status:

  sla_status  tickets
0       PASS     8760
1     BREACH     2440

Breach rate:
21.79%
SLA breach calculation completed.

In [ ]:
# CELL 15 — Calculate SLA credit exposure

SLA_CREDIT_PER_BREACH = 350

tickets_clean["sla_credit_exposure_inr"] = np.where(
    tickets_clean["sla_breach"],
    SLA_CREDIT_PER_BREACH,
    0
)

total_breaches = int(tickets_clean["sla_breach"].sum())
total_credit_exposure = int(
    tickets_clean["sla_credit_exposure_inr"].sum()
)

print(f"Total tickets analyzed : {len(tickets_clean):,}")
print(f"Total SLA breaches     : {total_breaches:,}")
print(f"Breach rate            : {overall_breach_rate:.2f}%")
print(f"SLA credit exposure    : ₹{total_credit_exposure:,.0f}")

print("\nExposure check:")
print(
    f"{total_breaches:,} breaches × ₹{SLA_CREDIT_PER_BREACH:,} "
    f"= ₹{total_credit_exposure:,.0f}"
)

print("SLA financial exposure calculated.")

Total tickets analyzed : 11,200
Total SLA breaches     : 2,440
Breach rate            : 21.79%
SLA credit exposure    : ₹854,000

Exposure check:
2,440 breaches × ₹350 = ₹854,000
SLA financial exposure calculated.

In [ ]:
print(agents.columns.tolist())
print(agents.head())

['agent_id', 'name', 'site', 'team', 'shift', 'tier', 'from_date', 'to_date']
  agent_id                name    site            team  shift  tier   from_date     to_date
0    A3001          Zoya Mehta  Indore  Chat Frontline  Night     1  2021-04-20  2025-06-29
1    A3002        Tarun Mishra  Indore  Chat Frontline  Night     1  2023-02-12  2025-06-29
2    A3002        Tarun Mishra  Indore  Chat Frontline    Day     1  2025-06-30         NaN
3    A3003  Harpreet Deshpande  Indore  Chat Frontline  Night     1  2023-06-14  2025-06-29
4    A3003  Harpreet Deshpande  Indore  Chat Frontline    Day     1  2025-06-30         NaN

In [ ]:
# CELL 16 — Validate and prepare agent roster

agents_clean = agents.copy()

# Clean column names
agents_clean.columns = agents_clean.columns.str.strip()

# Required columns from the actual agents.csv
required_agent_columns = {
    "agent_id",
    "name",
    "site",
    "team",
    "shift",
    "tier",
    "from_date",
    "to_date"
}

missing_agent_columns = sorted(
    required_agent_columns - set(agents_clean.columns)
)

if missing_agent_columns:
    raise ValueError(
        f"Missing agent columns: {missing_agent_columns}"
    )

# Convert roster dates
agents_clean["from_date"] = pd.to_datetime(
    agents_clean["from_date"],
    errors="coerce"
)

agents_clean["to_date"] = pd.to_datetime(
    agents_clean["to_date"],
    errors="coerce"
)

# Validate dates
invalid_date_rows = (
    agents_clean["from_date"].isna()
).sum()

if invalid_date_rows > 0:
    raise ValueError(
        f" {invalid_date_rows:,} roster rows have invalid from_date values."
    )

print("Agent roster validation completed.\n")

print(f"Assignment rows : {len(agents_clean):,}")
print(f"Unique agents   : {agents_clean['agent_id'].nunique():,}")

print("\nShift distribution:")
display(
    agents_clean["shift"]
    .value_counts(dropna=False)
    .rename_axis("shift")
    .reset_index(name="assignments")
)

print("\nTier distribution:")
display(
    agents_clean["tier"]
    .value_counts(dropna=False)
    .rename_axis("tier")
    .reset_index(name="assignments")
)

print("\nRoster preview:")
display(agents_clean.head(10))

Agent roster validation completed.

Assignment rows : 46
Unique agents   : 44

Shift distribution:

     shift  assignments
0      Day           21
1  Morning           20
2    Night            5

Tier distribution:

   tier  assignments
0     1           40
1     2            6

Roster preview:

  agent_id                name       site            team    shift  tier  from_date    to_date
0    A3001          Zoya Mehta     Indore  Chat Frontline    Night     1 2021-04-20 2025-06-29
1    A3002        Tarun Mishra     Indore  Chat Frontline    Night     1 2023-02-12 2025-06-29
2    A3002        Tarun Mishra     Indore  Chat Frontline      Day     1 2025-06-30        NaT
3    A3003  Harpreet Deshpande     Indore  Chat Frontline    Night     1 2023-06-14 2025-06-29
4    A3003  Harpreet Deshpande     Indore  Chat Frontline      Day     1 2025-06-30        NaT
5    A3004       Krishna Naidu  Bengaluru  Chat Frontline      Day     1 2022-12-30        NaT
6    A3005        Sameer Joshi  Bengaluru  Chat Frontline  Morning     1 2021-07-28        NaT
7    A3006       Lakshmi Reddy  Bengaluru  Chat Frontline      Day     1 2021-02-05        NaT
8    A3007        Neha Gaikwad  Bengaluru  Chat Frontline  Morning     1 2023-09-10        NaT
9    A3008         Steven Kaur     Indore  Chat Frontline  Morning     1 2022-05-02        NaT

In [ ]:
# CELL 17 — Attach historical roster assignment

# Ticket creation date in IST
tickets_clean["_created_date_ist"] = (
    tickets_clean["created_at_ist"]
    .dt.tz_localize(None)
    .dt.normalize()
)

# Prepare roster
agents_lookup = agents_clean.copy()

# Open-ended assignments remain active indefinitely
agents_lookup["to_date_filled"] = agents_lookup["to_date"].fillna(
    pd.Timestamp("2099-12-31")
)

# Rename roster columns to avoid conflicts
agents_lookup = agents_lookup.rename(columns={
    "name": "roster_agent_name",
    "site": "roster_site",
    "team": "roster_team",
    "shift": "roster_shift",
    "tier": "roster_tier"
})

# Match tickets to agent assignments
ticket_roster = tickets_clean.merge(
    agents_lookup[
        [
            "agent_id",
            "roster_agent_name",
            "roster_site",
            "roster_team",
            "roster_shift",
            "roster_tier",
            "from_date",
            "to_date_filled"
        ]
    ],
    on="agent_id",
    how="left"
)

# Keep the assignment active when the ticket was created
active_assignment = (
    (ticket_roster["_created_date_ist"] >= ticket_roster["from_date"]) &
    (ticket_roster["_created_date_ist"] <= ticket_roster["to_date_filled"])
)

ticket_roster = ticket_roster.loc[active_assignment].copy()

# Check matching quality
roster_match_counts = (
    ticket_roster.groupby("ticket_id")
    .size()
)

multiple_roster_matches = (
    roster_match_counts > 1
).sum()

matched_ticket_ids = set(ticket_roster["ticket_id"])
all_ticket_ids = set(tickets_clean["ticket_id"])

unmatched_ticket_ids = (
    all_ticket_ids - matched_ticket_ids
)

print("Historical roster matching results:")
print(f"Tickets in clean dataset       : {len(all_ticket_ids):,}")
print(f"Tickets matched to roster      : {len(matched_ticket_ids):,}")
print(f"Tickets without roster match   : {len(unmatched_ticket_ids):,}")
print(f"Tickets with multiple matches  : {multiple_roster_matches:,}")

if multiple_roster_matches > 0:
    print("\nMultiple roster assignments detected.")
else:
    print("\nNo multiple roster assignments detected.")

Historical roster matching results:
Tickets in clean dataset       : 11,200
Tickets matched to roster      : 11,200
Tickets without roster match   : 0
Tickets with multiple matches  : 0

No multiple roster assignments detected.

In [ ]:
# CELL 18 — Build final analysis dataset

analysis = ticket_roster.copy()

# Shift from historical roster
analysis["agent_shift"] = analysis["roster_shift"]

# Operational shift based on ticket creation time in IST
def determine_shift(hour):
    if 6 <= hour < 14:
        return "Morning"
    elif 14 <= hour < 22:
        return "Day"
    else:
        return "Night"

analysis["operational_shift"] = (
    analysis["created_at_ist"]
    .dt.hour
    .apply(determine_shift)
)

# Weekly reporting period
analysis["week_start"] = (
    analysis["created_at_ist"]
    .dt.tz_localize(None)
    .dt.to_period("W-SUN")
    .dt.start_time
)

print("Final analysis dataset created.")
print(f"Rows: {len(analysis):,}")

print("\nAgent shift distribution:")
display(
    analysis["agent_shift"]
    .value_counts(dropna=False)
    .rename_axis("agent_shift")
    .reset_index(name="tickets")
)

print("\nOperational shift distribution:")
display(
    analysis["operational_shift"]
    .value_counts(dropna=False)
    .rename_axis("operational_shift")
    .reset_index(name="tickets")
)

Final analysis dataset created.
Rows: 11,200

Agent shift distribution:

  agent_shift  tickets
0     Morning     6264
1         Day     4668
2       Night      268

Operational shift distribution:

  operational_shift  tickets
0               Day     4668
1           Morning     4046
2             Night     2486

In [ ]:
# CELL 19 — Weekly shift SLA report

weekly_shift_report = (
    analysis
    .groupby(
        ["week_start", "agent_shift"],
        dropna=False
    )
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

# Calculate breach rate
weekly_shift_report["breach_rate_pct"] = (
    weekly_shift_report["breaches"]
    / weekly_shift_report["tickets"]
    * 100
)

# Avoid division-by-zero issues
weekly_shift_report["breach_rate_pct"] = (
    weekly_shift_report["breach_rate_pct"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

# Sort for easier reading
weekly_shift_report = weekly_shift_report.sort_values(
    ["week_start", "breaches"],
    ascending=[True, False]
).reset_index(drop=True)

print("Weekly shift SLA report created.")
print(f"Reporting weeks: {weekly_shift_report['week_start'].nunique():,}")

display(weekly_shift_report.head(30))

Weekly shift SLA report created.
Reporting weeks: 79

   week_start agent_shift  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0  2024-12-30         Day       13         0                        0         0.000000
1  2024-12-30     Morning       14         0                        0         0.000000
2  2024-12-30       Night        4         0                        0         0.000000
3  2025-01-06       Night        9         2                      700        22.222222
4  2025-01-06         Day       21         1                      350         4.761905
5  2025-01-06     Morning       20         0                        0         0.000000
6  2025-01-13         Day       27         4                     1400        14.814815
7  2025-01-13     Morning       24         3                     1050        12.500000
8  2025-01-13       Night        7         1                      350        14.285714
9  2025-01-20     Morning       32         4                     1400        12.500000
10 2025-01-20       Night       12         2                      700        16.666667
11 2025-01-20         Day       36         1                      350         2.777778
12 2025-01-27     Morning       35         4                     1400        11.428571
13 2025-01-27         Day       27         1                      350         3.703704
14 2025-01-27       Night       10         1                      350        10.000000
15 2025-02-03     Morning       40         8                     2800        20.000000
16 2025-02-03         Day       33         6                     2100        18.181818
17 2025-02-03       Night       12         2                      700        16.666667
18 2025-02-10     Morning       42         6                     2100        14.285714
19 2025-02-10         Day       31         2                      700         6.451613
20 2025-02-10       Night       10         1                      350        10.000000
21 2025-02-17     Morning       50         7                     2450        14.000000
22 2025-02-17         Day       40         3                     1050         7.500000
23 2025-02-17       Night        8         0                        0         0.000000
24 2025-02-24     Morning       39         4                     1400        10.256410
25 2025-02-24         Day       47         2                      700         4.255319
26 2025-02-24       Night        8         1                      350        12.500000
27 2025-03-03     Morning       38         5                     1750        13.157895
28 2025-03-03         Day       37         1                      350         2.702703
29 2025-03-03       Night       11         0                        0         0.000000

In [ ]:
# CELL 20 — Weekly agent SLA report

weekly_agent_report = (
    analysis
    .groupby(
        [
            "week_start",
            "agent_id",
            "roster_agent_name",
            "agent_shift",
            "roster_site",
            "roster_team",
            "roster_tier"
        ],
        dropna=False
    )
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

# Calculate breach rate
weekly_agent_report["breach_rate_pct"] = (
    weekly_agent_report["breaches"]
    / weekly_agent_report["tickets"]
    * 100
)

# Protect against division-by-zero
weekly_agent_report["breach_rate_pct"] = (
    weekly_agent_report["breach_rate_pct"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

# Sort:
# 1. Week
# 2. Highest breach volume
# 3. Highest breach rate
weekly_agent_report = weekly_agent_report.sort_values(
    [
        "week_start",
        "breaches",
        "breach_rate_pct"
    ],
    ascending=[True, False, False]
).reset_index(drop=True)

print(" Weekly agent SLA report created.")
print(f"Reporting weeks : {weekly_agent_report['week_start'].nunique():,}")
print(f"Agent-week rows  : {len(weekly_agent_report):,}")

display(weekly_agent_report.head(50))

 Weekly agent SLA report created.
Reporting weeks : 79
Agent-week rows  : 2,935

   week_start agent_id   roster_agent_name agent_shift roster_site             roster_team  roster_tier  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0  2024-12-30    A3002        Tarun Mishra       Night      Indore          Chat Frontline            1        2         0                        0         0.000000
1  2024-12-30    A3004       Krishna Naidu         Day   Bengaluru          Chat Frontline            1        1         0                        0         0.000000
2  2024-12-30    A3006       Lakshmi Reddy         Day   Bengaluru          Chat Frontline            1        2         0                        0         0.000000
3  2024-12-30    A3010     Neha Chatterjee     Morning      Indore          Chat Frontline            1        1         0                        0         0.000000
4  2024-12-30    A3015        Yash Agarwal         Day   Bengaluru          Chat Frontline            1        1         0                        0         0.000000
5  2024-12-30    A3016       Deepak Jadhav       Night      Indore         Email Frontline            1        1         0                        0         0.000000
6  2024-12-30    A3017        Shreya Bhatt       Night      Indore         Email Frontline            1        1         0                        0         0.000000
7  2024-12-30    A3022       Steven Tiwari         Day   Bengaluru         Email Frontline            1        1         0                        0         0.000000
8  2024-12-30    A3023        Rahul Khanna         Day   Bengaluru         Voice Frontline            1        2         0                        0         0.000000
9  2024-12-30    A3024        Kunal Khanna     Morning   Bengaluru         Voice Frontline            1        2         0                        0         0.000000
10 2024-12-30    A3027      Dev Chatterjee         Day      Indore               Logistics            1        1         0                        0         0.000000
11 2024-12-30    A3028        Krishna Kaur     Morning      Indore               Logistics            1        2         0                        0         0.000000
12 2024-12-30    A3029          Rajat Iyer         Day   Bengaluru               Logistics            1        2         0                        0         0.000000
13 2024-12-30    A3031         Om Malhotra     Morning   Bengaluru               Logistics            1        1         0                        0         0.000000
14 2024-12-30    A3032       Aadhya Sheikh     Morning      Indore                 Billing            1        1         0                        0         0.000000
15 2024-12-30    A3033       Amit Kulkarni     Morning   Bengaluru                 Billing            1        2         0                        0         0.000000
16 2024-12-30    A3034        Thomas Patel         Day   Bengaluru                 Billing            1        1         0                        0         0.000000
17 2024-12-30    A3035     Rohit Mukherjee     Morning   Bengaluru                 Billing            1        1         0                        0         0.000000
18 2024-12-30    A3037           Rahul Sen     Morning   Bengaluru            Returns Desk            1        2         0                        0         0.000000
19 2024-12-30    A3039        Riya Gaikwad     Morning   Bengaluru  Escalations & Warranty            2        1         0                        0         0.000000
20 2024-12-30    A3042       Steven Chopra         Day   Bengaluru  Escalations & Warranty            2        1         0                        0         0.000000
21 2024-12-30    A3043          Rohit Jain     Morning   Bengaluru  Escalations & Warranty            2        1         0                        0         0.000000
22 2024-12-30    A3044      Kunal Malhotra         Day   Bengaluru  Escalations & Warranty            2        1         0                        0         0.000000
23 2025-01-06    A3003  Harpreet Deshpande       Night      Indore          Chat Frontline            1        2         1                      350        50.000000
24 2025-01-06    A3015        Yash Agarwal         Day   Bengaluru          Chat Frontline            1        2         1                      350        50.000000
25 2025-01-06    A3002        Tarun Mishra       Night      Indore          Chat Frontline            1        3         1                      350        33.333333
26 2025-01-06    A3001          Zoya Mehta       Night      Indore          Chat Frontline            1        2         0                        0         0.000000
27 2025-01-06    A3004       Krishna Naidu         Day   Bengaluru          Chat Frontline            1        1         0                        0         0.000000
28 2025-01-06    A3005        Sameer Joshi     Morning   Bengaluru          Chat Frontline            1        2         0                        0         0.000000
29 2025-01-06    A3006       Lakshmi Reddy         Day   Bengaluru          Chat Frontline            1        1         0                        0         0.000000
30 2025-01-06    A3011           Karan Roy     Morning      Indore          Chat Frontline            1        1         0                        0         0.000000
31 2025-01-06    A3012       Lakshmi Sethi         Day   Bengaluru          Chat Frontline            1        6         0                        0         0.000000
32 2025-01-06    A3013   Ritika Chatterjee     Morning      Indore          Chat Frontline            1        1         0                        0         0.000000
33 2025-01-06    A3017        Shreya Bhatt       Night      Indore         Email Frontline            1        2         0                        0         0.000000
34 2025-01-06    A3020        Ramesh Ghosh         Day   Bengaluru         Email Frontline            1        1         0                        0         0.000000
35 2025-01-06    A3021      Aditya Dhillon         Day   Bengaluru         Email Frontline            1        2         0                        0         0.000000
36 2025-01-06    A3022       Steven Tiwari         Day   Bengaluru         Email Frontline            1        2         0                        0         0.000000
37 2025-01-06    A3023        Rahul Khanna         Day   Bengaluru         Voice Frontline            1        1         0                        0         0.000000
38 2025-01-06    A3024        Kunal Khanna     Morning   Bengaluru         Voice Frontline            1        1         0                        0         0.000000
39 2025-01-06    A3025         Lobsang Rao     Morning   Bengaluru         Voice Frontline            1        1         0                        0         0.000000
40 2025-01-06    A3026     Lakshmi Qureshi         Day   Bengaluru         Voice Frontline            1        2         0                        0         0.000000
41 2025-01-06    A3027      Dev Chatterjee         Day      Indore               Logistics            1        1         0                        0         0.000000
42 2025-01-06    A3028        Krishna Kaur     Morning      Indore               Logistics            1        2         0                        0         0.000000
43 2025-01-06    A3031         Om Malhotra     Morning   Bengaluru               Logistics            1        5         0                        0         0.000000
44 2025-01-06    A3032       Aadhya Sheikh     Morning      Indore                 Billing            1        1         0                        0         0.000000
45 2025-01-06    A3033       Amit Kulkarni     Morning   Bengaluru                 Billing            1        1         0                        0         0.000000
46 2025-01-06    A3035     Rohit Mukherjee     Morning   Bengaluru                 Billing            1        1         0                        0         0.000000
47 2025-01-06    A3038          Amit Yadav         Day   Bengaluru            Returns Desk            1        1         0                        0         0.000000
48 2025-01-06    A3039        Riya Gaikwad     Morning   Bengaluru  Escalations & Warranty            2        4         0                        0         0.000000
49 2025-01-06    A3044      Kunal Malhotra         Day   Bengaluru  Escalations & Warranty            2        1         0                        0         0.000000

In [ ]:
# CELL 21 — Overall SLA validation

print("=" * 70)
print("OVERALL SLA VALIDATION")
print("=" * 70)

total_tickets = analysis["ticket_id"].nunique()
total_breaches = int(analysis["sla_breach"].sum())
total_passes = total_tickets - total_breaches

calculated_breach_rate = (
    total_breaches / total_tickets * 100
    if total_tickets > 0 else 0
)

calculated_exposure = int(
    analysis["sla_credit_exposure_inr"].sum()
)

expected_exposure = total_breaches * SLA_CREDIT_PER_BREACH

print(f"Total tickets       : {total_tickets:,}")
print(f"SLA passes          : {total_passes:,}")
print(f"SLA breaches        : {total_breaches:,}")
print(f"Breach rate         : {calculated_breach_rate:.2f}%")
print(f"Credit exposure     : ₹{calculated_exposure:,.0f}")
print(f"Expected exposure   : ₹{expected_exposure:,.0f}")

# Validation checks
assert total_tickets == total_passes + total_breaches
assert calculated_exposure == expected_exposure

print("\nTicket count reconciliation passed.")
print(" ₹350 exposure reconciliation passed.")
print(" Overall SLA validation passed.")

======================================================================
OVERALL SLA VALIDATION
======================================================================
Total tickets       : 11,200
SLA passes          : 8,760
SLA breaches        : 2,440
Breach rate         : 21.79%
Credit exposure     : ₹854,000
Expected exposure   : ₹854,000

Ticket count reconciliation passed.
 ₹350 exposure reconciliation passed.
 Overall SLA validation passed.

In [ ]:
# CELL 22 — Validate channel SLA targets

expected_sla = {
    "chat": 15,
    "voice": 120,
    "social": 240,
    "email": 480
}

channel_validation = (
    analysis
    .groupby("channel")
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        avg_response_minutes=("response_time_minutes", "mean"),
        median_response_minutes=("response_time_minutes", "median")
    )
    .reset_index()
)

channel_validation["sla_target_minutes"] = (
    channel_validation["channel"]
    .str.lower()
    .map(expected_sla)
)

channel_validation["breach_rate_pct"] = (
    channel_validation["breaches"]
    / channel_validation["tickets"]
    * 100
)

channel_validation = channel_validation.sort_values(
    "breach_rate_pct",
    ascending=False
).reset_index(drop=True)

print("Channel-level SLA performance:")
display(channel_validation)

# Verify every channel has the expected target
for channel, target in expected_sla.items():
    actual_targets = (
        analysis.loc[
            analysis["channel"].str.lower() == channel,
            "sla_target_minutes"
        ]
        .dropna()
        .unique()
    )

    assert len(actual_targets) == 1
    assert actual_targets[0] == target

print("Channel SLA targets validated.")

Channel-level SLA performance:

  channel  tickets  breaches  avg_response_minutes  median_response_minutes  sla_target_minutes  breach_rate_pct
0    chat     4959      1368             85.151240                      6.0                  15        27.586207
1  social     1106       243            152.216998                     84.0                 240        21.971067
2   email     3647       745            295.752399                    216.0                 480        20.427749
3   voice     1488        84             46.189516                     34.0                 120         5.645161

Channel SLA targets validated.

In [ ]:
# CELL 23 — Shift-level performance

shift_report = (
    analysis
    .groupby("agent_shift", dropna=False)
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        avg_response_minutes=("response_time_minutes", "mean"),
        median_response_minutes=("response_time_minutes", "median"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

shift_report["breach_rate_pct"] = (
    shift_report["breaches"]
    / shift_report["tickets"]
    * 100
)

shift_report["share_of_all_breaches_pct"] = (
    shift_report["breaches"]
    / total_breaches
    * 100
)

shift_report = shift_report.sort_values(
    "breaches",
    ascending=False
).reset_index(drop=True)

print("Overall shift performance:")
display(shift_report)

print("\nHighest breach-volume shift:")
top_volume_shift = shift_report.iloc[0]

print(
    f"{top_volume_shift['agent_shift']} — "
    f"{int(top_volume_shift['breaches']):,} breaches "
    f"({top_volume_shift['share_of_all_breaches_pct']:.2f}% of all breaches)"
)

print("Shift analysis completed.")

Overall shift performance:

  agent_shift  tickets  breaches  avg_response_minutes  median_response_minutes  sla_credit_exposure_inr  breach_rate_pct  share_of_all_breaches_pct
0     Morning     6264      2018            205.398467                     98.5                   706300        32.215837                  82.704918
1         Day     4668       393             89.203085                     25.0                   137550         8.419023                  16.106557
2       Night      268        29            130.373134                     58.0                    10150        10.820896                   1.188525

Highest breach-volume shift:
Morning — 2,018 breaches (82.70% of all breaches)
Shift analysis completed.

In [ ]:
# CELL 24 — Test the Morning-shift hypothesis

morning_row = shift_report[
    shift_report["agent_shift"].astype(str).str.lower() == "morning"
]

if len(morning_row) == 0:
    raise ValueError("❌ Morning shift was not found in the roster.")

morning_breaches = int(morning_row.iloc[0]["breaches"])
morning_breach_share = float(
    morning_row.iloc[0]["share_of_all_breaches_pct"]
)

morning_is_highest_volume = (
    shift_report.iloc[0]["agent_shift"] == morning_row.iloc[0]["agent_shift"]
)

print("Morning-shift hypothesis:")
print(f"Morning breaches          : {morning_breaches:,}")
print(f"Share of all breaches     : {morning_breach_share:.2f}%")
print(f"Highest breach volume     : {morning_is_highest_volume}")

if morning_is_highest_volume:
    print(
        "\n Neha's claim is supported by breach volume."
    )
else:
    print(
        "\nNeha's claim is NOT supported by breach volume."
    )

print("\nImportant:")
print("Breach volume and breach rate are different measures.")
print("We should report both rather than declaring a shift 'worst' from volume alone.")

Morning-shift hypothesis:
Morning breaches          : 2,018
Share of all breaches     : 82.70%
Highest breach volume     : True

 Neha's claim is supported by breach volume.

Important:
Breach volume and breach rate are different measures.
We should report both rather than declaring a shift 'worst' from volume alone.

In [ ]:
# CELL 25 — Agent ranking by breach volume

agent_overall = (
    analysis
    .groupby(
        [
            "agent_id",
            "roster_agent_name",
            "agent_shift",
            "roster_site",
            "roster_team",
            "roster_tier"
        ],
        dropna=False
    )
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

agent_overall["breach_rate_pct"] = (
    agent_overall["breaches"]
    / agent_overall["tickets"]
    * 100
)

agent_overall["share_of_all_breaches_pct"] = (
    agent_overall["breaches"]
    / total_breaches
    * 100
)

agent_by_volume = agent_overall.sort_values(
    ["breaches", "breach_rate_pct"],
    ascending=[False, False]
).reset_index(drop=True)

print("Top 20 agents by breach volume:")
display(
    agent_by_volume.head(20)
)

print("Agent breach-volume ranking created.")

Top 20 agents by breach volume:

   agent_id  roster_agent_name agent_shift roster_site             roster_team  roster_tier  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct  share_of_all_breaches_pct
0     A3037          Rahul Sen     Morning   Bengaluru            Returns Desk            1      606       179                    62650        29.537954                   7.336066
1     A3028       Krishna Kaur     Morning      Indore               Logistics            1      558       176                    61600        31.541219                   7.213115
2     A3031        Om Malhotra     Morning   Bengaluru               Logistics            1      573       168                    58800        29.319372                   6.885246
3     A3018       Farah Sheikh     Morning   Bengaluru         Email Frontline            1      526       152                    53200        28.897338                   6.229508
4     A3019         Sai Sandhu     Morning   Bengaluru         Email Frontline            1      525       144                    50400        27.428571                   5.901639
5     A3032      Aadhya Sheikh     Morning      Indore                 Billing            1      365       132                    46200        36.164384                   5.409836
6     A3033      Amit Kulkarni     Morning   Bengaluru                 Billing            1      322       109                    38150        33.850932                   4.467213
7     A3035    Rohit Mukherjee     Morning   Bengaluru                 Billing            1      340       108                    37800        31.764706                   4.426230
8     A3013  Ritika Chatterjee     Morning      Indore          Chat Frontline            1      240       100                    35000        41.666667                   4.098361
9     A3010    Neha Chatterjee     Morning      Indore          Chat Frontline            1      218        92                    32200        42.201835                   3.770492
10    A3039       Riya Gaikwad     Morning   Bengaluru  Escalations & Warranty            2      232        91                    31850        39.224138                   3.729508
11    A3009       Ramesh Patel     Morning   Bengaluru          Chat Frontline            1      202        85                    29750        42.079208                   3.483607
12    A3014         Diya Patil     Morning   Bengaluru          Chat Frontline            1      202        83                    29050        41.089109                   3.401639
13    A3011          Karan Roy     Morning      Indore          Chat Frontline            1      203        83                    29050        40.886700                   3.401639
14    A3005       Sameer Joshi     Morning   Bengaluru          Chat Frontline            1      219        81                    28350        36.986301                   3.319672
15    A3007       Neha Gaikwad     Morning   Bengaluru          Chat Frontline            1      217        78                    27300        35.944700                   3.196721
16    A3008        Steven Kaur     Morning      Indore          Chat Frontline            1      195        75                    26250        38.461538                   3.073770
17    A3043         Rohit Jain     Morning   Bengaluru  Escalations & Warranty            2      229        61                    21350        26.637555                   2.500000
18    A3034       Thomas Patel         Day   Bengaluru                 Billing            1      639        54                    18900         8.450704                   2.213115
19    A3036       Rohit Shinde         Day   Bengaluru            Returns Desk            1      232        30                    10500        12.931034                   1.229508

Agent breach-volume ranking created.

In [ ]:
# CELL 26 — Agent ranking by breach rate

MIN_TICKETS_FOR_RATE = 30

agent_by_rate = (
    agent_overall[
        agent_overall["tickets"] >= MIN_TICKETS_FOR_RATE
    ]
    .sort_values(
        ["breach_rate_pct", "breaches"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)

print(
    f"Agents with at least {MIN_TICKETS_FOR_RATE} tickets:"
)

print(f"Qualifying agent groups: {len(agent_by_rate):,}")

display(
    agent_by_rate.head(20)
)

print(
    "\nRate ranking uses a minimum-volume threshold "
    f"of {MIN_TICKETS_FOR_RATE} tickets."
)

Agents with at least 30 tickets:
Qualifying agent groups: 46

   agent_id   roster_agent_name agent_shift roster_site             roster_team  roster_tier  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct  share_of_all_breaches_pct
0     A3010     Neha Chatterjee     Morning      Indore          Chat Frontline            1      218        92                    32200        42.201835                   3.770492
1     A3009        Ramesh Patel     Morning   Bengaluru          Chat Frontline            1      202        85                    29750        42.079208                   3.483607
2     A3013   Ritika Chatterjee     Morning      Indore          Chat Frontline            1      240       100                    35000        41.666667                   4.098361
3     A3014          Diya Patil     Morning   Bengaluru          Chat Frontline            1      202        83                    29050        41.089109                   3.401639
4     A3011           Karan Roy     Morning      Indore          Chat Frontline            1      203        83                    29050        40.886700                   3.401639
5     A3039        Riya Gaikwad     Morning   Bengaluru  Escalations & Warranty            2      232        91                    31850        39.224138                   3.729508
6     A3008         Steven Kaur     Morning      Indore          Chat Frontline            1      195        75                    26250        38.461538                   3.073770
7     A3005        Sameer Joshi     Morning   Bengaluru          Chat Frontline            1      219        81                    28350        36.986301                   3.319672
8     A3032       Aadhya Sheikh     Morning      Indore                 Billing            1      365       132                    46200        36.164384                   5.409836
9     A3007        Neha Gaikwad     Morning   Bengaluru          Chat Frontline            1      217        78                    27300        35.944700                   3.196721
10    A3033       Amit Kulkarni     Morning   Bengaluru                 Billing            1      322       109                    38150        33.850932                   4.467213
11    A3035     Rohit Mukherjee     Morning   Bengaluru                 Billing            1      340       108                    37800        31.764706                   4.426230
12    A3028        Krishna Kaur     Morning      Indore               Logistics            1      558       176                    61600        31.541219                   7.213115
13    A3037           Rahul Sen     Morning   Bengaluru            Returns Desk            1      606       179                    62650        29.537954                   7.336066
14    A3031         Om Malhotra     Morning   Bengaluru               Logistics            1      573       168                    58800        29.319372                   6.885246
15    A3018        Farah Sheikh     Morning   Bengaluru         Email Frontline            1      526       152                    53200        28.897338                   6.229508
16    A3019          Sai Sandhu     Morning   Bengaluru         Email Frontline            1      525       144                    50400        27.428571                   5.901639
17    A3043          Rohit Jain     Morning   Bengaluru  Escalations & Warranty            2      229        61                    21350        26.637555                   2.500000
18    A3003  Harpreet Deshpande         Day      Indore          Chat Frontline            1      150        20                     7000        13.333333                   0.819672
19    A3036        Rohit Shinde         Day   Bengaluru            Returns Desk            1      232        30                    10500        12.931034                   1.229508

Rate ranking uses a minimum-volume threshold of 30 tickets.

In [ ]:
# CELL 27 — Separate Tier 1 and Tier 2

tier_summary = (
    analysis
    .groupby("roster_tier", dropna=False)
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

tier_summary["breach_rate_pct"] = (
    tier_summary["breaches"]
    / tier_summary["tickets"]
    * 100
)

print("Tier-level summary:")
display(tier_summary)

print("\nTier values found:")
print(sorted(analysis["roster_tier"].dropna().unique().tolist()))

print(
    "\nTier 1 and Tier 2 will be kept separate "
    "in agent-level operational comparisons."
)

print("Tier separation check completed.")

Tier-level summary:

   roster_tier  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0            1    10448      2265                   792750        21.678790
1            2      752       175                    61250        23.271277

Tier values found:
[1, 2]

Tier 1 and Tier 2 will be kept separate in agent-level operational comparisons.
Tier separation check completed.

In [ ]:
# CELL 28 — Weekly SLA trend

weekly_trend = (
    analysis
    .groupby("week_start")
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

weekly_trend["breach_rate_pct"] = (
    weekly_trend["breaches"]
    / weekly_trend["tickets"]
    * 100
)

weekly_trend["week_start"] = pd.to_datetime(
    weekly_trend["week_start"]
)

weekly_trend = weekly_trend.sort_values(
    "week_start"
).reset_index(drop=True)

print("Weekly SLA trend:")
display(weekly_trend.head(20))

print("\nMost recent weeks:")
display(weekly_trend.tail(10))

print("Weekly trend calculated.")

Weekly SLA trend:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0  2024-12-30       31         0                        0         0.000000
1  2025-01-06       50         3                     1050         6.000000
2  2025-01-13       58         8                     2800        13.793103
3  2025-01-20       80         7                     2450         8.750000
4  2025-01-27       72         6                     2100         8.333333
5  2025-02-03       85        16                     5600        18.823529
6  2025-02-10       83         9                     3150        10.843373
7  2025-02-17       98        10                     3500        10.204082
8  2025-02-24       94         7                     2450         7.446809
9  2025-03-03       86         6                     2100         6.976744
10 2025-03-10      101         9                     3150         8.910891
11 2025-03-17       88        10                     3500        11.363636
12 2025-03-24       86         6                     2100         6.976744
13 2025-03-31      104        11                     3850        10.576923
14 2025-04-07       87         7                     2450         8.045977
15 2025-04-14       83        13                     4550        15.662651
16 2025-04-21      100         6                     2100         6.000000
17 2025-04-28      114         7                     2450         6.140351
18 2025-05-05       98         6                     2100         6.122449
19 2025-05-12       86         9                     3150        10.465116

Most recent weeks:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
69 2026-04-27      181        45                    15750        24.861878
70 2026-05-04      158        35                    12250        22.151899
71 2026-05-11      172        47                    16450        27.325581
72 2026-05-18      178        45                    15750        25.280899
73 2026-05-25      157        41                    14350        26.114650
74 2026-06-01      162        36                    12600        22.222222
75 2026-06-08      163        47                    16450        28.834356
76 2026-06-15      195        46                    16100        23.589744
77 2026-06-22      207        49                    17150        23.671498
78 2026-06-29       31         3                     1050         9.677419

Weekly trend calculated.

In [ ]:
# CELL 29 — Identify high-impact weeks

high_impact_weeks = weekly_trend.sort_values(
    ["breaches", "breach_rate_pct"],
    ascending=[False, False]
).reset_index(drop=True)

print("Top 10 weeks by breach volume:")
display(
    high_impact_weeks.head(10)
)

print("\nTop 10 weeks by breach rate:")
display(
    weekly_trend.sort_values(
        ["breach_rate_pct", "breaches"],
        ascending=[False, False]
    ).head(10)
)

print("High-impact weeks identified.")

Top 10 weeks by breach volume:

  week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0 2025-10-20      211        62                    21700        29.383886
1 2025-11-24      231        61                    21350        26.406926
2 2025-12-01      204        58                    20300        28.431373
3 2025-12-29      204        56                    19600        27.450980
4 2025-09-01      157        53                    18550        33.757962
5 2025-11-03      196        53                    18550        27.040816
6 2026-03-30      172        51                    17850        29.651163
7 2026-03-09      178        51                    17850        28.651685
8 2026-01-19      184        51                    17850        27.717391
9 2026-04-20      173        50                    17500        28.901734

Top 10 weeks by breach rate:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
35 2025-09-01      157        53                    18550        33.757962
32 2025-08-11      156        49                    17150        31.410256
26 2025-06-30       92        28                     9800        30.434783
65 2026-03-30      172        51                    17850        29.651163
42 2025-10-20      211        62                    21700        29.383886
68 2026-04-20      173        50                    17500        28.901734
75 2026-06-08      163        47                    16450        28.834356
62 2026-03-09      178        51                    17850        28.651685
48 2025-12-01      204        58                    20300        28.431373
36 2025-09-08      174        49                    17150        28.160920

High-impact weeks identified.

In [ ]:
# CELL 30 — Business summary

top_shift_volume = shift_report.iloc[0]

top_agent_volume = agent_by_volume.iloc[0]

top_agent_rate = agent_by_rate.iloc[0]

total_credit_exposure = int(
    analysis["sla_credit_exposure_inr"].sum()
)

print("=" * 70)
print("VIREO SUPPORT SLA — BUSINESS SUMMARY")
print("=" * 70)

print("\nOVERALL")
print(f"Tickets analyzed       : {total_tickets:,}")
print(f"SLA breaches           : {total_breaches:,}")
print(f"Overall breach rate    : {calculated_breach_rate:.2f}%")
print(f"SLA credit exposure    : ₹{total_credit_exposure:,.0f}")

print("\nSHIFT")
print(
    f"Highest breach volume  : "
    f"{top_shift_volume['agent_shift']}"
)
print(
    f"Breaches               : "
    f"{int(top_shift_volume['breaches']):,}"
)
print(
    f"Share of breaches      : "
    f"{top_shift_volume['share_of_all_breaches_pct']:.2f}%"
)
print(
    f"Breach rate            : "
    f"{top_shift_volume['breach_rate_pct']:.2f}%"
)

print("\nTOP AGENT BY BREACH VOLUME")
print(
    f"Agent                  : "
    f"{top_agent_volume['roster_agent_name']}"
)
print(
    f"Agent ID               : "
    f"{top_agent_volume['agent_id']}"
)
print(
    f"Shift                  : "
    f"{top_agent_volume['agent_shift']}"
)
print(
    f"Tickets                : "
    f"{int(top_agent_volume['tickets']):,}"
)
print(
    f"Breaches               : "
    f"{int(top_agent_volume['breaches']):,}"
)
print(
    f"Breach rate            : "
    f"{top_agent_volume['breach_rate_pct']:.2f}%"
)
print(
    f"Credit exposure        : "
    f"₹{int(top_agent_volume['sla_credit_exposure_inr']):,}"
)

print("\nTOP AGENT BY BREACH RATE")
print(
    f"Agent                  : "
    f"{top_agent_rate['roster_agent_name']}"
)
print(
    f"Tickets                : "
    f"{int(top_agent_rate['tickets']):,}"
)
print(
    f"Breaches               : "
    f"{int(top_agent_rate['breaches']):,}"
)
print(
    f"Breach rate            : "
    f"{top_agent_rate['breach_rate_pct']:.2f}%"
)

print("\nMORNING-SHIFT CLAIM")
print(
    f"Morning is highest-volume shift: "
    f"{morning_is_highest_volume}"
)

print("\n" + "=" * 70)
print("These are descriptive findings, not causal conclusions.")
print("Next step: investigate the ticket text to identify breach-associated themes.")
print("=" * 70)

======================================================================
VIREO SUPPORT SLA — BUSINESS SUMMARY
======================================================================

OVERALL
Tickets analyzed       : 11,200
SLA breaches           : 2,440
Overall breach rate    : 21.79%
SLA credit exposure    : ₹854,000

SHIFT
Highest breach volume  : Morning
Breaches               : 2,018
Share of breaches      : 82.70%
Breach rate            : 32.22%

TOP AGENT BY BREACH VOLUME
Agent                  : Rahul Sen
Agent ID               : A3037
Shift                  : Morning
Tickets                : 606
Breaches               : 179
Breach rate            : 29.54%
Credit exposure        : ₹62,650

TOP AGENT BY BREACH RATE
Agent                  : Neha Chatterjee
Tickets                : 218
Breaches               : 92
Breach rate            : 42.20%

MORNING-SHIFT CLAIM
Morning is highest-volume shift: True

======================================================================
These are descriptive findings, not causal conclusions.
Next step: investigate the ticket text to identify breach-associated themes.
======================================================================

In [ ]:
# CELL 31 — Channel × Shift SLA analysis

channel_shift_report = (
    analysis
    .groupby(
        ["agent_shift", "channel"],
        dropna=False
    )
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum"),
        avg_response_minutes=("response_time_minutes", "mean"),
        median_response_minutes=("response_time_minutes", "median")
    )
    .reset_index()
)

channel_shift_report["breach_rate_pct"] = (
    channel_shift_report["breaches"]
    / channel_shift_report["tickets"]
    * 100
)

channel_shift_report["share_of_all_breaches_pct"] = (
    channel_shift_report["breaches"]
    / total_breaches
    * 100
)

channel_shift_report = channel_shift_report.sort_values(
    ["breaches", "breach_rate_pct"],
    ascending=[False, False]
).reset_index(drop=True)

print("Channel × Shift SLA performance:")
display(channel_shift_report)

print("\nTop 10 shift/channel combinations by breach volume:")
display(channel_shift_report.head(10))

print("Channel × Shift analysis completed.")

Channel × Shift SLA performance:

   agent_shift channel  tickets  breaches  sla_credit_exposure_inr  avg_response_minutes  median_response_minutes  breach_rate_pct  share_of_all_breaches_pct
0      Morning    chat     2830      1170                   409500            139.432155                      9.0        41.342756                  47.950820
1      Morning   email     2200       613                   214550            337.956364                    270.0        27.863636                  25.122951
2      Morning  social      627       200                    70000            191.236045                    105.0        31.897927                   8.196721
3          Day    chat     2019       190                    66500             13.375929                      4.0         9.410599                   7.786885
4          Day   email     1328       117                    40950            229.853163                    164.0         8.810241                   4.795082
5          Day   voice      873        47                    16450             45.375716                     33.0         5.383734                   1.926230
6          Day  social      448        39                    13650             99.410714                     65.5         8.705357                   1.598361
7      Morning   voice      607        35                    12250             47.140033                     36.0         5.766063                   1.434426
8        Night   email      119        15                     5250            250.924370                    177.0        12.605042                   0.614754
9        Night    chat      110         8                     2800              6.054545                      4.0         7.272727                   0.327869
10       Night  social       31         4                     1400            126.161290                    111.0        12.903226                   0.163934
11       Night   voice        8         2                      700             62.875000                     33.5        25.000000                   0.081967

Top 10 shift/channel combinations by breach volume:

  agent_shift channel  tickets  breaches  sla_credit_exposure_inr  avg_response_minutes  median_response_minutes  breach_rate_pct  share_of_all_breaches_pct
0     Morning    chat     2830      1170                   409500            139.432155                      9.0        41.342756                  47.950820
1     Morning   email     2200       613                   214550            337.956364                    270.0        27.863636                  25.122951
2     Morning  social      627       200                    70000            191.236045                    105.0        31.897927                   8.196721
3         Day    chat     2019       190                    66500             13.375929                      4.0         9.410599                   7.786885
4         Day   email     1328       117                    40950            229.853163                    164.0         8.810241                   4.795082
5         Day   voice      873        47                    16450             45.375716                     33.0         5.383734                   1.926230
6         Day  social      448        39                    13650             99.410714                     65.5         8.705357                   1.598361
7     Morning   voice      607        35                    12250             47.140033                     36.0         5.766063                   1.434426
8       Night   email      119        15                     5250            250.924370                    177.0        12.605042                   0.614754
9       Night    chat      110         8                     2800              6.054545                      4.0         7.272727                   0.327869

Channel × Shift analysis completed.

In [ ]:
# CELL 32 — Transfer count vs SLA breach analysis

transfer_report = (
    analysis
    .groupby("transfers", dropna=False)
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

transfer_report["breach_rate_pct"] = (
    transfer_report["breaches"]
    / transfer_report["tickets"]
    * 100
)

transfer_report = transfer_report.sort_values(
    "transfers"
).reset_index(drop=True)

print("Transfer count vs SLA performance:")
display(transfer_report)

# Compare no-transfer vs transferred tickets
analysis["has_transfer"] = (
    analysis["transfers"].fillna(0) > 0
)

transfer_comparison = (
    analysis
    .groupby("has_transfer")
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

transfer_comparison["breach_rate_pct"] = (
    transfer_comparison["breaches"]
    / transfer_comparison["tickets"]
    * 100
)

transfer_comparison["transfer_status"] = (
    transfer_comparison["has_transfer"]
    .map({
        False: "No transfer",
        True: "One or more transfers"
    })
)

print("\nNo-transfer vs transferred tickets:")
display(
    transfer_comparison[
        [
            "transfer_status",
            "tickets",
            "breaches",
            "breach_rate_pct",
            "sla_credit_exposure_inr"
        ]
    ]
)

print("Transfer analysis completed.")

Transfer count vs SLA performance:

   transfers  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0          0    10183      2229                   780150        21.889424
1          1      905       186                    65100        20.552486
2          2      112        25                     8750        22.321429

No-transfer vs transferred tickets:

         transfer_status  tickets  breaches  breach_rate_pct  sla_credit_exposure_inr
0            No transfer    10183      2229        21.889424                   780150
1  One or more transfers     1017       211        20.747296                    73850

Transfer analysis completed.

In [ ]:
# CELL 33 — Weekly Morning-shift trend

morning_weekly = (
    analysis[
        analysis["agent_shift"].astype(str).str.lower() == "morning"
    ]
    .groupby("week_start")
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

morning_weekly["breach_rate_pct"] = (
    morning_weekly["breaches"]
    / morning_weekly["tickets"]
    * 100
)

morning_weekly["week_start"] = pd.to_datetime(
    morning_weekly["week_start"]
)

morning_weekly = morning_weekly.sort_values(
    "week_start"
).reset_index(drop=True)

print("Morning-shift weekly performance:")
display(morning_weekly)

print("\nHighest Morning breach-volume weeks:")
display(
    morning_weekly
    .sort_values(
        ["breaches", "breach_rate_pct"],
        ascending=[False, False]
    )
    .head(10)
)

print("\nHighest Morning breach-rate weeks:")
display(
    morning_weekly
    .sort_values(
        ["breach_rate_pct", "breaches"],
        ascending=[False, False]
    )
    .head(10)
)

print("Morning-shift trend analysis completed.")

Morning-shift weekly performance:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0  2024-12-30       14         0                        0         0.000000
1  2025-01-06       20         0                        0         0.000000
2  2025-01-13       24         3                     1050        12.500000
3  2025-01-20       32         4                     1400        12.500000
4  2025-01-27       35         4                     1400        11.428571
5  2025-02-03       40         8                     2800        20.000000
6  2025-02-10       42         6                     2100        14.285714
7  2025-02-17       50         7                     2450        14.000000
8  2025-02-24       39         4                     1400        10.256410
9  2025-03-03       38         5                     1750        13.157895
10 2025-03-10       48         7                     2450        14.583333
11 2025-03-17       44         7                     2450        15.909091
12 2025-03-24       49         6                     2100        12.244898
13 2025-03-31       52         4                     1400         7.692308
14 2025-04-07       42         2                      700         4.761905
15 2025-04-14       34         5                     1750        14.705882
16 2025-04-21       53         6                     2100        11.320755
17 2025-04-28       61         4                     1400         6.557377
18 2025-05-05       47         0                        0         0.000000
19 2025-05-12       44         5                     1750        11.363636
20 2025-05-19       43         1                      350         2.325581
21 2025-05-26       44         4                     1400         9.090909
22 2025-06-02       42         4                     1400         9.523810
23 2025-06-09       31         4                     1400        12.903226
24 2025-06-16       55         1                      350         1.818182
25 2025-06-23       45         8                     2800        17.777778
26 2025-06-30       54        26                     9100        48.148148
27 2025-07-07       57        23                     8050        40.350877
28 2025-07-14       53        15                     5250        28.301887
29 2025-07-21       69        24                     8400        34.782609
30 2025-07-28       76        29                    10150        38.157895
31 2025-08-04       89        33                    11550        37.078652
32 2025-08-11      104        45                    15750        43.269231
33 2025-08-18       80        29                    10150        36.250000
34 2025-08-25      108        38                    13300        35.185185
35 2025-09-01       98        47                    16450        47.959184
36 2025-09-08      108        43                    15050        39.814815
37 2025-09-15       87        27                     9450        31.034483
38 2025-09-22       92        26                     9100        28.260870
39 2025-09-29       99        34                    11900        34.343434
40 2025-10-06      104        29                    10150        27.884615
41 2025-10-13      121        39                    13650        32.231405
42 2025-10-20      136        53                    18550        38.970588
43 2025-10-27      115        41                    14350        35.652174
44 2025-11-03      121        46                    16100        38.016529
45 2025-11-10       99        32                    11200        32.323232
46 2025-11-17      118        43                    15050        36.440678
47 2025-11-24      126        53                    18550        42.063492
48 2025-12-01      113        49                    17150        43.362832
49 2025-12-08      100        33                    11550        33.000000
50 2025-12-15      112        29                    10150        25.892857
51 2025-12-22      115        42                    14700        36.521739
52 2025-12-29      118        48                    16800        40.677966
53 2026-01-05      107        34                    11900        31.775701
54 2026-01-12      104        38                    13300        36.538462
55 2026-01-19      111        47                    16450        42.342342
56 2026-01-26       98        35                    12250        35.714286
57 2026-02-02      100        33                    11550        33.000000
58 2026-02-09       91        31                    10850        34.065934
59 2026-02-16      108        33                    11550        30.555556
60 2026-02-23       88        30                    10500        34.090909
61 2026-03-02       94        38                    13300        40.425532
62 2026-03-09       98        46                    16100        46.938776
63 2026-03-16      117        42                    14700        35.897436
64 2026-03-23       93        32                    11200        34.408602
65 2026-03-30       95        39                    13650        41.052632
66 2026-04-06       91        35                    12250        38.461538
67 2026-04-13       94        36                    12600        38.297872
68 2026-04-20      106        43                    15050        40.566038
69 2026-04-27      102        36                    12600        35.294118
70 2026-05-04       98        33                    11550        33.673469
71 2026-05-11       95        38                    13300        40.000000
72 2026-05-18      102        39                    13650        38.235294
73 2026-05-25       87        36                    12600        41.379310
74 2026-06-01       92        32                    11200        34.782609
75 2026-06-08      104        43                    15050        41.346154
76 2026-06-15      123        40                    14000        32.520325
77 2026-06-22      109        41                    14350        37.614679
78 2026-06-29       17         3                     1050        17.647059

Highest Morning breach-volume weeks:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
47 2025-11-24      126        53                    18550        42.063492
42 2025-10-20      136        53                    18550        38.970588
48 2025-12-01      113        49                    17150        43.362832
52 2025-12-29      118        48                    16800        40.677966
35 2025-09-01       98        47                    16450        47.959184
55 2026-01-19      111        47                    16450        42.342342
62 2026-03-09       98        46                    16100        46.938776
44 2025-11-03      121        46                    16100        38.016529
32 2025-08-11      104        45                    15750        43.269231
75 2026-06-08      104        43                    15050        41.346154

Highest Morning breach-rate weeks:

   week_start  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
26 2025-06-30       54        26                     9100        48.148148
35 2025-09-01       98        47                    16450        47.959184
62 2026-03-09       98        46                    16100        46.938776
48 2025-12-01      113        49                    17150        43.362832
32 2025-08-11      104        45                    15750        43.269231
55 2026-01-19      111        47                    16450        42.342342
47 2025-11-24      126        53                    18550        42.063492
73 2026-05-25       87        36                    12600        41.379310
75 2026-06-08      104        43                    15050        41.346154
65 2026-03-30       95        39                    13650        41.052632

Morning-shift trend analysis completed.

In [ ]:
# CELL 34 — June Indore reshuffle analysis

# Focus on Indore agents and compare June 2025 with surrounding periods.
indore_analysis = analysis[
    analysis["roster_site"].astype(str).str.lower() == "indore"
].copy()

indore_analysis["month"] = (
    indore_analysis["created_at_ist"]
    .dt.tz_localize(None)
    .dt.to_period("M")
    .astype(str)
)

indore_monthly = (
    indore_analysis
    .groupby("month")
    .agg(
        tickets=("ticket_id", "nunique"),
        breaches=("sla_breach", "sum"),
        sla_credit_exposure_inr=("sla_credit_exposure_inr", "sum")
    )
    .reset_index()
)

indore_monthly["breach_rate_pct"] = (
    indore_monthly["breaches"]
    / indore_monthly["tickets"]
    * 100
)

print("Indore monthly SLA performance:")
display(indore_monthly)

# Show the months around the June 2025 reshuffle
june_window = indore_monthly[
    indore_monthly["month"].isin([
        "2025-04",
        "2025-05",
        "2025-06",
        "2025-07",
        "2025-08"
    ])
].copy()

print("\nIndore performance around June 2025:")
display(june_window)

print(
    "\nThis is a descriptive before/after comparison, "
    "not proof that the reshuffle caused a change."
)

print("Indore reshuffle analysis completed.")

Indore monthly SLA performance:

      month  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
0   2025-01       75         9                     3150        12.000000
1   2025-02      103        11                     3850        10.679612
2   2025-03       97        11                     3850        11.340206
3   2025-04      132        12                     4200         9.090909
4   2025-05      123        12                     4200         9.756098
5   2025-06      111        10                     3500         9.009009
6   2025-07      109        42                    14700        38.532110
7   2025-08      177        63                    22050        35.593220
8   2025-09      169        53                    18550        31.360947
9   2025-10      212        75                    26250        35.377358
10  2025-11      207        57                    19950        27.536232
11  2025-12      198        62                    21700        31.313131
12  2026-01      197        58                    20300        29.441624
13  2026-02      142        40                    14000        28.169014
14  2026-03      191        71                    24850        37.172775
15  2026-04      159        50                    17500        31.446541
16  2026-05      153        50                    17500        32.679739
17  2026-06      190        65                    22750        34.210526

Indore performance around June 2025:

     month  tickets  breaches  sla_credit_exposure_inr  breach_rate_pct
3  2025-04      132        12                     4200         9.090909
4  2025-05      123        12                     4200         9.756098
5  2025-06      111        10                     3500         9.009009
6  2025-07      109        42                    14700        38.532110
7  2025-08      177        63                    22050        35.593220

This is a descriptive before/after comparison, not proof that the reshuffle caused a change.
Indore reshuffle analysis completed.

In [ ]:
# CELL 35 — Create controlled sample for AI-assisted theme analysis

# Work from the deterministic analysis dataset
ai_source = analysis.copy()

# Select useful text fields
ai_source["customer_message"] = (
    ai_source["customer_message"]
    .fillna("")
    .astype(str)
    .str.strip()
)

ai_source["agent_notes"] = (
    ai_source["agent_notes"]
    .fillna("")
    .astype(str)
    .str.strip()
)

# Combine text for AI interpretation
ai_source["text_for_ai"] = (
    "CUSTOMER MESSAGE:\n"
    + ai_source["customer_message"]
    + "\n\nAGENT NOTES:\n"
    + ai_source["agent_notes"]
)

# Remove completely empty text
ai_source = ai_source[
    ai_source["text_for_ai"].str.len() > len(
        "CUSTOMER MESSAGE:\n\nAGENT NOTES:\n"
    )
].copy()

# Create a representative sample by channel and SLA status
SAMPLE_SIZE = 200

group_columns = ["channel", "sla_breach"]

available_groups = (
    ai_source
    .groupby(group_columns)
    .size()
    .reset_index(name="available")
)

print("Available AI-analysis groups:")
display(available_groups)

# Allocate approximately equal representation across channel/status groups
group_count = len(available_groups)

base_per_group = SAMPLE_SIZE // group_count
remainder = SAMPLE_SIZE % group_count

sample_parts = []

for group_index, row in available_groups.iterrows():

    channel_value = row["channel"]
    breach_value = row["sla_breach"]

    group_data = ai_source[
        (ai_source["channel"] == channel_value) &
        (ai_source["sla_breach"] == breach_value)
    ]

    target_n = base_per_group

    if group_index < remainder:
        target_n += 1

    target_n = min(target_n, len(group_data))

    if target_n > 0:
        sample_parts.append(
            group_data.sample(
                n=target_n,
                random_state=42
            )
        )

ai_sample = (
    pd.concat(sample_parts, ignore_index=True)
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

print("\nAI sample created.")
print(f"Requested sample size : {SAMPLE_SIZE}")
print(f"Actual sample size    : {len(ai_sample):,}")

print("\nSample by channel and SLA status:")
display(
    ai_sample
    .groupby(["channel", "sla_breach"])
    .size()
    .reset_index(name="tickets")
)

print("\nSample columns:")
print(
    [
        "ticket_id",
        "channel",
        "sla_breach",
        "agent_shift",
        "roster_agent_name",
        "customer_message",
        "agent_notes"
    ]
)

print("\nControlled AI-analysis sample is ready.")

Available AI-analysis groups:

  channel  sla_breach  available
0    chat       False       3591
1    chat        True       1368
2   email       False       2902
3   email        True        745
4  social       False        863
5  social        True        243
6   voice       False       1404
7   voice        True         84

AI sample created.
Requested sample size : 200
Actual sample size    : 200

Sample by channel and SLA status:

  channel  sla_breach  tickets
0    chat       False       25
1    chat        True       25
2   email       False       25
3   email        True       25
4  social       False       25
5  social        True       25
6   voice       False       25
7   voice        True       25

Sample columns:
['ticket_id', 'channel', 'sla_breach', 'agent_shift', 'roster_agent_name', 'customer_message', 'agent_notes']

Controlled AI-analysis sample is ready.

In [ ]:
# CELL 36 — Gemini API setup

!pip -q install -U google-genai

from google import genai
from getpass import getpass
import json
import time
import random
import pandas as pd
import numpy as np

GEMINI_API_KEY = getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=GEMINI_API_KEY)

print("Gemini API client configured successfully.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 29.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 kB 20.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.60.0 which is incompatible.
Enter your Gemini API key: ··········
Gemini API client configured successfully.

In [ ]:
# CELL 37 — AI classification schema

PRIMARY_ISSUES = [
    "Delivery & Shipping",
    "Billing & Payments",
    "Connectivity",
    "Returns & Refunds",
    "Charging & Battery",
    "App & Firmware",
    "Audio Quality",
    "Product Enquiry",
    "Warranty & Repair",
    "Account & Login",
    "Other"
]

COMPLEXITY_LEVELS = [
    "Low",
    "Medium",
    "High"
]

OPERATIONAL_FACTORS = [
    "Queue Backlog",
    "Customer Information Missing",
    "Technical Troubleshooting",
    "Cross-Team Dependency",
    "Transfer / Handoff",
    "Policy / Approval",
    "Delivery / Logistics Dependency",
    "No Clear Operational Factor",
    "Other"
]

BREACH_DRIVER_VALUES = [
    "Yes",
    "No",
    "Unclear"
]

print("Classification schema loaded.")

Classification schema loaded.

In [ ]:
# CELL 38 — Prompt builder and JSON validation

def build_classification_prompt(customer_message, agent_notes):
    return f"""
You are analyzing a customer-support ticket for an operations team.

Classify the ticket using ONLY the allowed values below.

Return ONLY a JSON object.
Do not include markdown.
Do not include explanations.

JSON schema:
{{
  "primary_issue": "...",
  "complexity": "...",
  "operational_factor": "...",
  "likely_breach_driver": "..."
}}

Allowed primary_issue:
{", ".join(PRIMARY_ISSUES)}

Allowed complexity:
{", ".join(COMPLEXITY_LEVELS)}

Allowed operational_factor:
{", ".join(OPERATIONAL_FACTORS)}

Allowed likely_breach_driver:
{", ".join(BREACH_DRIVER_VALUES)}

Important:
- Do not assume that a ticket caused an SLA breach merely because it actually breached.
- Use the ticket text and agent notes only.
- If the operational cause cannot reasonably be inferred, use "Unclear" or "No Clear Operational Factor".

Customer message:
{customer_message}

Agent notes:
{agent_notes}
"""


def validate_classification(result):
    if not isinstance(result, dict):
        return False, "Output is not a JSON object"

    required = [
        "primary_issue",
        "complexity",
        "operational_factor",
        "likely_breach_driver"
    ]

    missing = [x for x in required if x not in result]

    if missing:
        return False, f"Missing fields: {missing}"

    if result["primary_issue"] not in PRIMARY_ISSUES:
        return False, "Invalid primary_issue"

    if result["complexity"] not in COMPLEXITY_LEVELS:
        return False, "Invalid complexity"

    if result["operational_factor"] not in OPERATIONAL_FACTORS:
        return False, "Invalid operational_factor"

    if result["likely_breach_driver"] not in BREACH_DRIVER_VALUES:
        return False, "Invalid likely_breach_driver"

    return True, "Valid"

In [ ]:
# CELL 39 — Gemini ticket classifier

def classify_ticket_gemini(
    customer_message,
    agent_notes,
    max_retries=2
):
    prompt = build_classification_prompt(
        customer_message,
        agent_notes
    )

    for attempt in range(max_retries + 1):

        try:
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.1,
                    "response_mime_type": "application/json"
                }
            )

            raw_text = response.text.strip()

            result = json.loads(raw_text)

            valid, validation_message = validate_classification(result)

            if valid:
                return {
                    "success": True,
                    "result": result,
                    "error": None,
                    "attempts": attempt + 1
                }

            error = validation_message

        except Exception as e:
            error = str(e)

        if attempt < max_retries:
            time.sleep((2 ** attempt) + random.uniform(0, 1))

    return {
        "success": False,
        "result": None,
        "error": error,
        "attempts": max_retries + 1
    }

print("Gemini classifier ready.")

Gemini classifier ready.

In [ ]:
# CELL 40 — Single-ticket Gemini test

# Use the analysis dataset, which contains the authoritative SLA result
test_ticket = analysis[
    analysis["ticket_id"] == "TK-241159"
].iloc[0]

test_result = classify_ticket_gemini(
    test_ticket["customer_message"],
    test_ticket["agent_notes"]
)

print("Ticket:", test_ticket["ticket_id"])
print("Actual SLA breach:", test_ticket["sla_breach"])

print("\nAI result:")

if test_result["success"]:
    print(json.dumps(
        test_result["result"],
        indent=2
    ))
else:
    print("FAILED")
    print(test_result["error"])

print("\nAttempts:", test_result["attempts"])

Ticket: TK-241159
Actual SLA breach: True

AI result:
{
  "primary_issue": "Delivery & Shipping",
  "complexity": "Medium",
  "operational_factor": "Delivery / Logistics Dependency",
  "likely_breach_driver": "Unclear"
}

Attempts: 1

In [ ]:
# CELL 41 — Build controlled AI evaluation sample

# Inspect the columns we actually have
print("ai_sample columns:")
print(ai_sample.columns.tolist())

print("\nanalysis columns:")
print(analysis.columns.tolist())

# ---------------------------------------------------------
# 1. Get the authoritative SLA result from analysis
# ---------------------------------------------------------

sla_lookup = (
    analysis[
        ["ticket_id", "sla_breach"]
    ]
    .drop_duplicates("ticket_id")
    .copy()
)

# ---------------------------------------------------------
# 2. Start with the AI sample
# ---------------------------------------------------------

evaluation_pool = ai_sample.copy()

# Remove any existing SLA column from the sample
# so the merge cannot create _x / _y duplicates
for col in [
    "actual_sla_breach",
    "sla_breach",
    "sla_breach_x",
    "sla_breach_y"
]:
    if col in evaluation_pool.columns:
        evaluation_pool = evaluation_pool.drop(columns=[col])

# ---------------------------------------------------------
# 3. Add authoritative SLA result
# ---------------------------------------------------------

evaluation_pool = evaluation_pool.merge(
    sla_lookup,
    on="ticket_id",
    how="left"
)

# Standardize the column name
evaluation_pool["actual_sla_breach"] = (
    evaluation_pool["sla_breach"]
    .astype("boolean")
)

evaluation_pool = evaluation_pool.drop(
    columns=["sla_breach"]
)

# ---------------------------------------------------------
# 4. Verify
# ---------------------------------------------------------

print("\nEvaluation pool:")
print(f"Tickets: {len(evaluation_pool):,}")
print(
    "Missing SLA labels:",
    evaluation_pool["actual_sla_breach"].isna().sum()
)

# ---------------------------------------------------------
# 5. Create balanced evaluation sample
# ---------------------------------------------------------

evaluation_sample = (
    evaluation_pool
    .groupby(
        ["channel", "actual_sla_breach"],
        group_keys=False
    )
    .sample(
        n=5,
        random_state=42
    )
    .reset_index(drop=True)
)

print(
    f"\nFinal AI evaluation sample: "
    f"{len(evaluation_sample):,} tickets"
)

display(
    evaluation_sample[
        [
            "ticket_id",
            "channel",
            "actual_sla_breach"
        ]
    ]
)

print("\nDistribution:")
display(
    evaluation_sample
    .groupby(
        ["channel", "actual_sla_breach"]
    )
    .size()
    .reset_index(name="count")
)

ai_sample columns:
['ticket_id', 'created_at', 'first_response_at', 'resolved_at', 'status', 'channel', 'customer_id', 'order_id', 'product_sku', 'category', 'priority', 'assigned_team', 'agent_id', 'transfers', 'csat_score', 'refund_amount_inr', 'refund_reason_code', 'replacement_issued', 'customer_message', 'agent_notes', 'source_system', 'created_at_ist', 'first_response_at_ist', 'resolved_at_ist', 'response_time_minutes', 'sla_target_minutes', 'sla_breach', 'sla_status', 'sla_credit_exposure_inr', '_created_date_ist', 'roster_agent_name', 'roster_site', 'roster_team', 'roster_shift', 'roster_tier', 'from_date', 'to_date_filled', 'agent_shift', 'operational_shift', 'week_start', 'has_transfer', 'text_for_ai']

analysis columns:
['ticket_id', 'created_at', 'first_response_at', 'resolved_at', 'status', 'channel', 'customer_id', 'order_id', 'product_sku', 'category', 'priority', 'assigned_team', 'agent_id', 'transfers', 'csat_score', 'refund_amount_inr', 'refund_reason_code', 'replacement_issued', 'customer_message', 'agent_notes', 'source_system', 'created_at_ist', 'first_response_at_ist', 'resolved_at_ist', 'response_time_minutes', 'sla_target_minutes', 'sla_breach', 'sla_status', 'sla_credit_exposure_inr', '_created_date_ist', 'roster_agent_name', 'roster_site', 'roster_team', 'roster_shift', 'roster_tier', 'from_date', 'to_date_filled', 'agent_shift', 'operational_shift', 'week_start', 'has_transfer']

Evaluation pool:
Tickets: 200
Missing SLA labels: 0

Final AI evaluation sample: 40 tickets

    ticket_id channel  actual_sla_breach
0   TK-253864    chat              False
1   TK-253891    chat              False
2   TK-249930    chat              False
3   TK-252498    chat              False
4   TK-246309    chat              False
5   TK-248325    chat               True
6   TK-245900    chat               True
7   TK-242785    chat               True
8   TK-248223    chat               True
9   TK-245887    chat               True
10  TK-243010   email              False
11  TK-248628   email              False
12  TK-251391   email              False
13  TK-243743   email              False
14  TK-246440   email              False
15  TK-248611   email               True
16  TK-244205   email               True
17  TK-244720   email               True
18  TK-242365   email               True
19  TK-247485   email               True
20  TK-249284  social              False
21  TK-251573  social              False
22  TK-253378  social              False
23  TK-247318  social              False
24  TK-243126  social              False
25  TK-249651  social               True
26  TK-243279  social               True
27  TK-249363  social               True
28  TK-250559  social               True
29  TK-240872  social               True
30  TK-248698   voice              False
31  TK-244925   voice              False
32  TK-240704   voice              False
33  TK-251370   voice              False
34  TK-251737   voice              False
35  TK-241955   voice               True
36  TK-241546   voice               True
37  TK-244147   voice               True
38  TK-248501   voice               True
39  TK-246877   voice               True

Distribution:

  channel  actual_sla_breach  count
0    chat              False      5
1    chat               True      5
2   email              False      5
3   email               True      5
4  social              False      5
5  social               True      5
6   voice              False      5
7   voice               True      5

In [ ]:
# CELL 42 — Run Gemini classification on evaluation sample

ai_evaluation_results = []

for i, row in evaluation_sample.iterrows():

    result = classify_ticket_gemini(
        row["customer_message"],
        row["agent_notes"]
    )

    ai_evaluation_results.append({
        "ticket_id": row["ticket_id"],
        "channel": row["channel"],
        "actual_sla_breach": row["actual_sla_breach"],
        "ai_success": result["success"],
        "ai_result": result["result"],
        "ai_error": result["error"],
        "attempts": result["attempts"]
    })

    print(
        f"[{i+1}/{len(evaluation_sample)}] "
        f"{row['ticket_id']} → "
        f"{'SUCCESS' if result['success'] else 'FAILED'}"
    )

    # Small delay between requests
    time.sleep(1)

ai_evaluation_df = pd.DataFrame(ai_evaluation_results)

print("\nEvaluation completed.")

[1/40] TK-253864 → SUCCESS
[2/40] TK-253891 → FAILED
[3/40] TK-249930 → SUCCESS
[4/40] TK-252498 → FAILED
[5/40] TK-246309 → FAILED
[6/40] TK-248325 → FAILED
[7/40] TK-245900 → SUCCESS
[8/40] TK-242785 → SUCCESS
[9/40] TK-248223 → SUCCESS
[10/40] TK-245887 → SUCCESS
[11/40] TK-243010 → SUCCESS
[12/40] TK-248628 → SUCCESS
[13/40] TK-251391 → FAILED
[14/40] TK-243743 → FAILED
[15/40] TK-246440 → FAILED
[16/40] TK-248611 → FAILED
[17/40] TK-244205 → FAILED
[18/40] TK-244720 → SUCCESS
[19/40] TK-242365 → SUCCESS
[20/40] TK-247485 → SUCCESS
[21/40] TK-249284 → SUCCESS
[22/40] TK-251573 → SUCCESS
[23/40] TK-253378 → SUCCESS
[24/40] TK-247318 → FAILED
[25/40] TK-243126 → FAILED
[26/40] TK-249651 → FAILED
[27/40] TK-243279 → FAILED
[28/40] TK-249363 → FAILED
[29/40] TK-250559 → FAILED
[30/40] TK-240872 → FAILED
[31/40] TK-248698 → FAILED
[32/40] TK-244925 → FAILED
[33/40] TK-240704 → FAILED
[34/40] TK-251370 → FAILED
[35/40] TK-251737 → FAILED
[36/40] TK-241955 → FAILED
[37/40] TK-241546 → FAILED
[38/40] TK-244147 → FAILED
[39/40] TK-248501 → FAILED
[40/40] TK-246877 → FAILED

Evaluation completed.

In [ ]:
# CELL 43 — Diagnose Gemini evaluation failures

failed_ai = ai_evaluation_df[
    ~ai_evaluation_df["ai_success"]
].copy()

successful_ai = ai_evaluation_df[
    ai_evaluation_df["ai_success"]
].copy()

print(f"Total evaluation tickets: {len(ai_evaluation_df)}")
print(f"Successful: {len(successful_ai)}")
print(f"Failed: {len(failed_ai)}")

print("\nFailure reasons:")
display(
    failed_ai["ai_error"]
    .fillna("UNKNOWN")
    .value_counts()
    .reset_index()
    .rename(
        columns={
            "index": "error",
            "ai_error": "count"
        }
    )
)

print("\nFirst 10 failures:")
display(
    failed_ai[
        [
            "ticket_id",
            "channel",
            "actual_sla_breach",
            "ai_error",
            "attempts"
        ]
    ].head(10)
)

Total evaluation tickets: 40
Successful: 14
Failed: 26

Failure reasons:

                                                count  count
0   503 UNAVAILABLE. {'error': {'code': 503, 'mess...      1
1   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
2   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
3   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
4   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
5   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
6   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
7   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
8   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
9   429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
10  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
11  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
12  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
13  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
14  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
15  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
16  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
17  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
18  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
19  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
20  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
21  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
22  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
23  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
24  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1
25  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...      1

First 10 failures:

    ticket_id channel  actual_sla_breach                                           ai_error  attempts
1   TK-253891    chat              False  503 UNAVAILABLE. {'error': {'code': 503, 'mess...         3
3   TK-252498    chat              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
4   TK-246309    chat              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
5   TK-248325    chat               True  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
12  TK-251391   email              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
13  TK-243743   email              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
14  TK-246440   email              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
15  TK-248611   email               True  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
16  TK-244205   email               True  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3
23  TK-247318  social              False  429 RESOURCE_EXHAUSTED. {'error': {'code': 429...         3

In [ ]:
# CELL 44 — Extract successful Gemini classifications

successful_ai = ai_evaluation_df[
    ai_evaluation_df["ai_success"]
].copy()

print(f"Successful AI classifications: {len(successful_ai)}")

if len(successful_ai) > 0:

    ai_expanded = pd.json_normalize(
        successful_ai["ai_result"]
    )

    ai_expanded.index = successful_ai.index

    successful_ai = pd.concat(
        [
            successful_ai.drop(columns=["ai_result"]),
            ai_expanded
        ],
        axis=1
    )

    print("\nValidated AI classifications:")

    display(
        successful_ai[
            [
                "ticket_id",
                "channel",
                "actual_sla_breach",
                "primary_issue",
                "complexity",
                "operational_factor",
                "likely_breach_driver"
            ]
        ]
    )
else:
    print("No successful AI classifications.")

Successful AI classifications: 14

Validated AI classifications:

    ticket_id channel  actual_sla_breach        primary_issue complexity               operational_factor likely_breach_driver
0   TK-253864    chat              False   Charging & Battery     Medium        Technical Troubleshooting              Unclear
2   TK-249930    chat              False    Returns & Refunds        Low      No Clear Operational Factor                   No
6   TK-245900    chat               True   Billing & Payments        Low        Technical Troubleshooting                  Yes
7   TK-242785    chat               True  Delivery & Shipping     Medium  Delivery / Logistics Dependency                  Yes
8   TK-248223    chat               True         Connectivity     Medium        Technical Troubleshooting                   No
9   TK-245887    chat               True        Audio Quality     Medium  Delivery / Logistics Dependency                   No
10  TK-243010   email              False      Account & Login        Low        Technical Troubleshooting                   No
11  TK-248628   email              False      Product Enquiry        Low      No Clear Operational Factor                   No
17  TK-244720   email               True  Delivery & Shipping        Low  Delivery / Logistics Dependency              Unclear
18  TK-242365   email               True   Charging & Battery     Medium        Technical Troubleshooting              Unclear
19  TK-247485   email               True  Delivery & Shipping        Low  Delivery / Logistics Dependency                   No
20  TK-249284  social              False    Warranty & Repair        Low            Cross-Team Dependency              Unclear
21  TK-251573  social              False      Product Enquiry        Low      No Clear Operational Factor                   No
22  TK-253378  social              False   Billing & Payments        Low      No Clear Operational Factor                   No

In [ ]:
# CELL 45 — AI operational theme summary

if len(successful_ai) > 0:

    print("PRIMARY ISSUE")
    print("=" * 40)

    display(
        successful_ai["primary_issue"]
        .value_counts()
        .rename_axis("primary_issue")
        .reset_index(name="tickets")
    )

    print("\nOPERATIONAL FACTORS")
    print("=" * 40)

    display(
        successful_ai["operational_factor"]
        .value_counts()
        .rename_axis("operational_factor")
        .reset_index(name="tickets")
    )

    print("\nCOMPLEXITY")
    print("=" * 40)

    display(
        successful_ai["complexity"]
        .value_counts()
        .rename_axis("complexity")
        .reset_index(name="tickets")
    )

else:
    print("No successful AI results.")

PRIMARY ISSUE
========================================

         primary_issue  tickets
0  Delivery & Shipping        3
1   Charging & Battery        2
2   Billing & Payments        2
3      Product Enquiry        2
4    Returns & Refunds        1
5         Connectivity        1
6        Audio Quality        1
7      Account & Login        1
8    Warranty & Repair        1

OPERATIONAL FACTORS
========================================

                operational_factor  tickets
0        Technical Troubleshooting        5
1      No Clear Operational Factor        4
2  Delivery / Logistics Dependency        4
3            Cross-Team Dependency        1

COMPLEXITY
========================================

  complexity  tickets
0        Low        9
1     Medium        5

In [ ]:
# CELL 46 — Compare AI themes with observed SLA status

if len(successful_ai) > 0:

    print("AI THEMES BY OBSERVED SLA STATUS")

    theme_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "primary_issue"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(theme_by_breach)

    print("\nOPERATIONAL FACTORS BY OBSERVED SLA STATUS")

    factor_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "operational_factor"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(factor_by_breach)

    print("\nLIKELY BREACH DRIVER LABELS")

    driver_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "likely_breach_driver"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(driver_by_breach)

else:
    print("No successful AI classifications available.")

AI THEMES BY OBSERVED SLA STATUS

    actual_sla_breach        primary_issue  tickets
10               True  Delivery & Shipping        3
6                True        Audio Quality        1
7                True   Billing & Payments        1
8                True   Charging & Battery        1
9                True         Connectivity        1
3               False      Product Enquiry        2
0               False      Account & Login        1
1               False   Billing & Payments        1
2               False   Charging & Battery        1
4               False    Returns & Refunds        1
5               False    Warranty & Repair        1

OPERATIONAL FACTORS BY OBSERVED SLA STATUS

   actual_sla_breach               operational_factor  tickets
3               True  Delivery / Logistics Dependency        4
4               True        Technical Troubleshooting        3
1              False      No Clear Operational Factor        4
2              False        Technical Troubleshooting        2
0              False            Cross-Team Dependency        1

LIKELY BREACH DRIVER LABELS

   actual_sla_breach likely_breach_driver  tickets
2               True                   No        3
3               True              Unclear        2
4               True                  Yes        2
0              False                   No        5
1              False              Unclear        2

In [ ]:
# CELL 46 — Compare AI themes with observed SLA status

if len(successful_ai) > 0:

    print("AI THEMES BY OBSERVED SLA STATUS")

    theme_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "primary_issue"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(theme_by_breach)

    print("\nOPERATIONAL FACTORS BY OBSERVED SLA STATUS")

    factor_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "operational_factor"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(factor_by_breach)

    print("\nLIKELY BREACH DRIVER LABELS")

    driver_by_breach = (
        successful_ai
        .groupby(["actual_sla_breach", "likely_breach_driver"])
        .size()
        .reset_index(name="tickets")
        .sort_values(["actual_sla_breach", "tickets"], ascending=[False, False])
    )

    display(driver_by_breach)

else:
    print("No successful AI classifications available.")

AI THEMES BY OBSERVED SLA STATUS

    actual_sla_breach        primary_issue  tickets
10               True  Delivery & Shipping        3
6                True        Audio Quality        1
7                True   Billing & Payments        1
8                True   Charging & Battery        1
9                True         Connectivity        1
3               False      Product Enquiry        2
0               False      Account & Login        1
1               False   Billing & Payments        1
2               False   Charging & Battery        1
4               False    Returns & Refunds        1
5               False    Warranty & Repair        1

OPERATIONAL FACTORS BY OBSERVED SLA STATUS

   actual_sla_breach               operational_factor  tickets
3               True  Delivery / Logistics Dependency        4
4               True        Technical Troubleshooting        3
1              False      No Clear Operational Factor        4
2              False        Technical Troubleshooting        2
0              False            Cross-Team Dependency        1

LIKELY BREACH DRIVER LABELS

   actual_sla_breach likely_breach_driver  tickets
2               True                   No        3
3               True              Unclear        2
4               True                  Yes        2
0              False                   No        5
1              False              Unclear        2

In [ ]:
# CELL 47 — Final AI evidence summary

if len(successful_ai) > 0:

    total_ai = len(successful_ai)
    ai_breaches = successful_ai["actual_sla_breach"].sum()
    ai_passes = total_ai - ai_breaches

    print("AI-ASSISTED ANALYSIS SUMMARY")
    print("=" * 50)
    print(f"Validated AI classifications : {total_ai}")
    print(f"Observed SLA breaches        : {ai_breaches}")
    print(f"Observed SLA passes          : {ai_passes}")
    print()

    print("Top primary issues:")
    display(
        successful_ai["primary_issue"]
        .value_counts()
        .head(5)
        .rename_axis("primary_issue")
        .reset_index(name="tickets")
    )

    print("\nTop operational factors:")
    display(
        successful_ai["operational_factor"]
        .value_counts()
        .head(5)
        .rename_axis("operational_factor")
        .reset_index(name="tickets")
    )

    print("\nImportant interpretation:")
    print(
        "These AI classifications describe themes in the reviewed sample. "
        "They do not establish that an issue or operational factor caused an SLA breach."
    )

else:
    print("No successful AI classifications available.")

AI-ASSISTED ANALYSIS SUMMARY
==================================================
Validated AI classifications : 14
Observed SLA breaches        : 7
Observed SLA passes          : 7

Top primary issues:

         primary_issue  tickets
0  Delivery & Shipping        3
1   Charging & Battery        2
2   Billing & Payments        2
3      Product Enquiry        2
4    Returns & Refunds        1

Top operational factors:

                operational_factor  tickets
0        Technical Troubleshooting        5
1      No Clear Operational Factor        4
2  Delivery / Logistics Dependency        4
3            Cross-Team Dependency        1

Important interpretation:
These AI classifications describe themes in the reviewed sample. They do not establish that an issue or operational factor caused an SLA breach.

In [ ]:
# CELL 48 — Final Evidence Pack for Business Reporting

print("=" * 70)
print("VIREO AUDIO — SUPPORT SLA FINAL EVIDENCE PACK")
print("=" * 70)

# ============================================================
# 1. CORE SLA METRICS
# ============================================================

total_tickets = len(analysis)

total_breaches = int(
    analysis["sla_breach"].sum()
)

total_passes = total_tickets - total_breaches

breach_rate = (
    total_breaches / total_tickets * 100
)

credit_exposure = (
    total_breaches * 350
)

print("\nCORE SLA PERFORMANCE")
print("-" * 70)

print(f"Unique tickets analyzed : {total_tickets:,}")
print(f"SLA passes              : {total_passes:,}")
print(f"SLA breaches            : {total_breaches:,}")
print(f"SLA breach rate         : {breach_rate:.2f}%")
print(f"Credit exposure         : ₹{credit_exposure:,.0f}")


# ============================================================
# 2. MORNING SHIFT ANALYSIS
# ============================================================

morning = analysis[
    analysis["operational_shift"] == "Morning"
].copy()

morning_tickets = len(morning)

morning_breaches = int(
    morning["sla_breach"].sum()
)

morning_breach_rate = (
    morning_breaches / morning_tickets * 100
)

morning_share_of_breaches = (
    morning_breaches / total_breaches * 100
)

morning_credit_exposure = (
    morning_breaches * 350
)

print("\nMORNING SHIFT")
print("-" * 70)

print(f"Morning tickets         : {morning_tickets:,}")
print(f"Morning breaches        : {morning_breaches:,}")
print(f"Morning breach rate     : {morning_breach_rate:.2f}%")
print(f"Share of all breaches   : {morning_share_of_breaches:.2f}%")
print(f"Credit exposure         : ₹{morning_credit_exposure:,.0f}")


# ============================================================
# 3. AGENT-LEVEL ANALYSIS
# ============================================================

agent_summary = (
    analysis
    .groupby(
        [
            "agent_id",
            "roster_agent_name",
            "operational_shift"
        ]
    )
    .agg(
        tickets=("ticket_id", "count"),
        breaches=("sla_breach", "sum")
    )
    .reset_index()
)

agent_summary["breach_rate"] = (
    agent_summary["breaches"]
    / agent_summary["tickets"]
    * 100
)

agent_summary["credit_exposure_inr"] = (
    agent_summary["breaches"] * 350
)


# ============================================================
# 4. TOP AGENT BY BREACH VOLUME
# ============================================================

top_volume_agent = (
    agent_summary
    .sort_values(
        ["breaches", "tickets"],
        ascending=[False, False]
    )
    .iloc[0]
)

print("\nTOP AGENT BY BREACH VOLUME")
print("-" * 70)

print(
    f"Agent                   : "
    f"{top_volume_agent['roster_agent_name']}"
)

print(
    f"Agent ID                : "
    f"{top_volume_agent['agent_id']}"
)

print(
    f"Shift                   : "
    f"{top_volume_agent['operational_shift']}"
)

print(
    f"Tickets                 : "
    f"{int(top_volume_agent['tickets']):,}"
)

print(
    f"Breaches                : "
    f"{int(top_volume_agent['breaches']):,}"
)

print(
    f"Breach rate             : "
    f"{top_volume_agent['breach_rate']:.2f}%"
)

print(
    f"Credit exposure         : "
    f"₹{int(top_volume_agent['credit_exposure_inr']):,}"
)


# ============================================================
# 5. TOP AGENT BY BREACH RATE
# ============================================================

top_rate_agent = (
    agent_summary[
        agent_summary["tickets"] >= 100
    ]
    .sort_values(
        ["breach_rate", "breaches"],
        ascending=[False, False]
    )
    .iloc[0]
)

print("\nTOP AGENT BY BREACH RATE")
print("-" * 70)

print(
    f"Agent                   : "
    f"{top_rate_agent['roster_agent_name']}"
)

print(
    f"Agent ID                : "
    f"{top_rate_agent['agent_id']}"
)

print(
    f"Shift                   : "
    f"{top_rate_agent['operational_shift']}"
)

print(
    f"Tickets                 : "
    f"{int(top_rate_agent['tickets']):,}"
)

print(
    f"Breaches                : "
    f"{int(top_rate_agent['breaches']):,}"
)

print(
    f"Breach rate             : "
    f"{top_rate_agent['breach_rate']:.2f}%"
)


# ============================================================
# 6. AI-ASSISTED EVIDENCE
# ============================================================

print("\nAI-ASSISTED TICKET ANALYSIS")
print("-" * 70)

if len(successful_ai) > 0:

    valid_ai_classifications = len(successful_ai)

    ai_breaches = int(
        successful_ai["actual_sla_breach"].sum()
    )

    ai_passes = (
        valid_ai_classifications - ai_breaches
    )

    top_issue_counts = (
        successful_ai["primary_issue"]
        .value_counts()
    )

    top_factor_counts = (
        successful_ai["operational_factor"]
        .value_counts()
    )

    top_issue_name = top_issue_counts.index[0]
    top_issue_count = int(top_issue_counts.iloc[0])

    top_factor_name = top_factor_counts.index[0]
    top_factor_count = int(top_factor_counts.iloc[0])

    print(
        f"Valid AI classifications : "
        f"{valid_ai_classifications}"
    )

    print(
        f"Observed breaches        : "
        f"{ai_breaches}"
    )

    print(
        f"Observed passes          : "
        f"{ai_passes}"
    )

    print(
        f"Top issue theme          : "
        f"{top_issue_name} ({top_issue_count} tickets)"
    )

    print(
        f"Top operational factor   : "
        f"{top_factor_name} ({top_factor_count} tickets)"
    )

else:

    print("No successful AI classifications available.")


# ============================================================
# 7. RECONCILIATION CHECK
# ============================================================

expected_credit_exposure = (
    total_breaches * 350
)

reconciliation_passed = (
    credit_exposure == expected_credit_exposure
)

print("\nRECONCILIATION CHECK")
print("-" * 70)

print(
    f"Calculated exposure     : "
    f"₹{credit_exposure:,.0f}"
)

print(
    f"Expected exposure       : "
    f"₹{expected_credit_exposure:,.0f}"
)

print(
    f"Reconciliation passed   : "
    f"{reconciliation_passed}"
)


# ============================================================
# 8. FINAL INTERPRETATION
# ============================================================

print("\nFINAL INTERPRETATION")
print("-" * 70)

print(
    "1. Morning shift has the largest concentration of observed SLA breaches."
)

print(
    "2. Breach volume and breach rate should be reviewed separately."
)

print(
    "3. Agent-level results should be interpreted with ticket volume context."
)

print(
    "4. AI classifications identify descriptive ticket themes, "
    "not proven causal drivers."
)

print(
    "5. SLA calculations, breach flags, roster joins and financial "
    "exposure are deterministic and reproducible."
)

print(
    "6. The AI layer is an assistive analysis component rather than "
    "the source of truth for SLA measurement."
)

print("\n" + "=" * 70)
print("FINAL EVIDENCE PACK COMPLETE")
print("=" * 70)

======================================================================
VIREO AUDIO — SUPPORT SLA FINAL EVIDENCE PACK
======================================================================

CORE SLA PERFORMANCE
----------------------------------------------------------------------
Unique tickets analyzed : 11,200
SLA passes              : 8,760
SLA breaches            : 2,440
SLA breach rate         : 21.79%
Credit exposure         : ₹854,000

MORNING SHIFT
----------------------------------------------------------------------
Morning tickets         : 4,046
Morning breaches        : 394
Morning breach rate     : 9.74%
Share of all breaches   : 16.15%
Credit exposure         : ₹137,900

TOP AGENT BY BREACH VOLUME
----------------------------------------------------------------------
Agent                   : Krishna Kaur
Agent ID                : A3028
Shift                   : Night
Tickets                 : 203
Breaches                : 136
Breach rate             : 67.00%
Credit exposure         : ₹47,600

TOP AGENT BY BREACH RATE
----------------------------------------------------------------------
Agent                   : Amit Kulkarni
Agent ID                : A3033
Shift                   : Night
Tickets                 : 119
Breaches                : 87
Breach rate             : 73.11%

AI-ASSISTED TICKET ANALYSIS
----------------------------------------------------------------------
Valid AI classifications : 14
Observed breaches        : 7
Observed passes          : 7
Top issue theme          : Delivery & Shipping (3 tickets)
Top operational factor   : Technical Troubleshooting (5 tickets)

RECONCILIATION CHECK
----------------------------------------------------------------------
Calculated exposure     : ₹854,000
Expected exposure       : ₹854,000
Reconciliation passed   : True

FINAL INTERPRETATION
----------------------------------------------------------------------
1. Morning shift has the largest concentration of observed SLA breaches.
2. Breach volume and breach rate should be reviewed separately.
3. Agent-level results should be interpreted with ticket volume context.
4. AI classifications identify descriptive ticket themes, not proven causal drivers.
5. SLA calculations, breach flags, roster joins and financial exposure are deterministic and reproducible.
6. The AI layer is an assistive analysis component rather than the source of truth for SLA measurement.

======================================================================
FINAL EVIDENCE PACK COMPLETE
======================================================================

In [ ]:
# CELL 49 — Generate Final Weekly SLA Reports

print("=" * 70)
print("GENERATING FINAL WEEKLY SLA REPORTS")
print("=" * 70)


# ============================================================
# 1. WEEKLY AGENT-LEVEL REPORT
# ============================================================

weekly_agent_report = (
    analysis
    .groupby(
        [
            "week_start",
            "agent_id",
            "roster_agent_name",
            "operational_shift"
        ]
    )
    .agg(
        tickets=("ticket_id", "count"),
        sla_breaches=("sla_breach", "sum")
    )
    .reset_index()
)

# Calculate breach rate
weekly_agent_report["breach_rate"] = (
    weekly_agent_report["sla_breaches"]
    / weekly_agent_report["tickets"]
    * 100
)

# Calculate automatic store-credit exposure
weekly_agent_report["credit_exposure_inr"] = (
    weekly_agent_report["sla_breaches"] * 350
)

# Rename columns for clean business output
weekly_agent_report = weekly_agent_report.rename(
    columns={
        "roster_agent_name": "agent_name",
        "operational_shift": "shift"
    }
)

# Sort chronologically and then by breach volume
weekly_agent_report = (
    weekly_agent_report
    .sort_values(
        ["week_start", "sla_breaches", "breach_rate"],
        ascending=[True, False, False]
    )
    .reset_index(drop=True)
)


# ============================================================
# 2. WEEKLY SHIFT-LEVEL REPORT
# ============================================================

weekly_shift_report = (
    analysis
    .groupby(
        [
            "week_start",
            "operational_shift"
        ]
    )
    .agg(
        tickets=("ticket_id", "count"),
        sla_breaches=("sla_breach", "sum")
    )
    .reset_index()
)

# Calculate breach rate
weekly_shift_report["breach_rate"] = (
    weekly_shift_report["sla_breaches"]
    / weekly_shift_report["tickets"]
    * 100
)

# Calculate automatic store-credit exposure
weekly_shift_report["credit_exposure_inr"] = (
    weekly_shift_report["sla_breaches"] * 350
)

# Rename for business readability
weekly_shift_report = weekly_shift_report.rename(
    columns={
        "operational_shift": "shift"
    }
)

# Sort chronologically
weekly_shift_report = (
    weekly_shift_report
    .sort_values(
        ["week_start", "shift"]
    )
    .reset_index(drop=True)
)


# ============================================================
# 3. FORMAT REPORT COLUMNS
# ============================================================

weekly_agent_report["week_start"] = pd.to_datetime(
    weekly_agent_report["week_start"]
).dt.strftime("%Y-%m-%d")

weekly_shift_report["week_start"] = pd.to_datetime(
    weekly_shift_report["week_start"]
).dt.strftime("%Y-%m-%d")


# ============================================================
# 4. SAVE REPORTS
# ============================================================

weekly_agent_report.to_csv(
    "weekly_sla_report.csv",
    index=False
)

weekly_shift_report.to_csv(
    "weekly_shift_report.csv",
    index=False
)


# ============================================================
# 5. VALIDATION
# ============================================================

print("\nWEEKLY AGENT REPORT")
print("-" * 70)

print(
    f"Rows generated : "
    f"{len(weekly_agent_report):,}"
)

print(
    f"Columns        : "
    f"{list(weekly_agent_report.columns)}"
)

display(
    weekly_agent_report.head(10)
)


print("\nWEEKLY SHIFT REPORT")
print("-" * 70)

print(
    f"Rows generated : "
    f"{len(weekly_shift_report):,}"
)

print(
    f"Columns        : "
    f"{list(weekly_shift_report.columns)}"
)

display(
    weekly_shift_report.head(10)
)


# ============================================================
# 6. REPORT RECONCILIATION
# ============================================================

agent_total_tickets = (
    weekly_agent_report["tickets"].sum()
)

agent_total_breaches = (
    weekly_agent_report["sla_breaches"].sum()
)

shift_total_tickets = (
    weekly_shift_report["tickets"].sum()
)

shift_total_breaches = (
    weekly_shift_report["sla_breaches"].sum()
)

print("\nREPORT RECONCILIATION")
print("-" * 70)

print(
    f"Source tickets           : {total_tickets:,}"
)

print(
    f"Agent report tickets     : {agent_total_tickets:,}"
)

print(
    f"Shift report tickets     : {shift_total_tickets:,}"
)

print(
    f"Source breaches          : {total_breaches:,}"
)

print(
    f"Agent report breaches    : {agent_total_breaches:,}"
)

print(
    f"Shift report breaches    : {shift_total_breaches:,}"
)

print(
    f"Agent report reconciles  : "
    f"{agent_total_tickets == total_tickets and agent_total_breaches == total_breaches}"
)

print(
    f"Shift report reconciles  : "
    f"{shift_total_tickets == total_tickets and shift_total_breaches == total_breaches}"
)


# ============================================================
# 7. FINAL FILE CONFIRMATION
# ============================================================

print("\nFILES CREATED")
print("-" * 70)

print("✓ weekly_sla_report.csv")
print("✓ weekly_shift_report.csv")

print("\n" + "=" * 70)
print("WEEKLY SLA REPORT GENERATION COMPLETE")
print("=" * 70)

======================================================================
GENERATING FINAL WEEKLY SLA REPORTS
======================================================================

WEEKLY AGENT REPORT
----------------------------------------------------------------------
Rows generated : 4,866
Columns        : ['week_start', 'agent_id', 'agent_name', 'shift', 'tickets', 'sla_breaches', 'breach_rate', 'credit_exposure_inr']

   week_start agent_id       agent_name    shift  tickets  sla_breaches  breach_rate  credit_exposure_inr
0  2024-12-30    A3002     Tarun Mishra    Night        2             0          0.0                    0
1  2024-12-30    A3004    Krishna Naidu      Day        1             0          0.0                    0
2  2024-12-30    A3006    Lakshmi Reddy      Day        2             0          0.0                    0
3  2024-12-30    A3010  Neha Chatterjee  Morning        1             0          0.0                    0
4  2024-12-30    A3015     Yash Agarwal      Day        1             0          0.0                    0
5  2024-12-30    A3016    Deepak Jadhav    Night        1             0          0.0                    0
6  2024-12-30    A3017     Shreya Bhatt      Day        1             0          0.0                    0
7  2024-12-30    A3022    Steven Tiwari  Morning        1             0          0.0                    0
8  2024-12-30    A3023     Rahul Khanna      Day        2             0          0.0                    0
9  2024-12-30    A3024     Kunal Khanna  Morning        2             0          0.0                    0

WEEKLY SHIFT REPORT
----------------------------------------------------------------------
Rows generated : 237
Columns        : ['week_start', 'shift', 'tickets', 'sla_breaches', 'breach_rate', 'credit_exposure_inr']

   week_start    shift  tickets  sla_breaches  breach_rate  credit_exposure_inr
0  2024-12-30      Day       12             0     0.000000                    0
1  2024-12-30  Morning       11             0     0.000000                    0
2  2024-12-30    Night        8             0     0.000000                    0
3  2025-01-06      Day       21             1     4.761905                  350
4  2025-01-06  Morning       16             2    12.500000                  700
5  2025-01-06    Night       13             0     0.000000                    0
6  2025-01-13      Day       23             1     4.347826                  350
7  2025-01-13  Morning       25             5    20.000000                 1750
8  2025-01-13    Night       10             2    20.000000                  700
9  2025-01-20      Day       41             1     2.439024                  350

REPORT RECONCILIATION
----------------------------------------------------------------------
Source tickets           : 11,200
Agent report tickets     : 11,200
Shift report tickets     : 11,200
Source breaches          : 2,440
Agent report breaches    : 2,440
Shift report breaches    : 2,440
Agent report reconciles  : True
Shift report reconciles  : True

FILES CREATED
----------------------------------------------------------------------
✓ weekly_sla_report.csv
✓ weekly_shift_report.csv

======================================================================
WEEKLY SLA REPORT GENERATION COMPLETE
======================================================================

In [ ]:
# CELL 50 — Create Final Excel Business Report

import os
import pandas as pd

print("=" * 70)
print("CREATING FINAL EXCEL BUSINESS REPORT")
print("=" * 70)


# ============================================================
# 1. CREATE EXCEL WORKBOOK
# ============================================================

excel_file = "vireo_weekly_sla_report.xlsx"

with pd.ExcelWriter(
    excel_file,
    engine="openpyxl"
) as writer:

    # Weekly agent report
    weekly_agent_report.to_excel(
        writer,
        sheet_name="Weekly Agent SLA",
        index=False
    )

    # Weekly shift report
    weekly_shift_report.to_excel(
        writer,
        sheet_name="Weekly Shift SLA",
        index=False
    )

    # Executive summary
    summary_data = pd.DataFrame({
        "Metric": [
            "Unique tickets analyzed",
            "SLA passes",
            "SLA breaches",
            "Overall SLA breach rate",
            "Automatic credit exposure (INR)",
            "Morning shift breaches",
            "Morning shift breach rate",
            "Morning share of all breaches"
        ],
        "Value": [
            total_tickets,
            total_passes,
            total_breaches,
            f"{breach_rate:.2f}%",
            credit_exposure,
            morning_breaches,
            f"{morning_breach_rate:.2f}%",
            f"{morning_share_of_breaches:.2f}%"
        ]
    })

    summary_data.to_excel(
        writer,
        sheet_name="Executive Summary",
        index=False
    )


# ============================================================
# 2. BASIC EXCEL FORMATTING
# ============================================================

from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

workbook = load_workbook(excel_file)

for worksheet in workbook.worksheets:

    # Header formatting
    for cell in worksheet[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(
            horizontal="center"
        )

    # Freeze header row
    worksheet.freeze_panes = "A2"

    # Auto-adjust column widths
    for column_cells in worksheet.columns:

        max_length = 0
        column_letter = get_column_letter(
            column_cells[0].column
        )

        for cell in column_cells:

            if cell.value is not None:
                max_length = max(
                    max_length,
                    len(str(cell.value))
                )

        worksheet.column_dimensions[
            column_letter
        ].width = min(
            max_length + 2,
            35
        )


# ============================================================
# 3. FORMAT CURRENCY / PERCENTAGE COLUMNS
# ============================================================

if "Weekly Agent SLA" in workbook.sheetnames:

    ws = workbook["Weekly Agent SLA"]

    headers = {
        cell.value: cell.column
        for cell in ws[1]
    }

    if "breach_rate" in headers:
        col = headers["breach_rate"]

        for row in range(2, ws.max_row + 1):
            ws.cell(row, col).number_format = '0.00'

    if "credit_exposure_inr" in headers:
        col = headers["credit_exposure_inr"]

        for row in range(2, ws.max_row + 1):
            ws.cell(row, col).number_format = '₹#,##0'


if "Weekly Shift SLA" in workbook.sheetnames:

    ws = workbook["Weekly Shift SLA"]

    headers = {
        cell.value: cell.column
        for cell in ws[1]
    }

    if "breach_rate" in headers:
        col = headers["breach_rate"]

        for row in range(2, ws.max_row + 1):
            ws.cell(row, col).number_format = '0.00'

    if "credit_exposure_inr" in headers:
        col = headers["credit_exposure_inr"]

        for row in range(2, ws.max_row + 1):
            ws.cell(row, col).number_format = '₹#,##0'


# Save formatted workbook
workbook.save(excel_file)


# ============================================================
# 4. VALIDATE FILE
# ============================================================

file_exists = os.path.exists(excel_file)
file_size_kb = (
    os.path.getsize(excel_file) / 1024
    if file_exists
    else 0
)

print("\nEXCEL REPORT CREATED")
print("-" * 70)

print(f"File        : {excel_file}")
print(f"Exists      : {file_exists}")
print(f"File size   : {file_size_kb:.1f} KB")

print("\nSheets:")
for sheet in workbook.sheetnames:
    print(f"{sheet}")

print("\n" + "=" * 70)
print("EXCEL BUSINESS REPORT COMPLETE")
print("=" * 70)

======================================================================
CREATING FINAL EXCEL BUSINESS REPORT
======================================================================

EXCEL REPORT CREATED
----------------------------------------------------------------------
File        : vireo_weekly_sla_report.xlsx
Exists      : True
File size   : 164.7 KB

Sheets:
✓ Weekly Agent SLA
✓ Weekly Shift SLA
✓ Executive Summary

======================================================================
EXCEL BUSINESS REPORT COMPLETE
======================================================================